function AbcEndView(){var a=this;a.constructor();var h=a.board.c,n=0,p=0,l=0,m=0;a.uis.puzzle=["ABC End View"];a.enable.vmarkers=!0;a.enable.pgrid=!0;a.enable.values=!1;a.enable.currentValue=!1;a.cell.nilalias=0;a.labels.north=a.labels.south=a.labels.east=a.labels.west=1;a.valueToMarker=[0,a.marker.letterX];a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){var b;try{n=a.labels.west;p=a.labels.north;l=a.size.x-a.labels.east;m=a.size.y-a.labels.south;a.infoText=a.uis.get("letters")+
": A~"+String.fromCharCode(a.size.z+64);a.cell.values=[];var e=0;for(b=1;b<=a.size.z;b++)a.cell.values[e++]=b;a.cell.values[e++]=0;a.cell.values[e++]=nil;for(b=1;b<=a.size.z;b++)a.charToValue=a.charToValue.concat([String.fromCharCode(b+96),b]);a.charToValue=a.charToValue.concat(["x",0,"0",0,",",0,"-",nil,"/",nil]);a.valueToMarker=[];e=0;for(b=1;b<=a.size.z;b++)a.valueToMarker[e++]=b,a.valueToMarker[e++]=a.marker.letterBase+b-1;a.valueToMarker[e++]=0;a.valueToMarker[e++]=a.marker.letterX;e=a.size.z;
a.keypadValues=a.keypad.letters.slice(0,e);a.keypadValues[e++]=["\u00d7",0];a.keypadValues[e++]=["\u2022",nil];if(a.level.problem){b=0;var f=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=p;d<m;d++)for(var c=n;c<l;c++){var k=h[c][d];var g=f[b++];k.value="."==g||"-"==g?nil:"a"<=g&&"z">=g?g.charCodeAt(0)-96:"A"<=g&&"Z">=g?g.charCodeAt(0)-64:parseInt(g);k.value!=nil&&(k.fixed=!0)}}if(a.level.solution)for(b=0,f=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=p;d<m;d++)for(c=
n;c<l;c++)k=h[c][d],g=f[b++],k.solution="."==g||"-"==g?nil:"a"<=g&&"z">=g?g.charCodeAt(0)-96:"A"<=g&&"Z">=g?g.charCodeAt(0)-64:parseInt(g);if(a.level.clabels)for(b=0,f=a.level.clabels.replace(/\s+/g," ").trim().split(" "),d=0;d<a.size.y;d+=m)for(c=n;c<l;c++)k=h[c][d],g=f[b++],k.label="-"==g||"."==g?nil:"a"<=g&&"z">=g?g.charCodeAt(0)-96:"A"<=g&&"Z">=g?g.charCodeAt(0)-64:parseInt(g);if(a.level.rlabels)for(b=0,f=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),c=0;c<a.size.x;c+=l)for(d=p;d<m;d++)k=
h[c][d],g=f[b++],k.label="-"==g||"."==g?nil:"a"<=g&&"z">=g?g.charCodeAt(0)-96:"A"<=g&&"Z">=g?g.charCodeAt(0)-64:parseInt(g);a.reset2labels()}catch(q){throw a.exception(q),q;}};a.check2=function(){try{for(var b=n;b<l;b++){var e=[];for(var f=1;f<=a.size.z;f++)e[f]=nil;for(var d=p;d<m;d++){var c=h[b][d];c.value!=nil&&0!=c.value&&(e[c.value]==nil?e[c.value]=d:h[b][e[c.value]].error=c.error=2)}for(f=1;f<=a.size.z;f++)e[f]==nil&&(a.solved=!1)}for(d=p;d<m;d++){e=[];for(f=1;f<=a.size.z;f++)e[f]=nil;for(b=
n;b<l;b++)c=h[b][d],c.value!=nil&&0!=c.value&&(e[c.value]==nil?e[c.value]=b:h[e[c.value]][d].error=c.error=2);for(f=1;f<=a.size.z;f++)e[f]==nil&&(a.solved=!1)}if(a.level.options.contains("diagonals")){e=[];for(f=1;f<=a.size.z;f++)e[f]=nil;for(var k=1;k<l;k++)c=h[k][k],c.value!=nil&&0!=c.value&&(e[c.value]==nil?e[c.value]=k:h[e[c.value]][e[c.value]].error=c.error=2);for(f=1;f<=a.size.z;f++)e[f]==nil&&(a.solved=!1);for(f=1;f<=a.size.z;f++)e[f]=nil;for(k=1;k<m;k++)c=h[k][a.size.y-k-1],c.value!=nil&&
0!=c.value&&(e[c.value]==nil?e[c.value]=k:h[e[c.value]][a.size.y-e[c.value]-1].error=c.error=2);for(f=1;f<=a.size.z;f++)e[f]==nil&&(a.solved=!1)}for(b=n;b<l;b++)if(0<h[b][0].label)for(d=p;d<m;d++)if(c=h[b][d],c.value!=nil&&0!=c.value)if(c.value!=h[b][0].label)h[b][0].error=1;else break;for(d=p;d<m;d++)if(h[0][d].label!=nil)for(b=n;b<l;b++)if(c=h[b][d],c.value!=nil&&0!=c.value)if(c.value!=h[0][d].label)h[0][d].error=1;else break;for(b=n;b<l;b++)if(h[b][m].label!=nil)for(d=a.size.y-2;0<=d;d--)if(c=
h[b][d],c.value!=nil&&0!=c.value)if(c.value!=h[b][m].label)h[b][m].error=1;else break;for(d=p;d<m;d++)if(h[l][d].label!=nil)for(b=a.size.x-2;0<=b;b--)if(c=h[b][d],c.value!=nil&&0!=c.value)if(c.value!=h[l][d].label)h[l][d].error=1;else break}catch(g){throw a.exception(g),g;}};a.initValueMarkers2=function(){for(var b=n;b<l;b++)for(var e=p;e<m;e++)for(var f=1;f<=a.size.z;f++)h[b][e].markers.set(a.marker.numberBase+f)};a.updateValueMarkers2=function(){for(var b=n;b<l;b++)for(var e=p;e<m;e++){var f=h[b][e];
if(f.value!=nil){for(var d=0;d<a.size.x;d++)h[d][e].markers.clear(a.marker.numberBase+f.value);for(d=0;d<a.size.y;d++)h[b][d].markers.clear(a.marker.numberBase+f.value)}}};a.valueToString=function(a,e){try{return a==nil?"-":0==a?e?"x":"-":String.fromCharCode(a+96)}catch(f){return ojdebug(f.toString()),"%"}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):a.paintValueCell(b)}catch(e){throw a.exception(e),e;}};a.paintLabelCell=function(b){try{var e=a.canvas.getContext("2d");e.fillStyle=
a.uic.label;e.fillRect(b.px,b.py,a.unit.x,a.unit.y);b.label!=nil&&a.paintText(String.fromCharCode(b.label+64),b);b.error&&a.display.errors&&a.paintErrorCircle(b)}catch(f){throw a.exception(f),f;}};a.paintValueCell=function(b){try{var e=a.canvas.getContext("2d");e.fillStyle=a.uic.light[b.color];e.fillRect(b.px,b.py,a.unit.x,a.unit.y);a.level.options.contains("diagonals")&&(b.x==b.y&&a.paintDiagonal(b,1),b.x==a.size.y-b.y-1&&a.paintDiagonal(b,2));a.paintSymbolMarkers(b);a.paintValueMarkers(b);var f=
b.fixed?a.uic.clue:a.uic.text;0==b.value?a.paintCross(b,{color:f,scale:50}):b.value!=nil&&a.paintText(String.fromCharCode(b.value+64),b,{color:f});b.error&&a.display.errors&&(b.value==nil?a.paintErrorDot(b):a.paintErrorCircle(b))}catch(d){throw a.exception(d),d;}}}AbcEndView.prototype=new Puzzle;
