function Arukone(){this.constructor();this.uis.puzzle=["Number Link","Arukone"];var d=this.board.c,q=0,r=0,n=0,p=0,s="strict",h=nil,k=nil;this.charToValue=this.charToValue.concat([",",nil,"x",nil,"-",nil,"/",nil,".",nil]);this.enable.dragging=!0;this.enable.values=!1;this.enable.currentValue=!1;this.keypad.left=nil;this.reset2=function(){try{q=this.labels.west;r=this.labels.north;n=this.size.x-this.labels.east;p=this.size.y-this.labels.south;this.enable.pgrid=!0;if(this.level.variant){var a=this.level.variant;
if("strict"==a||"loose"==a||"tim"==a)s=a}else s="strict";if(this.level.problem)for(var b=0,c=this.level.problem.replace(/\s+/g," ").trim().split(" "),l=r;l<p;l++)for(var m=q;m<n;m++){var f=d[m][l],a=c[b++];"."==a||"-"==a?f.label=nil:"#"==a||"x"==a?(f.label=-2,f.fixed=!0):"@"==a?(f.areas=this.cell.outside,f.label=-2,f.fixed=!0,f.valid=!1,this.enable.pgrid=!1):f.label=parseInt(a)}if(this.level.solution){b=0;c=this.level.solution.replace(/\s+/g," ").trim().split(" ");for(l=r;l<p;l++)for(m=q;m<n;m++)if(f=
d[m][l],a=c[b++],"-"==a||"."==a)f.solution=nil;else{var g=0;a.contains("n")&&(g|=1);a.contains("s")&&(g|=4);if(a.contains("e")||a.contains("o"))g|=2;a.contains("w")&&(g|=8);0!=g&&(f.solution=g)}}}catch(e){throw this.exception(e),e;}};var e,t,v,u;this.check2=function(){try{t=0;for(var a=q;a<n;a++)for(var b=r;b<p;b++){var c=d[a][b];if(c.label>nil&&!c.checked)if(e=!1,t++,v=0,this.checkPath(c,null),e){c.error=1;for(var l=q;l<n;l++)for(var m=r;m<p;m++){var f=d[l][m];f.count==t&&(f.error=1)}}else u.label!=
c.label&&(c.error=3,u.error=3)}for(a=q;a<n;a++)for(b=r;b<p;b++)c=d[a][b],c.value!=nil&&!c.checked&&(d[a][b].error=1);if("strict"!=s)for(a=q;a<n;a++)for(b=r;b<p;b++)c=d[a][b],c.value==nil&&-2!=c.label&&(c.error=2);if("tim"==s)for(a=q;a<n-1;a++)for(b=r;b<p-1;b++)c=d[a][b],c.value!=nil&&(c.count==d[a+1][b].count&&c.count==d[a][b+1].count&&c.count==d[a+1][b+1].count)&&(d[a][b].error=4,d[a+1][b].error=4,d[a][b+1].error=4,d[a+1][b+1].error=4)}catch(g){throw this.exception(g),g;}};this.checkPath=function(a,
b){try{a.value==nil?e=!0:(u=a,a.checked?e=!0:(a.checked=!0,a.count=t,v++,a.label!=nil&&1!=a.value&&4!=a.value&&2!=a.value&&8!=a.value?e=!0:(1==a.value||4==a.value||2==a.value||8==a.value)&&a.label==nil?e=!0:(b&&(a.x-1==b.x&&0==(a.value&8)&&(e=!0),a.x+1==b.x&&0==(a.value&2)&&(e=!0),a.y-1==b.y&&0==(a.value&1)&&(e=!0),a.y+1==b.y&&0==(a.value&4)&&(e=!0)),e||(0!=(a.value&8)&&(0==a.x?e=!0:(null==b||b.x!=a.x-1)&&this.checkPath(d[a.x-1][a.y],a)),0!=(a.value&2)&&(a.x==n-1?e=!0:(null==b||b.x!=a.x+1)&&this.checkPath(d[a.x+
1][a.y],a)),0!=(a.value&1)&&(0==a.y?e=!0:(null==b||b.y!=a.y-1)&&this.checkPath(d[a.x][a.y-1],a)),0!=(a.value&4)&&(a.y==p-1?e=!0:(null==b||b.y!=a.y+1)&&this.checkPath(d[a.x][a.y+1],a))))))}catch(c){throw this.exception(c),c;}};this.dragTo2=function(a,b){try{if(!(a.fixed||a.areas==this.cell.outside)){if(a.x==b.x-1&&b.y==a.y){switch(b.value){case nil:case 16:case 0:this.makeMove(b,8);break;case 10:this.makeMove(b,10);break;case 12:this.makeMove(b,12);break;case 9:this.makeMove(b,9);break;case 1:this.makeMove(b,
9);break;case 2:this.makeMove(b,10);break;case 4:this.makeMove(b,12);break;case 8:this.makeMove(b,8);break;case 5:k==b.y-1?this.makeMove(b,9):k==b.y+1?this.makeMove(b,12):this.makeMove(b,8);break;case 3:k==b.y-1?this.makeMove(b,9):h==b.x+1?this.makeMove(b,10):this.makeMove(b,8);break;case 6:k==b.y+1?this.makeMove(b,12):h==b.x+1?this.makeMove(b,10):this.makeMove(b,8)}b.label!=nil&&this.makeMove(b,8);switch(a.value){case nil:case 16:case 0:this.makeMove(a,2);break;case 5:this.makeMove(a,2);break;case 10:this.makeMove(a,
10);break;case 3:this.makeMove(a,3);break;case 6:this.makeMove(a,6);break;case 12:this.makeMove(a,2);break;case 9:this.makeMove(a,2);break;case 1:this.makeMove(a,3);break;case 2:this.makeMove(a,2);break;case 4:this.makeMove(a,6);break;case 8:this.makeMove(a,10)}a.label!=nil&&this.makeMove(a,2)}if(a.x==b.x+1&&b.y==a.y){switch(b.value){case nil:case 16:case 0:this.makeMove(b,2);break;case 10:this.makeMove(b,10);break;case 3:this.makeMove(b,3);break;case 6:this.makeMove(b,6);break;case 1:this.makeMove(b,
3);break;case 2:this.makeMove(b,2);break;case 4:this.makeMove(b,6);break;case 8:this.makeMove(b,10);break;case 5:k==b.y-1?this.makeMove(b,3):k==b.y+1?this.makeMove(b,6):this.makeMove(b,2);break;case 12:h==b.x-1?this.makeMove(b,10):k==b.y+1?this.makeMove(b,6):this.makeMove(b,2);break;case 9:k==b.y-1?this.makeMove(b,3):h==b.x-1?this.makeMove(b,10):this.makeMove(b,2)}b.label!=nil&&this.makeMove(b,2);switch(a.value){case nil:case 16:case 0:this.makeMove(a,8);break;case 5:this.makeMove(a,8);break;case 10:this.makeMove(a,
10);break;case 3:this.makeMove(a,8);break;case 6:this.makeMove(a,8);break;case 12:this.makeMove(a,12);break;case 9:this.makeMove(a,9);break;case 1:this.makeMove(a,9);break;case 2:this.makeMove(a,10);break;case 4:this.makeMove(a,12);break;case 8:this.makeMove(a,8)}a.label!=nil&&this.makeMove(a,8)}if(a.y==b.y+1&&b.x==a.x){switch(b.value){case nil:case 16:case 0:this.makeMove(b,4);break;case 6:this.makeMove(b,6);break;case 12:this.makeMove(b,12);break;case 1:this.makeMove(b,5);break;case 2:this.makeMove(b,
6);break;case 4:this.makeMove(b,4);break;case 8:this.makeMove(b,12);break;case 5:this.makeMove(b,5);break;case 10:h==b.x-1?this.makeMove(b,12):h==b.x+1?this.makeMove(b,6):this.makeMove(b,4);break;case 3:k==b.y-1?this.makeMove(b,5):h==b.x+1?this.makeMove(b,6):this.makeMove(b,4);break;case 9:h==b.x-1?this.makeMove(b,12):k==b.y-1?this.makeMove(b,5):this.makeMove(b,4)}b.label!=nil&&this.makeMove(b,4);switch(a.value){case nil:case 16:case 0:this.makeMove(a,1);break;case 5:this.makeMove(a,5);break;case 10:this.makeMove(a,
1);break;case 3:this.makeMove(a,3);break;case 6:this.makeMove(a,1);break;case 12:this.makeMove(a,1);break;case 9:this.makeMove(a,9);break;case 1:this.makeMove(a,1);break;case 2:this.makeMove(a,3);break;case 4:this.makeMove(a,5);break;case 8:this.makeMove(a,9)}a.label!=nil&&this.makeMove(a,1)}if(a.y==b.y-1&&b.x==a.x){switch(b.value){case nil:case 16:case 0:this.makeMove(b,1);break;case 5:this.makeMove(b,5);break;case 3:this.makeMove(b,3);break;case 9:this.makeMove(b,9);break;case 1:this.makeMove(b,
1);break;case 2:this.makeMove(b,3);break;case 4:this.makeMove(b,5);break;case 8:this.makeMove(b,9);break;case 10:h==b.x-1?this.makeMove(b,9):h==b.x+1?this.makeMove(b,3):this.makeMove(b,1);break;case 6:k==b.y+1?this.makeMove(b,5):h==b.x+1?this.makeMove(b,6):this.makeMove(b,4);break;case 12:h==b.x-1?this.makeMove(b,3):k==b.y+1?this.makeMove(b,5):this.makeMove(b,4)}b.label!=nil&&this.makeMove(b,1);switch(a.value){case nil:case 16:case 0:this.makeMove(a,4);break;case 5:this.makeMove(a,5);break;case 10:this.makeMove(a,
4);break;case 3:this.makeMove(a,4);break;case 6:this.makeMove(a,6);break;case 12:this.makeMove(a,12);break;case 9:this.makeMove(a,4);break;case 1:this.makeMove(a,5);break;case 2:this.makeMove(a,6);break;case 4:this.makeMove(a,4);break;case 8:this.makeMove(a,12)}a.label!=nil&&this.makeMove(a,4)}h=b.x;k=b.y;this.moveTo(a)}}catch(c){throw this.exception(c),c;}};this.dragTo2Alt=function(a,b){try{b.value!=nil&&this.makeMove(b,nil,this.current.color),a.value!=nil&&this.makeMove(a,nil,this.current.color),
this.moveTo(a)}catch(c){throw this.exception(c),c;}};this.valueToString=function(a,b){switch(a){case 16:return b?"x":"-";case 15:return"nsew";case 0:return"o";case 4:return"s";case 1:return"n";case 2:return"e";case 8:return"w";case 3:return"ne";case 9:return"nw";case 6:return"se";case 12:return"sw";case 5:return"ns";case 10:return"ew";default:return"-"}};this.paintCell=function(a){try{var b=this.canvas.getContext("2d");b.fillStyle=-2==a.label?this.uic.hole:this.uic.light[0];b.fillRect(a.px,a.py,this.unit.x,
this.unit.y);if(a.value!=nil){var c=Math.floor((this.unit.x-Math.floor(this.unit.x/4))/2),d=this.unit.x-2*c,e=d+c;b.fillStyle=0==a.color?this.uic.line:this.uic.light[a.color];16==a.value&&!this.solved&&this.paintCross(a);0==a.value&&b.fillRect(a.px+c,a.py+c,d,d);0!=(a.value&1)&&b.fillRect(a.px+c,a.py,d,e);0!=(a.value&4)&&b.fillRect(a.px+c,a.py+c,d,e);0!=(a.value&2)&&b.fillRect(a.px+c,a.py+c,e,d);0!=(a.value&8)&&b.fillRect(a.px,a.py+c,e,d)}if(a.label!=nil&&-2!=a.label){var f=10<a.label?50:60;this.paintCircle(a,
{fill:this.uic.line,stroke:this.uic.line,scale:80});this.paintText(a.label.toString(),a,{scale:f})}this.paintSymbolMarkers(a);a.error&&this.display.errors&&(4==a.error?this.paintErrorSquare(a):a.label!=nil?this.paintErrorCircle(a):this.paintErrorDot(a))}catch(g){throw this.exception(g),g;}}}Arukone.prototype=new Puzzle;
