function Battleships(){var a=this;a.constructor();a.uis.puzzle=["Battleships"];var g=a.board.c,q=0,r=0,n=0,p=0,v,t,y,z;a.variant.ships=["battleships",["Battelships"]];a.variant.mines=["battlemines",["Battlemines"]];a.variant.digital=["battledigit",["Battelships (Digital)"]];a.variant.retro=["battleretro",["Battelships (Retrograde)"]];a.variant.houses=["battlehouse",["Battelships (Lighthouses)"]["Battelships (Leuchtt\u00fcrme)"]];var B=[1,0,-1,0,1,1,-1,-1],C=[0,1,0,-1,-1,1,-1,1],x=0,A=[],w=[];a.enable.dragging=
!0;a.enable.values=!1;a.enable.currentValue=!1;a.cell.nilalias=0;a.keys=a.keys.concat(["ships"]);a.uic.counter="#ffaacc";a.uic.aside="#999999";a.uic.clue="#8888ff";a.uis.ships=["Ships","Schiffe","Navires","Navi"];a.cell.values=[0,1,7,2,3,5,4,6,nil];a.charToValue=a.charToValue.concat(["n",3,"s",4,"e",5,"w",6,"m",7,"o",2,"?",1,".",1,"#",1,"x",0,",",0,"-",nil,"/",nil]);a.keypadValues=[["\ud83c\udf11",2],["\u25b2",3],["?",1],["\u00d7",0],["\u25c4",6],["\u25a0",7],["\u25ba",5],["\u2022",nil],[" ",1],["\u25bc",
4],[" ",1]];a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.setup2=function(){try{a.level.ships||(a.level.ships="4 3 2 1"),!a.level.puzzle&&a.level.variant&&(a.level.puzzle=a.level.variant),a.variant.init(a.variant.ships),a.variant.is(a.variant.mines)||(a.labels.west=a.labels.north=1),x=a.level.ships.replace(/\s+/g," ").trim().split(" ").length,a.labels.east=x+3,q=a.labels.west,r=a.labels.north,n=a.size.x+q,p=a.size.y+r,z=n+1,y=z+1,t=y+1,v=a.size.y+a.labels.north-x}catch(b){throw a.exception(b),
b;}};a.reset2=function(){var b;try{a.variant.is(a.variant.retro)?(a.keypad.left=nil,a.keypadValues=null):a.keypadValues=[[a.paintShipO,2],[a.paintShipN,3],["?",1],["\u00d7",0],[a.paintShipW,6],[a.paintShipM,7],[a.paintShipE,5],["\u2022",nil],[" ",nil],[a.paintShipS,4],[" ",nil]];if(a.level.ships){for(b=1;8>=b;b++)A[b]=0;var f=a.level.ships.replace(/\s+/g," ").trim().split(" ");for(b=0;b<f.length;b++)A[b]=parseInt(f[b])}if(a.level.problem){b=0;var c=a.level.problem.replace(/\s+/g," ").trim().split(" ");
for(var d=r;d<p;d++)for(var k=q;k<n;k++){var e=g[k][d];var h=c[b++];"-"==h||"."==h?e.value=nil:"n"==h?e.value=3:"s"==h?e.value=4:"e"==h?e.value=5:"w"==h?e.value=6:"m"==h?e.value=7:"o"==h?e.value=2:"?"==h?e.value=1:"x"==h?e.value=0:e.label=parseInt(h);e.value!=nil&&(e.fixed=!0);a.variant.is(a.variant.mines)&&e.label!=nil&&(e.fixed=!0);a.variant.is(a.variant.retro)&&(e.label=e.value,e.value=nil,e.fixed=!1)}}if(a.level.solution)for(b=0,c=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=r;d<p;d++)for(k=
q;k<n;k++)e=g[k][d],h=c[b++],"-"==h||"."==h||"x"==h?e.solution=nil:"n"==h?e.solution=3:"s"==h?e.solution=4:"e"==h?e.solution=5:"w"==h?e.solution=6:"m"==h?e.solution=7:"o"==h?e.solution=2:(e.label=parseInt(h),e.fixed=!0);if(a.level.clabels)for(b=0,c=a.level.clabels.replace(/\s+/g," ").trim().split(" "),k=q;k<n;k++)e=g[k][0],h=c[b++],e.label="-"==h||"."==h?nil:parseInt(h);if(a.level.rlabels)for(b=0,c=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),d=r;d<p;d++)e=g[0][d],h=c[b++],e.label="-"==h||
"."==h?nil:parseInt(h);if((a.variant.is(a.variant.ships)||a.variant.is(a.variant.digital))&&!a.level.clabels&&!a.level.clabels&&a.level.solution){for(k=q;k<n;++k)for(e=g[k][0],e.label=0,d=r;d<p;++d){var l=g[k][d];l.solution!=nil&&0!=l.solution&&(a.variant.is(a.variant.ships)?e.label++:e.label+=l.label)}for(d=r;d<p;++d)for(e=g[0][d],e.label=0,k=q;k<n;++k)l=g[k][d],l.solution!=nil&&0!=l.solution&&(a.variant.is(a.variant.ships)?e.label++:e.label+=l.label)}for(d=0;d<a.size.y;++d)for(k=0;k<a.size.x;++k){if(k<
q||d<r)g[k][d].valid=!1,g[k][d].fixed=!0,g[k][d].areas=a.cell.label;k>=n&&(g[k][d].valid=!1,g[k][d].fixed=!0,g[k][d].areas=a.cell.aside)}for(b=0;b<x;b++)if(g[y][v+b].label=A[b],0==b)g[t][v].label=2;else for(g[t][v+b].label=6,g[t+b][v+b].label=5,l=t+1;l<t+b;l++)g[l][v+b].label=7}catch(m){throw a.exception(m),m;}};a.check2=function(){var b;try{for(var f=1;8>=f;f++)w[f]=0;var c=0;if(a.variant.is(a.variant.ships)||a.variant.is(a.variant.digital))for(var d=r;d<p;d++){var k=0;for(var e=q;e<n;e++){var h=
g[e][d];h.value!=nil&&0!=h.value&&(a.variant.is(a.variant.ships)?k++:k+=h.label)}h=g[0][d];h.label!=nil&&h.label!=k&&(g[0][d].error=2)}if(a.variant.is(a.variant.ships)||a.variant.is(a.variant.digital))for(e=q;e<n;e++){k=0;for(d=r;d<p;d++)h=g[e][d],h.value!=nil&&0!=h.value&&(a.variant.is(a.variant.ships)?k++:k+=h.label);h=g[e][0];h.label!=nil&&h.label!=k&&(g[e][0].error=2)}if(a.variant.is(a.variant.mines))for(e=q;e<n;e++)for(d=r;d<p;d++)if(g[e][d].label!=nil){for(f=b=0;8>f;f++){var l=e+B[f];var m=
d+C[f];l>=q&&l<n&&m>=r&&m<p&&1<g[l][m].value&&b++}g[e][d].label!=b&&(g[e][d].error=2)}if(a.variant.is(a.variant.houses))for(e=q;e<n;e++)for(d=r;d<p;d++)if(g[e][d].label!=nil){for(f=b=0;4>f;f++)for(l=e,m=d;l>=q&&l<n&&m>=r&&m<p;)1<g[l][m].value&&b++,l+=B[f],m+=C[f];g[e][d].label!=b&&(g[e][d].error=2)}for(e=q;e<n;e++)for(d=r;d<p;d++)switch(g[e][d].value){case 1:g[e][d].error=1;break;case 2:w[1]++;c++;g[e][d].count=c;break;case 3:c++;g[e][d].count=c;var u=1;var t=!1;for(m=d+1;m<p;m++)if(7==g[e][m].value){if(u++,
g[e][m].count=c,m==p-1){g[e][m].error=1;break}}else{4==g[e][m].value?(u++,w[u]++,g[e][m].count=c):t=!0;break}if(t)for(f=0;f<u;f++)g[e][d+f].error=1;break;case 6:c++;g[e][d].count=c;u=1;t=!1;for(l=e+1;l<n;l++)if(7==g[l][d].value)u++,g[l][d].count=c,l==n-1&&(g[l][d].error=1);else{5==g[l][d].value?(u++,w[u]++,g[l][d].count=c):t=!0;break}if(t)for(f=0;f<u;f++)g[e+f][d].error=1;break;case 5:case 4:case 7:1>g[e][d].count&&(g[e][d].error=1)}for(f=1;8>=f;f++)w[f]!=A[f-1]&&(a.solved=!1);for(e=q;e<n;e++)for(d=
r;d<p;d++)if(g[e][d].value!=nil&&0!=g[e][d].value)for(f=0;8>f;f++)l=e+B[f],m=d+C[f],0<=l&&l<n&&0<=m&&m<p&&g[l][m].value!=nil&&0!=g[l][m].value&&g[l][m].count!=g[e][d].count&&(g[e][d].error=g[l][m].error=3);for(f=1;f<=x;f++)g[z][v+f-1].label=w[f]}catch(D){throw a.exception(D),D;}};a.moveTo2=function(b,f,c){try{a.variant.is(a.variant.retro)&&(a.cell.values=[b.label,0,nil])}catch(d){throw a.exception(d),d;}};a.dragTo2=function(b,f){try{var c=0;a.variant.is(a.variant.retro)?(c=f.value,0!=c&&c!=nil&&(c=
b.label),a.cell.values=[c,0,nil]):(c=f.value,4==c&&f.x==b.x&&f.y==b.y+1&&(c=7),3==c&&f.x==b.x&&f.y==b.y-1&&(c=7),5==c&&f.y==b.y&&f.x==b.x+1&&(c=7),6==c&&f.y==b.y&&f.x==b.x-1&&(c=7),7!=c&&1!=c&&c!=nil&&(c=0));a.makeMove(b,c,a.current.color)}catch(d){throw a.exception(d),d;}};a.valueToString=function(b,f){try{switch(b){case nil:return"-";case 0:return f?"x":"-";case 1:return"?";case 7:return"m";case 2:return"o";case 3:return"n";case 4:return"s";case 5:return"e";case 6:return"w"}return a.numberToString(b)}catch(c){return ojdebug(c.toString()),
"%"}};a.paintInit=function(){try{var b=a.size.x,f=a.labels.east;a.paintToImage&&a.solved&&(a.size.x=n,a.labels.east=0);Object.getPrototypeOf(this).paintInit.call(this);a.labels.east=f;a.size.x=b}catch(c){throw a.exception(c),c;}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):b.areas==a.cell.aside?a.paintAsideCell(b):a.paintValueCell(b)}catch(f){throw a.exception(f),f;}};a.paintLabelCell=function(b){try{b.label!=nil&&a.paintText(b.label.toString(),b),b.error&&a.display.errors&&
a.paintErrorCircle(b)}catch(f){throw a.exception(f),f;}};a.paintAsideCell=function(b){try{if(b.label!=nil)if(b.x==z){var f=a.canvas.getContext("2d");f.fillStyle=f.strokeStyle=a.uic.counter;a.paintSquare(b,{fill:a.uic.counter,stroke:a.uic.counter,scale:80});a.paintText(b.label.toString(),b)}else b.x==y?a.paintText(b.label.toString()+"\u00d7",b):a.paintShip(b.label,b,{color:a.uic.aside})}catch(c){throw a.exception(c),c;}};a.paintValueCell=function(b){try{var f=a.canvas.getContext("2d");f.fillStyle=
a.uic.light[0];f.fillRect(b.px,b.py,a.unit.x,a.unit.y);if(a.variant.is(a.variant.retro)&&b.label!=nil){var c=a.uic.gray;b.error&&a.display.errors&&(c=a.uic.error);a.paintShip(b.label,b,{color:c})}b.value!=nil&&(c=a.uic.text,c=b.fixed?a.uic.clue:a.uic.dark[b.color],b.error&&a.display.errors&&(c=a.uic.error),a.paintShip(b.value,b,{color:c}));a.variant.is(a.variant.retro)||b.label==nil||(c=b.value==nil?a.uic.black:a.uic.white,a.paintText(b.label.toString(),b,{color:c}),b.error&&a.display.errors&&a.paintErrorCircle(b));
a.paintSymbolMarkers(b)}catch(d){throw a.exception(d),d;}};a.paintShipN=function(b,f){a.paintShip(3,b,f)};a.paintShipS=function(b,f){a.paintShip(4,b,f)};a.paintShipE=function(b,f){a.paintShip(5,b,f)};a.paintShipW=function(b,f){a.paintShip(6,b,f)};a.paintShipM=function(b,f){a.paintShip(7,b,f)};a.paintShipO=function(b,f){a.paintShip(2,b,f)};a.paintShip=function(b,f,c){try{if(c=a.defaultParams(f,c))f.px&&(f=a.canvas.getContext("2d")),c.fill=c.color?c.stroke=c.color:c.stroke=a.uic.black,0==b?a.paintCross(f,
c):1==b?(c.scale=40,c.fill=a.uic.none,a.paintSquare(f,c)):7==b?(c.scale=80,a.paintSquare(f,c)):2==b?(c.scale=80,a.paintCircle(f,c)):(a.paintCircle(f,c),5==b&&(c.w/=2,c.scale=60),6==b&&(c.x+=c.w/2,c.w/=2,c.scale=60),4==b&&(c.h/=2,c.scale=80),3==b&&(c.y+=c.h/2,c.h/=2,c.scale=80),a.paintSquare(f,c))}catch(d){throw a.exception(d),d;}}}Battleships.prototype=new Puzzle;
