function Doors(){var a=this;a.constructor();a.uis.puzzle=["Doors","T\u00fcren"];var g=a.board.c,h=a.board.h,k=a.board.v,p=0,q=0,l=0,m=0;a.charToValue=a.charToValue.concat(["8",1,"2",4,"4",8,"6",2,"i",1,"m",4,"j",8,"k",2]);a.line.values=[a.line.wall,a.line.cross,a.line.grid];a.enable.pnodes=!0;a.enable.lines=!0;a.enable.cells=!a.config.touch;a.enable.dragging=!0;a.enable.pgridlines=!0;a.enable.pedgelines=!0;a.keypad.left=nil;a.uic.seen="#ffff00";a.init=function(){Object.getPrototypeOf(a).init.call(a)};
a.reset2=function(){try{p=a.labels.west;q=a.labels.north;l=a.size.x-a.labels.east;m=a.size.y-a.labels.south;if(a.level.problem){var b=0;var c=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=0;d<m;d++)for(var e=0;e<l;e++){var f=g[e][d];var n=c[b++];f.label="."==n||"-"==n?nil:parseInt(n);f.label!=nil&&(f.fixed=!0)}}a.level.lines&&a.reset2lines(p,q,l,m,a.level.lines);if(a.level.solution)for(b=0,c=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=0;d<m;d++)for(e=0;e<l;e++)n=c[b++],
g[e][d].solution=n,0!=(n&1)&&(h[e][d].solution=a.line.wall),0!=(n&4)&&(h[e][d+1].solution=a.line.wall),0!=(n&8)&&(k[e][d].solution=a.line.wall),0!=(n&2)&&(k[e+1][d].solution=a.line.wall);for(e=0;e<l;e++)h[e][0].valid=!1,h[e][0].value=a.line.wall,h[e][m].valid=!1,h[e][m].value=a.line.wall;for(d=0;d<m;d++)k[0][d].valid=!1,k[0][d].value=a.line.wall,k[l][d].valid=!1,k[l][d].value=a.line.wall}catch(r){throw a.exception(r),r;}};a.check2=function(){try{for(var b=0;b<l;b++)for(var c=0;c<m;c++)if(g[b][c].label!=
nil){for(var d=0,e=b;0<=e&&k[e][c].value!=a.line.wall;e--)d++;for(e=b;e<l-1&&k[e+1][c].value!=a.line.wall;e++)d++;for(e=c;0<=e&&h[b][e].value!=a.line.wall;e--)d++;for(e=c;e<m-1&&h[b][e+1].value!=a.line.wall;e++)d++;g[b][c].label!=d&&(g[b][c].error=1)}d=1;for(b=0;b<l;b++)for(c=0;c<m;c++)0==g[b][c].count&&a.markArea(b,c,d++);2!=d&&(a.solved=!1);for(b=0;b<l;b++)for(c=0;c<m;c++){var f=g[b][c];f.value=0;h[b][c].value==a.line.wall&&(f.value|=1);h[b][c+1].value==a.line.wall&&(f.value|=4);k[b][c].value==
a.line.wall&&(f.value|=8);k[b+1][c].value==a.line.wall&&(f.value|=2)}}catch(n){throw a.exception(n),n;}};a.markArea=function(b,c,d){try{g[b][c].count=d,0!=b&&0==g[b-1][c].count&&k[b][c].value!=a.line.wall&&a.markArea(b-1,c,d),b!=l-1&&0==g[b+1][c].count&&k[b+1][c].value!=a.line.wall&&a.markArea(b+1,c,d),0!=c&&0==g[b][c-1].count&&h[b][c].value!=a.line.wall&&a.markArea(b,c-1,d),c!=m-1&&0==g[b][c+1].count&&h[b][c+1].value!=a.line.wall&&a.markArea(b,c+1,d)}catch(e){throw a.exception(e),e;}};a.showSolution2=
function(){try{for(var b=0;b<a.board.l.length;b++){var c=a.board.l[b];c.value=c.solution}}catch(d){throw a.exception(d),d;}};a.makeMove22=function(b,c,d){try{var e=b;c&&(1==c?b=h[b.x][b.y]:4==c?b=h[b.x][b.y+1]:8==c?b=k[b.x][b.y]:2==c&&(b=k[b.x+1][b.y]));if(e!=b){if(b.fixed||!b.valid)return;c=null}Object.getPrototypeOf(this).makeMove2.call(this,b,c,d);e!=b&&(a.current.item=e)}catch(f){throw a.exception(f),f;}};a.onValues=function(){try{a.config.touch?a.enable.lines?(a.enable.lines=!1,a.enable.cells=
!0):(a.enable.lines=!0,a.enable.cells=!1):Object.getPrototypeOf(this).onValues.call(this)}catch(b){throw a.exception(b),b;}};a.paintCells=function(){try{for(var b=0;b<l;b++)for(var c=0;c<m;c++)g[b][c].marked=!1;if(null!=a.current.item&&a.current.item.type==a.item.cell){var d=a.current.item.x,e=a.current.item.y;for(b=d;0<=b&&(g[b][e].marked=!0,k[b][e].value!=a.line.wall);b--);for(b=d;b<l&&(g[b][e].marked=!0,k[b+1][e].value!=a.line.wall);b++);for(c=e;0<=c&&(g[d][c].marked=!0,h[d][c].value!=a.line.wall);c--);
for(c=e;c<m&&(g[d][c].marked=!0,h[d][c+1].value!=a.line.wall);c++);a.current.item.marked=!1}Object.getPrototypeOf(this).paintCells.call(this)}catch(f){throw a.exception(f),f;}};a.paintCell=function(b){try{var c=a.canvas.getContext("2d");if(!a.solved&&a.display.errors){var d=(b.count-1)%10;c.fillStyle=0==d?a.uic.gray:a.uic.light[d]}else c.fillStyle=a.uic.light[b.color];c.fillRect(b.px,b.py,a.unit.x,a.unit.y);b.marked&&a.paintCircle(b,{fill:a.uic.seen,stroke:a.uic.none});b.label!=nil&&a.paintText(b.label.toString(),
b);a.paintSymbolMarkers(b);b.error&&a.display.errors&&a.paintErrorCircle(b)}catch(e){throw a.exception(e),e;}};a.paintNode=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.wall;c.fillRect(b.px+.5-a.uim.wall/2,b.py+.5-a.uim.wall/2,a.uim.wall,a.uim.wall)}catch(d){throw a.exception(d),d;}};a.paintCurrentValue=function(){try{var b=a.uie.value,c=b.getContext("2d");c.fillStyle=a.uic.white;c.fillRect(0,0,b.width,b.height);a.enable.lines&&a.paintText("#",c,{x:0,y:0,w:b.width,h:b.height,scale:90})}catch(d){throw a.exception(d),
d;}}}Doors.prototype=new Puzzle;
