function Fillomino(){var a=this;a.constructor();var f=a.board.c;rlist=a.rlist;var m=0,n=0,k=0,l=0;a.uis.puzzle=["Fillomino"];a.variant.std=["std",["Fillomino"]];a.variant.cipher=["cipher",["Fillomino (Cipher)"]];a.variant.liar=["liar",["Fillomino (Liar)","Fillomino (L\u00fcgner)"]];a.variant.minimize=["minimize",["Minimize"]];a.variant.maximize=["maximize",["Maximize"]];a.variant.cross=["cross"];a.uic.done="#dddddd";a.enable.dragging=!0;a.enable.cells=!0;a.enable.lines=!a.config.touch;a.keypadValues=
a.keypad.numbers;a.line.values=[a.line.wall,a.line.cross,a.line.grid];a.cell.min=1;a.cell.max=999;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.setup2=function(){try{if(a.labels.north=a.labels.south=a.labels.east=a.labels.west=0,a.level.nlabels){var c=a.level.nlabels.replace(/\s+/g," ").trim().split(" ");a.labels.west=parseInt(c[0]);a.labels.north=parseInt(c[1]);a.labels.east=parseInt(c[2]);a.labels.south=parseInt(c[3])}}catch(e){throw a.exception(e),e;}};a.reset2=function(){try{m=a.labels.west;
n=a.labels.north;k=a.size.x-a.labels.east;l=a.size.y-a.labels.south;a.level.depth&&(a.cell.max=parseInt(a.level.depth));a.level.options.contains("cross")?(a.charToValue=["/",nil,"-",nil,",",nil,"x",0],a.cell.min=0):(a.charToValue=["/",nil,"-",nil,",",nil],a.cell.min=1);!a.level.puzzle&&a.level.variant&&(a.level.puzzle=a.level.variant);a.variant.init(a.variant.std);if(a.level.problem){var c=0;var e=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var b=n;b<l;b++)for(var d=m;d<k;d++){var h=
f[d][b];var g=e[c++];"."==g||"-"==g?h.value=nil:"@"==g?(h.areas=a.cell.outside,h.fixed=!0,h.valid=!1):"#"==g?(h.label=0,h.value=0,h.valid=!1):a.level.options.contains("cross")&&"x"==g?h.value=0:a.variant.is(a.variant.cipher)||a.variant.is(a.variant.liar)?h.label="a"<=g&&"z">=g?g.charCodeAt(0)+1E3-96:"A"<=g&&"Z">=g?g.charCodeAt(0)+1E3-64:parseInt(g):h.value=parseInt(g);h.value!=nil&&(h.fixed=!0)}}if(a.level.clabels){c=0;e=a.level.clabels.replace(/\s+/g," ").trim().split(" ");for(b=0;b<a.labels.north;b++)for(d=
m;d<k;d++)h=f[d][b],g=e[c++],h.label="-"==g||"."==g?nil:parseInt(g);for(b=a.size.y-a.labels.south;b<a.size.y;b++)for(d=m;d<k;d++)h=f[d][b],g=e[c++],h.label="-"==g||"."==g?nil:parseInt(g)}if(a.level.rlabels){c=0;e=a.level.rlabels.replace(/\s+/g," ").trim().split(" ");for(d=0;d<a.labels.west;d++)for(b=n;b<l;b++)h=f[d][b],g=e[c++],h.label="-"==g||"."==g?nil:parseInt(g);for(d=a.size.x-a.labels.east;d<a.size.x;d++)for(b=n;b<l;b++)h=f[d][b],g=e[c++],h.label="-"==g||"."==g?nil:parseInt(g)}a.reset2labels();
if(a.level.solution)for(c=0,e=a.level.solution.replace(/\s+/g," ").trim().split(" "),b=n;b<l;b++)for(d=m;d<k;d++)h=f[d][b],g=e[c++],h.solution="."==g||"-"==g||"0"==g?nil:"x"==g?0:parseInt(g);if(a.level.lines)for(c=0,e=a.level.lines.replace(/\s+/g," ").trim().split(" "),b=n;b<l;b++)for(d=m;d<k;d++)g=e[c++],0!=(g&4)&&(a.board.v[d][b].value=a.line.wall,a.board.v[d][b].fixed=!0),0!=(g&1)&&(a.board.v[d+1][b].value=a.line.wall,a.board.v[d+1][b].fixed=!0),0!=(g&8)&&(a.board.h[d][b].value=a.line.wall,a.board.h[d][b].fixed=
!0),0!=(g&2)&&(a.board.h[d][b+1].value=a.line.wall,a.board.h[d][b+1].fixed=!0);for(d=m;d<k-1;d++)for(b=n;b<l;b++)if(1==f[d][b].value||1==f[d+1][b].value||f[d][b].value!=nil&&f[d+1][b].value!=nil&&f[d][b].value!=f[d+1][b].value)a.board.v[d+1][b].value=a.line.wall,a.board.v[d+1][b].fixed=a.board.v[d+1][b].auto=!0;for(d=m;d<k;d++)for(b=n;b<l-1;b++)if(1==f[d][b].value||1==f[d][b+1].value||f[d][b].value!=nil&&f[d][b+1].value!=nil&&f[d][b].value!=f[d][b+1].value)a.board.h[d][b+1].value=a.line.wall,a.board.h[d][b+
1].fixed=a.board.h[d][b+1].auto=!0;for(d=m;d<k;d++)a.board.h[d][0].valid=!1,a.board.h[d][l].valid=!1;for(b=n;b<l;b++)a.board.v[0][b].valid=!1,a.board.v[k][b].valid=!1;for(d=m;d<k;d++)for(b=n;b<l;b++)if(f[d][b].areas==a.cell.outside||0==f[d][b].label)a.board.h[d][b].valid=!1,a.board.v[d][b].valid=!1,a.board.h[d][b+1].valid=!1,a.board.v[d+1][b].valid=!1}catch(q){throw a.exception(q),q;}};a.check2=function(){try{for(var c=m;c<k;c++)for(var e=n;e<l;e++){var b=f[c][e];0!=b.label&&b.areas!=a.cell.outside&&
0!=b.value&&(b.value==nil?b.error=1:b.checked||(p=0,a.check3values(c,e,b.value),p!=b.value&&a.check3markers(c,e,b.value)))}}catch(d){throw a.exception(d),d;}};var p=0;a.check3values=function(c,e,b){try{f[c][e].checked=!0,p++,0<c&&(f[c-1][e].checked||f[c-1][e].value!=b||a.check3values(c-1,e,b)),0<e&&(f[c][e-1].checked||f[c][e-1].value!=b||a.check3values(c,e-1,b)),c<k-1&&(f[c+1][e].checked||f[c+1][e].value!=b||a.check3values(c+1,e,b)),e<l-1&&(f[c][e+1].checked||f[c][e+1].value!=b||a.check3values(c,
e+1,b))}catch(d){throw a.exception(d),d;}};a.check3markers=function(c,e,b){try{f[c][e].error=3,0<c&&(f[c-1][e].error||f[c-1][e].value!=b||a.check3markers(c-1,e,b)),0<e&&(f[c][e-1].error||f[c][e-1].value!=b||a.check3markers(c,e-1,b)),c<k-1&&(f[c+1][e].error||f[c+1][e].value!=b||a.check3markers(c+1,e,b)),e<l-1&&(f[c][e+1].error||f[c][e+1].value!=b||a.check3markers(c,e+1,b))}catch(d){throw a.exception(d),d;}};a.valueToString=function(c,e){try{return c==nil||c==a.cell.nilalias?"-":0==c?"x":c.toString()}catch(b){return ojdebug(b.toString()),
"%"}};a.onValues=function(){try{a.config.touch?a.enable.lines?(a.enable.lines=!1,a.enable.cells=!0):(a.enable.lines=!0,a.enable.cells=!1):Object.getPrototypeOf(this).onValues.call(this)}catch(c){throw a.exception(c),c;}};a.paintCell=function(c){try{c.areas==a.cell.label?a.paintLabelCell(c):a.paintValueCell(c)}catch(e){throw a.exception(e),e;}};a.paintLabelCell=function(c){try{var e=a.canvas.getContext("2d");e.fillStyle=a.uic.label;e.fillRect(c.px,c.py,a.unit.x,a.unit.y);c.label!=nil&&a.paintText(c.label.toString(),
c)}catch(b){throw a.exception(b),b;}};a.paintValueCell=function(c){try{var e=a.canvas.getContext("2d");e.fillStyle=0==c.label?a.uic.black:a.paintToImage&&a.solved?9<c.value?a.uic.light[0]:a.uic.light[c.value%9+1]:a.paintToImage&&a.moves.current==nil?a.uic.white:c.error?a.uic.light[c.color]:a.uic.done;e.fillRect(c.px,c.py,a.unit.x,a.unit.y);if(0!=c.label){if(!c.error&&0!=c.color){e.save();e.beginPath();e.rect(c.px,c.py,a.unit.x,a.unit.y);e.clip();e.beginPath();e.strokeStyle=a.uic.light[c.color];for(var b=
5;b<2*a.unit.x;b+=5)e.moveTo(c.px+b,c.py),e.lineTo(c.px,c.py+b);e.stroke();e.restore()}a.paintSymbolMarkers(c);if(0<c.label){e.textAlign="left";e.textBaseline="top";e.font=Math.floor(40*a.unit.x/100).toString()+"px sans-serif";e.fillStyle=a.uic.text;var d=1E3<=c.label?String.fromCharCode(c.label-1E3+64):c.label.toString();e.fillText(d,c.px+4,c.py+4)}var f=c.fixed?a.uic.clue:a.uic.text;a.paintToImage&&a.moves.current==nil&&(f=a.uic.text);0==c.value?a.paintCross(c,{color:f}):c.value!=nil&&a.paintText(c.value.toString(),
c,{color:f});0!=c.error&&a.display.errors&&(c.value!=nil?a.paintErrorCircle(c):a.paintErrorDot(c))}}catch(g){throw a.exception(g),g;}};a.paintLine=function(c){try{if(a.paintToImage&&a.moves.current==nil){var e=c.value;c.auto&&(c.value=a.line.grid)}else{e=c.value;var b=c.x,d=c.y;if(!c.fixed)if(c.type==a.item.vline)if(1==f[b-1][d].value||1==f[b][d].value)c.value=a.line.wall;else if(f[b-1][d].value==f[b][d].value)0<f[b][d].value&&(c.value=a.line.none);else if(0<f[b-1][d].value&&0<f[b][d].value)c.value=
a.line.wall;else{if(0<f[b-1][d].value&&!f[b-1][d].error||0<f[b][d].value&&!f[b][d].error)c.value=a.line.wall}else if(c.type==a.item.hline)if(1==f[b][d-1].value||1==f[b][d].value)c.value=a.line.wall;else if(f[b][d-1].value==f[b][d].value)0<f[b][d].value&&(c.value=a.line.none);else if(0<f[b][d-1].value&&0<f[b][d].value)c.value=a.line.wall;else if(0<f[b][d-1].value&&!f[b][d-1].error||0<f[b][d].value&&!f[b][d].error)c.value=a.line.wall}Object.getPrototypeOf(this).paintLine.call(this,c);c.value=e}catch(h){throw a.exception(h),
h;}};a.paintCurrentValue=function(){try{var c=a.uie.value,e=c.getContext("2d");e.fillStyle=a.uic.white;e.fillRect(0,0,c.width,c.height);e.fillStyle=a.uic.none;e.strokeStyle=a.uic.black;var b={x:0,y:0,w:c.width,h:c.height,scale:90};a.enable.lines&&!a.enable.cells?a.paintText("#",e,b):a.current.type!=a.item.cell?a.paintText("1",e,b):a.current.value!=nil&&a.paintText(a.current.value.toString(),e,b)}catch(d){throw a.exception(d),d;}}}Fillomino.prototype=new Puzzle;
