function Gokigen(){var c=this;c.constructor();c.uis.puzzle=["Gokigen Nananme"];var d=c.board.c,n=1,p=1,g=0,h=0;c.charToValue=c.charToValue.concat(["/",1,"\\",2,",",1,".",2,"-",nil,"0",nil]);c.cell.values=[1,2,nil];c.enable.nodes=!1;c.enable.pnodes=!0;c.enable.pgrid=!0;c.keypad.left=nil;c.uic.circlefill="#ffffff";c.uic.circleedge="#000000";c.uic.slashfill="#666666";c.uic.slashedge="#000000";c.uim.padding=25;c.init=function(){Object.getPrototypeOf(c).init.call(c)};c.reset2=function(){try{n=c.labels.west;
p=c.labels.north;g=c.size.x-c.labels.east;h=c.size.y-c.labels.south;if(c.level.problem){var b=0;var a=c.level.problem.replace(/\s+/g," ").trim().split(" ");for(var f=p;f<=h;f++)for(var e=n;e<=g;e++){var k=c.board.n[e][f];var l=a[b++];k.label="."==l||"-"==l?nil:parseInt(l)}}if(c.level.solution)for(b=0,a=c.level.solution.replace(/\s+/g," ").trim().split(" "),f=p;f<h;f++)for(e=n;e<g;e++){var m=d[e][f];l=a[b++];if("."==l||"-"==l)m.solution=nil;else if("2"==l||"/"==l)m.solution=1;else if("1"==l||"\\"==
l)m.solution=2}}catch(t){throw c.exception(t),t;}};var m=[],q=[],k;c.check2=function(){try{for(var b=n;b<g;b++)for(var a=p;a<h;a++)d[b][a].value==nil&&(d[b][a].error=1);for(b=n;b<=g;b++)for(a=p;a<=h;a++)if(0<=c.board.n[b][a].label){var f=0;f=0;0<b&&0<a&&2==d[b-1][a-1].value&&f++;0<b&&a<h&&1==d[b-1][a].value&&f++;0<a&&b<g&&1==d[b][a-1].value&&f++;b<g&&a<h&&2==d[b][a].value&&f++;f!=c.board.n[b][a].label&&(c.board.n[b][a].error=3)}f=0;for(b=n;b<g;b++)for(a=p;a<h;a++)0==d[b][a].count&&d[b][a].value!=
nil&&(f++,1==d[b][a].value?(k=0,c.checkLoop(b,a,1,f),k=0,c.checkLoop(b,a,4,f)):2==d[b][a].value&&(k=0,c.checkLoop(b,a,2,f),k=0,c.checkLoop(b,a,3,f)))}catch(e){throw c.exception(e),e;}};c.checkLoop=function(b,a,f,e){try{if(!(0<k&&d[m[k-1]][q[k-1]].error))if(m[k]=b,q[k]=a,k++,1!=k&&0!=d[b][a].count)for(c.solved=!1,b=k-1;0<=b&&!d[m[b]][q[b]].error;b--)d[m[b]][q[b]].error=2;else{d[b][a].count=e;switch(f){case 2:0<b&&0<a&&2==d[b-1][a-1].value&&c.checkLoop(b-1,a-1,2,e);0<b&&1==d[b-1][a].value&&c.checkLoop(b-
1,a,4,e);0<a&&1==d[b][a-1].value&&c.checkLoop(b,a-1,1,e);break;case 3:b<g-1&&a<h-1&&2==d[b+1][a+1].value&&c.checkLoop(b+1,a+1,3,e);b<g-1&&1==d[b+1][a].value&&c.checkLoop(b+1,a,1,e);a<h-1&&1==d[b][a+1].value&&c.checkLoop(b,a+1,4,e);break;case 1:b<g-1&&0<a&&1==d[b+1][a-1].value&&c.checkLoop(b+1,a-1,1,e);b<g-1&&2==d[b+1][a].value&&c.checkLoop(b+1,a,3,e);0<a&&2==d[b][a-1].value&&c.checkLoop(b,a-1,2,e);break;case 4:0<b&&a<h-1&&1==d[b-1][a+1].value&&c.checkLoop(b-1,a+1,4,e),0<b&&2==d[b-1][a].value&&c.checkLoop(b-
1,a,2,e),a<h-1&&2==d[b][a+1].value&&c.checkLoop(b,a+1,3,e)}k--}}catch(r){throw c.exception(r),r;}};c.solve2=function(){try{for(var b=n;b<=g;b++)for(var a=p;a<=h;a++)0==c.board.n[b][a].label&&(b!=g&&a!=h&&(d[b][a].value=1),b!=g&&0!=a&&(d[b][a-1].value=2),a!=h&&0!=b&&(d[b-1][a].value=2),0!=b&&0!=a&&(d[b-1][a-1].value=1)),4==c.board.n[b][a].label&&(b!=g&&a!=h&&(d[b][a].value=2),b!=g&&0!=a&&(d[b][a-1].value=1),a!=h&&0!=b&&(d[b-1][a].value=1),0!=b&&0!=a&&(d[b-1][a-1].value=2)),1==c.board.n[b][a].label&&
(0==b&&0==a?d[b][a].value=2:0==b&&a==h?d[b][a-1].value=1:b==g&&0==a?d[b-1][a].value=1:b==g&&a==h&&(d[b-1][a-1].value=2)),2==c.board.n[b][a].label&&(0==b&&(d[b][a-1].value=1,d[b][a].value=2),0==a&&(d[b-1][a].value=1,d[b][a].value=2),b==g&&(d[b-1][a-1].value=2,d[b-1][a].value=1),a==g&&(d[b-1][a-1].value=2,d[b][a-1].value=1))}catch(f){throw c.exception(f),f;}};c.valueToString=function(b,a){return 1==b?"/":2==b?"\\":"-"};c.paintCell=function(b){try{var a=c.canvas.getContext("2d");a.fillStyle=c.uic.light[0];
a.fillRect(b.px,b.py,c.unit.x,c.unit.y);c.paintSymbolMarkers(b);b.value!=nil&&(a={},a.stroke=c.uic.slashedge,a.fill=c.display.errors&&b.error?c.uic.error:c.display.errors?c.uic.slashfill:c.uic.dark[b.color],1==b.value?c.paintFSlash(b,a):c.paintBSlash(b,a));b.error&&c.display.errors&&b.value==nil&&c.paintErrorDot(b)}catch(f){throw c.exception(f),f;}};c.paintNode=function(b){try{if(b.label!=nil){var a=c.canvas.getContext("2d"),d=c.unit.x/3;a.fillStyle=c.uic.circlefill;c.display.errors&&b.error?(a.strokeStyle=
c.uic.error,a.lineWidth=2):(a.strokeStyle=c.uic.circleedge,a.lineWidth=1);a.beginPath();a.arc(b.px,b.py,d,0,2*Math.PI);a.fill();a.stroke();a.textAlign="center";a.textBaseline="middle";a.font=Math.floor(c.unit.x/2).toString()+"px sans-serif";a.fillStyle=c.uic.text;a.fillText(b.label.toString(),b.px,b.py)}}catch(e){throw c.exception(e),e;}};c.paintFSlash=function(b,a){try{if(a=c.defaultParams(b,a)){b.px&&(b=c.canvas.getContext("2d"));b.strokeStyle=a.stroke?a.stroke:c.uic.slashedge;b.fillStyle=a.fill?
a.fill:c.uic.slashfill;b.lineWidth=a.width?a.width:1;var d=Math.min(Math.floor(c.unit.x/12),2);b.beginPath();b.moveTo(a.x+a.w-d,a.y);b.lineTo(a.x+a.w,a.y);b.lineTo(a.x+a.w,a.y+d);b.lineTo(a.x+d,a.y+a.h);b.lineTo(a.x,a.y+a.h);b.lineTo(a.x,a.y+a.h-d);b.lineTo(a.x+a.w-d,a.y);b.stroke();b.fill()}}catch(e){throw c.exception(e),e;}};c.paintBSlash=function(b,a){try{if(a=c.defaultParams(b,a)){b.px&&(b=c.canvas.getContext("2d"));b.strokeStyle=a.stroke?a.stroke:c.uic.slashedge;b.fillStyle=a.fill?a.fill:c.uic.slashfill;
b.lineWidth=a.width?a.width:1;var d=Math.min(Math.floor(c.unit.x/12),2);b.beginPath();b.moveTo(a.x,a.y);b.lineTo(a.x+d,a.y);b.lineTo(a.x+a.w,a.y+a.h-d);b.lineTo(a.x+a.w,a.y+a.h);b.lineTo(a.x+a.w-d,a.y+a.h);b.lineTo(a.x,a.y+d);b.lineTo(a.x,a.y);b.stroke();b.fill()}}catch(e){throw c.exception(e),e;}};c.paintCurrentValue=function(){try{var b=c.uie.value,a=b.getContext("2d");a.fillStyle=c.uic.white;a.fillRect(0,0,b.width,b.height);a.strokeStyle=c.uic.slashedge;a.fillStyle=c.uic.slashfill;var d={x:0,y:0,
w:b.width,h:b.height};1==c.current.value?c.paintFSlash(a,d):2==c.current.value&&c.paintBSlash(a,d)}catch(e){throw c.exception(e),e;}}}Gokigen.prototype=new Puzzle;
