function Hashi(){var c=this;c.constructor();c.uis.puzzle=["Hashiwokakero"];var e=c.board.c,n=0,q=0,l=0,m=0;c.enable.dragging=!0;c.enable.plines=!1;c.enable.values=!1;c.enable.smarkers=!1;c.keypad.left=nil;c.keypad.right=nil;c.uim.line=2;c.uic.line="#000000";c.uic.canvas=c.uic.light[0];labelValues=[1,2,3,4,5,6,7,8,nil];lineValues=[1,2,11,12,nil];var t=["1",1,"2",2,"3",3,"4",4,"5",5,"6",6,"7",7,"8",8,"0",nil,"-",nil,"/",nil],u=["1",1,"2",2,"a",11,"b",12,"0",nil,"-",nil,"/",nil],v=[["1",1],["2",2],["3",
3],["4",4],["5",5],["6",6],["7",7],["8",8],["\u2022",nil]];c.init=function(){Object.getPrototypeOf(c).init.call(c)};c.reset2=function(){try{n=c.labels.west;q=c.labels.north;l=c.size.x-c.labels.east;m=c.size.y-c.labels.south;if(c.level.problem){var a=0;var b=c.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=q;d<m;d++)for(var f=n;f<l;f++){var k=e[f][d];var g=b[a++];"."==g||"-"==g?k.label=nil:"a"<=g&&"z">=g?k.clues=g.charCodeAt(0)-96+1:"A"<=g&&"Z">=g?k.clues=g.charCodeAt(0)-64+1:"0"<=g&&
"9">=g&&(k.label=parseInt(g));k.label!=nil&&(k.fixed=!0)}}if(c.level.solution)for(a=0,b=c.level.solution.replace(/\s+/g," ").trim().split(" "),d=q;d<m;d++)for(f=n;f<l;f++)k=e[f][d],g=b[a++],"-"==g||"."==g?k.solution=nil:"a"<=g&&"z">=g?k.solution=g.charCodeAt(0)-96+10:"0"<=g&&"9">=g&&(k.solution=parseInt(g))}catch(h){throw c.exception(h),h;}};c.check2=function(){try{for(var a=[],b=0;9>b;b++)a[b]=nil;for(b=n;b<l;b++)for(var d=q;d<m;d++){var f=e[b][d];if(0!=f.clues)if(f.label==nil)f.error=3;else if(a[f.label]==
nil||a[f.label]==f.clues)a[f.label]=f.clues;else for(var k=0;k<l;k++)for(var g=0;g<m;g++){var h=e[k][g];h.label==f.label&&(h.error=2)}}for(b=n;b<l;b++)for(d=q;d<m;d++)e[b][d].label!=nil&&(a=0,0<b&&0<=e[b-1][d].value&&9>=e[b-1][d].value&&(a+=e[b-1][d].value),b<l-1&&0<=e[b+1][d].value&&9>=e[b+1][d].value&&(a+=e[b+1][d].value),0<d&&10<=e[b][d-1].value&&19>=e[b][d-1].value&&(a=a+e[b][d-1].value-10),d<m-1&&10<=e[b][d+1].value&&19>=e[b][d+1].value&&(a=a+e[b][d+1].value-10),a!=e[b][d].label&&(e[b][d].error=
3));a=1;for(b=n;b<l;b++)for(d=q;d<m;d++)e[b][d].value!=nil&&0==e[b][d].count&&c.check3(b,d,a++);2!=a&&(c.solved=!1)}catch(r){throw c.exception(r),r;}};c.check3=function(a,b,d){try{e[a][b].count=d,0<a&&0==e[a-1][b].count&&(e[a][b].label!=nil||1<=e[a][b].value&&9>=e[a][b].value)&&(e[a-1][b].label!=nil||1<=e[a-1][b].value&&9>=e[a-1][b].value)&&c.check3(a-1,b,d),0<b&&0==e[a][b-1].count&&(e[a][b].label!=nil||10<=e[a][b].value&&19>=e[a][b].value)&&(e[a][b-1].label!=nil||10<=e[a][b-1].value&&19>=e[a][b-
1].value)&&c.check3(a,b-1,d),a<l-1&&0==e[a+1][b].count&&(e[a][b].label!=nil||1<=e[a][b].value&&9>=e[a][b].value)&&(e[a+1][b].label!=nil||1<=e[a+1][b].value&&9>=e[a+1][b].value)&&c.check3(a+1,b,d),b<m-1&&0==e[a][b+1].count&&(e[a][b].label!=nil||10<=e[a][b].value&&19>=e[a][b].value)&&(e[a][b+1].label!=nil||10<=e[a][b+1].value&&19>=e[a][b+1].value)&&c.check3(a,b+1,d)}catch(f){return ojdebug(f.toString()),"%"}};c.showSolution2=function(){try{for(var a=n;a<l;a++)for(var b=q;b<m;b++){var d=e[a][b];d.color=
0;d.value=d.solution;0!=d.clues&&(d.label=d.solution)}}catch(f){throw c.exception(f),f;}};c.moveTo=function(a,b){try{a&&a.valid&&(a.fixed?(c.cell.values=null,c.keypadValues=null,c.charToValue=null):0!=a.clues?(c.cell.values=labelValues,c.keypadValues=v,c.charToValue=t):(c.cell.values=lineValues,c.keypadValues=null,c.charToValue=u),Object.getPrototypeOf(this).moveTo.call(this,a,b))}catch(d){throw c.exception(d),d;}};c.dragTo2=function(a,b){try{c.moveTo(a,b),a.label!=nil||0!=a.clues?c.current.item=
a:b.y==a.y?1==a.value?c.makeMove(a,2,c.current.color):2==a.value?c.makeMove(a,nil,c.current.color):c.makeMove(a,1,c.current.color):11==a.value?c.makeMove(a,12,c.current.color):12==a.value?c.makeMove(a,nil,c.current.color):c.makeMove(a,11,c.current.color)}catch(d){return ojdebug(d.toString()),"%"}};c.makeMove2=function(a,b,c){try{if(0!=a.clues){a.value=a.label;Object.getPrototypeOf(this).makeMove2.call(this,a,b,c);a.label=a.value;for(var f=n;f<l;f++)for(var d=q;d<m;d++)e[f][d].clues==a.clues&&(e[f][d].value=
e[f][d].label=a.label)}else{a.label!=nil||null!=b&&void 0!==b||(b=1==a.value?2:2==a.value?nil:1);var g=a.value;Object.getPrototypeOf(this).makeMove2.call(this,a,b,c);b=a.value;c=a.color;a.value=g;if(b==nil&&1<=a.value&&9>=a.value||1<=b&&9>=b){g=nil;for(f=a.x;0<=f&&g==nil;f--)if(e[f][a.y].label!=nil||0!=e[f][a.y].clues)g=f;var h=nil;for(f=a.x;f<l&&h==nil;f++)if(e[f][a.y].label!=nil||0!=e[f][a.y].clues)h=f;if(g==nil||h==nil)return;for(f=g+1;f<h;f++){if(10<=e[f][a.y].value&&19>=e[f][a.y].value){for(d=
a.y;e[f][d].label==nil&&0==e[f][d].clues;d--)e[f][d].value=nil,e[f][d].color=0;for(d=a.y;e[f][d].label==nil&&0==e[f][d].clues;d++)e[f][d].value=nil,e[f][d].color=0}e[f][a.y].value=b;e[f][a.y].color=c}}if(b==nil&&10<=a.value&&19>=a.value||10<=b&&19>=b){g=nil;for(d=a.y;0<=d&&g==nil;d--)if(e[a.x][d].label!=nil||0!=e[a.x][d].clues)g=d;h=nil;for(d=a.y;d<m&&h==nil;d++)if(e[a.x][d].label!=nil||0!=e[a.x][d].clues)h=d;if(g!=nil&&h!=nil)for(d=g+1;d<h;d++){if(1<=e[a.x][d].value&&9>=e[a.x][d].value){for(f=a.x;e[f][d].label==
nil&&0==e[f][d].clues;f--)e[f][d].value=nil,e[f][d].color=0;for(f=a.x;e[f][d].label==nil&&0==e[f][d].clues;f++)e[f][d].value=nil,e[f][d].color=0}e[a.x][d].value=b;e[a.x][d].color=c}}}}catch(r){return ojdebug(r.toString()),"%"}};c.makeMove2Alt=function(a,b,d){try{a.label!=nil||null!=b&&void 0!==b||(b=11==a.value?12:12==a.value?nil:11),c.makeMove2(a,b,d)}catch(f){throw c.exception(f),f;}};c.valueToString=function(a,b){try{return a==nil?"-":0<=a&&9>=a?a.toString():10<=a&&19>=a?String.fromCharCode(a+
86):" "}catch(d){return ojdebug(d.toString()),"%"}};c.paintCell=function(a){try{var b=c.canvas.getContext("2d");b.fillStyle=c.uic.light[0];b.fillRect(a.px,a.py,c.unit.x,c.unit.y);if(a.areas!=c.cell.black){if(a.label!=nil||0!=a.clues)p={scale:90},p.fill=c.uic.none,p.stroke=a.error&&c.display.errors?c.uic.error:a.error?c.uic.text:c.uic.solved,c.paintCircle(a,p);if(a.label!=nil)c.paintText(a.label.toString(),a);else if(0!=a.clues)c.paintText(String.fromCharCode(a.clues+64),a);else{var d=0==c.unit.x%
2?.5:0;b.lineWidth=c.uim.grid;b.strokeStyle=c.uic.grid;b.lineCap="round";var e=c.unit.x/2+d,k=c.unit.y/2+d;var g=a.px+c.unit.x/2+d;var h=a.py+c.unit.y/2+d;b.beginPath();if(0>a.value||9<a.value)0==a.x?(b.moveTo(a.px+e,h),b.lineTo(a.px+c.unit.x,h)):a.x==l-1?(b.moveTo(a.px,h),b.lineTo(a.px+c.unit.x-e,h)):(b.moveTo(a.px,h),b.lineTo(a.px+c.unit.x,h));if(10>a.value||19<a.value)0==a.y?(b.moveTo(g,a.py+k),b.lineTo(g,a.py+c.unit.y)):a.y==m-1?(b.moveTo(g,a.py),b.lineTo(g,a.py+c.unit.y-k)):(b.moveTo(g,a.py),
b.lineTo(g,a.py+c.unit.y));b.stroke();0<=a.value&&9>=a.value&&(b.lineWidth=c.uim.line,b.strokeStyle=c.display.errors&&1!=a.count?c.uic.dark[a.count%10]:c.uic.dark[a.color],b.lineCap="round",b.beginPath(),h=Math.floor(a.py+c.unit.y/2),1==a.value?(b.moveTo(a.px,h),b.lineTo(a.px+c.unit.x,h)):(b.moveTo(a.px,h-2),b.lineTo(a.px+c.unit.x,h-2),b.moveTo(a.px,h+2),b.lineTo(a.px+c.unit.x,h+2)),b.stroke());10<=a.value&&19>=a.value&&(b.lineWidth=c.uim.line,b.strokeStyle=c.display.errors&&1!=a.count?c.uic.dark[a.count%
10]:c.uic.dark[a.color],b.lineCap="round",b.beginPath(),g=Math.floor(a.px+c.unit.x/2),11==a.value?(b.moveTo(g,a.py),b.lineTo(g,a.py+c.unit.y)):(b.moveTo(g-2,a.py),b.lineTo(g-2,a.py+c.unit.y),b.moveTo(g+2,a.py),b.lineTo(g+2,a.py+c.unit.y)),b.stroke())}c.paintSymbolMarkers(a)}}catch(r){throw c.exception(r),r;}}}Hashi.prototype=new Puzzle;
