function Ketten(){var b=this;b.constructor();b.uis.puzzle=["Link-A-Pic","Ketten"];var l=b.board.c,m=0,n=0,p=0,q=0,a={any:0,none:16,n:1,e:2,s:4,w:8,ne:3,se:6,nw:9,sw:12,ns:5,ew:10,nsew:15},f=nil,h=nil,r={none:0,path:1,length:2,match:3};b.charToValue=b.charToValue.concat([".",a.any,",",a.none,"-",nil]);b.enable.dragging=!0;b.enable.pgrid=!0;b.keypad.left=nil;b.uic.line1="#aaaaaa";b.uic.line2="#777777";b.uic.edge="#883388";b.init=function(){Object.getPrototypeOf(b).init.call(b)};b.reset2=function(){try{m=
b.labels.west;n=b.labels.north;p=b.size.x-b.labels.east;q=b.size.y-b.labels.south;if(b.level.problem){var c=0;var d=b.level.problem.replace(/\s+/g," ").trim().split(" ");for(var e=n;e<q;e++)for(var t=m;t<p;t++){var g=l[t][e];var k=d[c++];"."!=k&&"-"!=k&&(g.label=parseInt(k));1==g.label&&(g.value=a,g.fixed=!0)}}if(b.level.solution)for(c=0,d=b.level.solution.replace(/\s+/g," ").trim().split(" "),e=n;e<q;e++)for(t=m;t<p;t++)if(g=l[t][e],k=d[c++],"-"!=k&&"."!=k){var f=0;k.contains("n")&&(f|=a.n);k.contains("s")&&
(f|=a.s);if(k.contains("e")||k.contains("o"))f|=a.e;k.contains("w")&&(f|=a.w);0!=f&&(g.solution=f)}}catch(y){throw b.exception(y),y;}};var g,w,x,v;b.check2=function(){try{w=0;for(var a=m;a<p;a++)for(var d=n;d<q;d++){var e=l[a][d];if(1==e.label)e.checked=!0;else if(1<e.label&&!e.checked)if(g=!1,w++,x=0,b.checkPath(e,null),g){e.error=r.path;for(var f=m;f<p;f++)for(var h=n;h<q;h++){var k=l[f][h];k.count==w&&(k.error=r.path)}}else v.label!=e.label?e.error=v.error=r.match:v.label!=x&&(e.error=r.length,
v.error=r.match)}for(a=m;a<p;a++)for(d=n;d<q;d++)e=l[a][d],e.value==nil||e.checked||(e.error=r.path)}catch(u){throw b.exception(u),u;}};b.checkPath=function(c,d){try{c.value==nil?g=!0:(v=c,c.checked?g=!0:(c.checked=!0,c.count=w,x++,c.label!=nil&&c.value!=a.n&&c.value!=a.s&&c.value!=a.e&&c.value!=a.w?g=!0:c.value!=a.n&&c.value!=a.s&&c.value!=a.e&&c.value!=a.w||c.label!=nil?(d&&(c.x-1==d.x&&0==(c.value&a.w)&&(g=!0),c.x+1==d.x&&0==(c.value&a.e)&&(g=!0),c.y-1==d.y&&0==(c.value&a.n)&&(g=!0),c.y+1==d.y&&
0==(c.value&a.s)&&(g=!0)),g||(0!=(c.value&a.w)&&(c.x==m?g=!0:(null==d||d.x!=c.x-1)&&b.checkPath(l[c.x-1][c.y],c)),0!=(c.value&a.e)&&(c.x==p-1?g=!0:(null==d||d.x!=c.x+1)&&b.checkPath(l[c.x+1][c.y],c)),0!=(c.value&a.n)&&(c.y==n?g=!0:(null==d||d.y!=c.y-1)&&b.checkPath(l[c.x][c.y-1],c)),0!=(c.value&a.s)&&(c.y==q-1?g=!0:(null==d||d.y!=c.y+1)&&b.checkPath(l[c.x][c.y+1],c)))):g=!0))}catch(e){throw b.exception(e),e;}};b.dragTo2=function(c,d){try{if(!c.fixed&&c.areas!=b.cell.outside){if(c.x==d.x-1&&d.y==c.y){switch(d.value){case nil:case a.none:case a.any:b.makeMove(d,
a.w);break;case a.ew:b.makeMove(d,a.ew);break;case a.sw:b.makeMove(d,a.sw);break;case a.nw:b.makeMove(d,a.nw);break;case a.n:b.makeMove(d,a.nw);break;case a.e:b.makeMove(d,a.ew);break;case a.s:b.makeMove(d,a.sw);break;case a.w:b.makeMove(d,a.w);break;case a.ns:h==d.y-1?b.makeMove(d,a.nw):h==d.y+1?b.makeMove(d,a.sw):b.makeMove(d,a.w);break;case a.ne:h==d.y-1?b.makeMove(d,a.nw):f==d.x+1?b.makeMove(d,a.ew):b.makeMove(d,a.w);break;case a.se:h==d.y+1?b.makeMove(d,a.sw):f==d.x+1?b.makeMove(d,a.ew):b.makeMove(d,
a.w)}d.label!=nil&&b.makeMove(d,a.w);switch(c.value){case nil:case a.none:case a.any:b.makeMove(c,a.e);break;case a.ns:b.makeMove(c,a.e);break;case a.ew:b.makeMove(c,a.ew);break;case a.ne:b.makeMove(c,a.ne);break;case a.se:b.makeMove(c,a.se);break;case a.sw:b.makeMove(c,a.e);break;case a.nw:b.makeMove(c,a.e);break;case a.n:b.makeMove(c,a.ne);break;case a.e:b.makeMove(c,a.e);break;case a.s:b.makeMove(c,a.se);break;case a.w:b.makeMove(c,a.ew)}c.label!=nil&&b.makeMove(c,a.e)}if(c.x==d.x+1&&d.y==c.y){switch(d.value){case nil:case a.none:case a.any:b.makeMove(d,
a.e);break;case a.ew:b.makeMove(d,a.ew);break;case a.ne:b.makeMove(d,a.ne);break;case a.se:b.makeMove(d,a.se);break;case a.n:b.makeMove(d,a.ne);break;case a.e:b.makeMove(d,a.e);break;case a.s:b.makeMove(d,a.se);break;case a.w:b.makeMove(d,a.ew);break;case a.ns:h==d.y-1?b.makeMove(d,a.ne):h==d.y+1?b.makeMove(d,a.se):b.makeMove(d,a.e);break;case a.sw:f==d.x-1?b.makeMove(d,a.ew):h==d.y+1?b.makeMove(d,a.se):b.makeMove(d,a.e);break;case a.nw:h==d.y-1?b.makeMove(d,a.ne):f==d.x-1?b.makeMove(d,a.ew):b.makeMove(d,
a.e)}d.label!=nil&&b.makeMove(d,a.e);switch(c.value){case nil:case a.none:case a.any:b.makeMove(c,a.w);break;case a.ns:b.makeMove(c,a.w);break;case a.ew:b.makeMove(c,a.ew);break;case a.ne:b.makeMove(c,a.w);break;case a.se:b.makeMove(c,a.w);break;case a.sw:b.makeMove(c,a.sw);break;case a.nw:b.makeMove(c,a.nw);break;case a.n:b.makeMove(c,a.nw);break;case a.e:b.makeMove(c,a.ew);break;case a.s:b.makeMove(c,a.sw);break;case a.w:b.makeMove(c,a.w)}c.label!=nil&&b.makeMove(c,a.w)}if(c.y==d.y+1&&d.x==c.x){switch(d.value){case nil:case a.none:case a.any:b.makeMove(d,
a.s);break;case a.se:b.makeMove(d,a.se);break;case a.sw:b.makeMove(d,a.sw);break;case a.n:b.makeMove(d,a.ns);break;case a.e:b.makeMove(d,a.se);break;case a.s:b.makeMove(d,a.s);break;case a.w:b.makeMove(d,a.sw);break;case a.ns:b.makeMove(d,a.ns);break;case a.ew:f==d.x-1?b.makeMove(d,a.sw):f==d.x+1?b.makeMove(d,a.se):b.makeMove(d,a.s);break;case a.ne:h==d.y-1?b.makeMove(d,a.ns):f==d.x+1?b.makeMove(d,a.se):b.makeMove(d,a.s);break;case a.nw:f==d.x-1?b.makeMove(d,a.sw):h==d.y-1?b.makeMove(d,a.ns):b.makeMove(d,
a.s)}d.label!=nil&&b.makeMove(d,a.s);switch(c.value){case nil:case a.none:case a.any:b.makeMove(c,a.n);break;case a.ns:b.makeMove(c,a.ns);break;case a.ew:b.makeMove(c,a.n);break;case a.ne:b.makeMove(c,a.ne);break;case a.se:b.makeMove(c,a.n);break;case a.sw:b.makeMove(c,a.n);break;case a.nw:b.makeMove(c,a.nw);break;case a.n:b.makeMove(c,a.n);break;case a.e:b.makeMove(c,a.ne);break;case a.s:b.makeMove(c,a.ns);break;case a.w:b.makeMove(c,a.nw)}c.label!=nil&&b.makeMove(c,a.n)}if(c.y==d.y-1&&d.x==c.x){switch(d.value){case nil:case a.none:case a.any:b.makeMove(d,
a.n);break;case a.ns:b.makeMove(d,a.ns);break;case a.ne:b.makeMove(d,a.ne);break;case a.nw:b.makeMove(d,a.nw);break;case a.n:b.makeMove(d,a.n);break;case a.e:b.makeMove(d,a.ne);break;case a.s:b.makeMove(d,a.ns);break;case a.w:b.makeMove(d,a.nw);break;case a.ew:f==d.x-1?b.makeMove(d,a.nw):f==d.x+1?b.makeMove(d,a.ne):b.makeMove(d,a.n);break;case a.se:h==d.y+1?b.makeMove(d,a.ns):f==d.x+1?b.makeMove(d,a.se):b.makeMove(d,a.s);break;case a.sw:f==d.x-1?b.makeMove(d,a.ne):h==d.y+1?b.makeMove(d,a.ns):b.makeMove(d,
a.s)}d.label!=nil&&b.makeMove(d,a.n);switch(c.value){case nil:case a.none:case a.any:b.makeMove(c,a.s);break;case a.ns:b.makeMove(c,a.ns);break;case a.ew:b.makeMove(c,a.s);break;case a.ne:b.makeMove(c,a.s);break;case a.se:b.makeMove(c,a.se);break;case a.sw:b.makeMove(c,a.sw);break;case a.nw:b.makeMove(c,a.s);break;case a.n:b.makeMove(c,a.ns);break;case a.e:b.makeMove(c,a.se);break;case a.s:b.makeMove(c,a.s);break;case a.w:b.makeMove(c,a.sw)}c.label!=nil&&b.makeMove(c,a.s)}f=d.x;h=d.y;b.moveTo(c)}}catch(e){throw b.exception(e),
e;}};b.dragTo2Alt=function(a,d){try{d.value!=nil&&b.makeMove(d,nil,b.current.color),a.value!=nil&&b.makeMove(a,nil,b.current.color),b.moveTo(a)}catch(e){throw b.exception(e),e;}};b.valueToString=function(b,d){try{switch(b){case a.none:return d?"x":"-";case a.nsew:return"nsew";case a.any:return"o";case a.s:return"s";case a.n:return"n";case a.e:return"e";case a.w:return"w";case a.ne:return"ne";case a.nw:return"nw";case a.se:return"se";case a.sw:return"sw";case a.ns:return"ns";case a.ew:return"ew";default:return"-"}}catch(e){return ojdebug(e.toString()),
"%"}};b.paintCell=function(c){try{var d=b.canvas.getContext("2d");d.fillStyle=c.value==nil?b.uic.light[0]:c.error?b.uic.light[0]:b.uic.dark[0];d.fillRect(c.px,c.py,b.unit.x,b.unit.y);if(c.value!=nil){var e=Math.floor((b.unit.x-Math.floor(b.unit.x/4))/2),f=b.unit.x-2*e,g=f+e;d.fillStyle=c.error?0==c.color?b.uic.line1:b.uic.light[c.color]:0==c.color?b.uic.line2:b.uic.dark[c.color];c.value!=a.none||b.solved||b.paintCross(c);c.value==a.any&&d.fillRect(c.px+e,c.py+e,f,f);0!=(c.value&a.n)&&d.fillRect(c.px+
e,c.py,f,g);0!=(c.value&a.s)&&d.fillRect(c.px+e,c.py+e,f,g);0!=(c.value&a.e)&&d.fillRect(c.px+e,c.py+e,g,f);0!=(c.value&a.w)&&d.fillRect(c.px,c.py+e,g,f)}if(c.label!=nil){var h=b.uic.test;c.value==nil||c.error||(h=b.uic.text2);b.paintText(c.label.toString(),c,{color:h})}b.paintSymbolMarkers(c);c.error&&b.display.errors&&(c.error==r.block?b.paintErrorSquare(c):c.label!=nil?b.paintErrorCircle(c):b.paintErrorDot(c))}catch(u){throw b.exception(u),u;}}}Ketten.prototype=new Puzzle;
