function Linesweeper(){this.constructor();this.uis.puzzle=["Linesweeper"];var k=this.board.c,p=0,q=0,m=0,n=0,g=nil,l=nil,r=[0,1,1,1,0,-1,-1,-1],s=[-1,-1,0,1,1,1,0,-1];this.charToValue=this.charToValue.concat(["-",nil,"/",nil,".",0,"o",0,",",16,"x",16]);this.enable.dragging=!0;this.enable.pgrid=!0;this.keypad.left=nil;this.cell.nilalias=16;this.reset2=function(){try{p=this.labels.west;q=this.labels.north;m=this.size.x-this.labels.east;n=this.size.y-this.labels.south;if(this.level.problem)for(var b=
0,a=this.level.problem.replace(/\s+/g," ").trim().split(" "),d=q;d<n;d++)for(var c=p;c<m;c++){var f=k[c][d],e=a[b++];"."==e||"-"==e||("@"==e?(f.areas=this.cell.outside,f.value=16,f.fixed=!0,f.valid=!1):"x"==e?f.value=16:e.startsWith("~")?(f.clues=1,f.label=parseInt(e.substring(1))):f.label=parseInt(e));if(f.value!=nil||f.label!=nil)f.fixed=!0}if(this.level.solution){b=0;a=this.level.solution.replace(/\s+/g," ").trim().split(" ");for(d=q;d<n;d++)for(c=p;c<m;c++)if(f=k[c][d],e=a[b++],"-"==e||"."==e)f.solution=
nil;else{var h=0;e.contains("n")&&(h|=1);e.contains("s")&&(h|=4);e.contains("e")&&(h|=2);e.contains("w")&&(h|=8);0!=h&&(f.solution=h)}}}catch(g){throw this.exception(g),g;}};this.check2=function(){try{for(var b=0,a=p;a<m;a++)for(var d=q;d<n;d++){var c=k[a][d];!c.checked&&(16!=c.value&&0!=c.value&&c.value!=nil)&&this.markPath(a,d,b++)}if(1!=b){this.solved=!1;for(a=p;a<m;a++)for(d=q;d<n;d++)1==k[a][d].error&&(k[a][d].error=0)}for(a=p;a<m;a++)for(d=q;d<n;d++){c=k[a][d];c.label!=nil&&c.value!=nil&&(c.error=
3);if(0==c.value||1==c.value||4==c.value||2==c.value||8==c.value)c.error=3;16<c.value&&!c.checked&&(c.error=3)}for(a=p;a<m;a++)for(d=q;d<n;d++)if(c=k[a][d],c.label!=nil){for(var f=b=0;8>f;f++){var e=a+r[f],h=d+s[f];0<=e&&(e<m&&0<=h&&h<n&&k[e][h].value!=nil&&0!=(k[e][h].value&15))&&b++}1==c.clues?b==c.label&&(c.error=2):b!=c.label&&(c.error=2)}}catch(g){throw this.exception(g),g;}};this.markPath=function(b,a,d){try{var c=k[b][a];if(c.value!=nil){c.checked=!0;c.count=d;var f=0==d?1:d;if(2==c.value||
8==c.value||1==c.value||4==c.value)c.error=f;if(0!=(c.value&8))if(0==b)c.error=f;else{var e=k[b-1][a];e.value==nil||0==(e.value&2)?c.error=f:e.checked||this.markPath(b-1,a,d)}0!=(c.value&2)&&(b==m-1?c.error=f:(e=k[b+1][a],e.value==nil||0==(e.value&8)?c.error=f:e.checked||this.markPath(b+1,a,d)));0!=(c.value&1)&&(0==a?c.error=1:(e=k[b][a-1],e.value==nil||0==(e.value&4)?c.error=f:e.checked||this.markPath(b,a-1,d)));0!=(c.value&4)&&(a==n-1?c.error=f:(e=k[b][a+1],e.value==nil||0==(e.value&1)?c.error=
f:e.checked||this.markPath(b,a+1,d)))}}catch(g){throw this.exception(g),g;}};this.makeMove2=function(b,a,d){try{if(void 0===a||null==a)a=this.current.value!=b.value&&(this.current.value==nil||0==this.current.value||16==this.current.value)?this.current.value:b.value==nil?0:0==b.value?16:nil;Object.getPrototypeOf(this).makeMove2.call(this,b,a,d)}catch(c){throw this.exception(c),c;}};this.makeMove2Alt=function(b,a,d){try{if(void 0===a||null==a)a=this.current.value!=b.value&&(this.current.value==nil||
0==this.current.value||16==this.current.value)?this.current.value:b.value==nil?16:16==b.value?0:nil;Object.getPrototypeOf(this).makeMove2.call(this,b,a,d)}catch(c){throw this.exception(c),c;}};this.dragTo2=function(b,a){try{if(!(b.fixed||b.areas==this.cell.outside)){if(b.x==a.x-1&&a.y==b.y){switch(a.value){case nil:case 16:case 0:this.makeMove(a,8);break;case 10:this.makeMove(a,10);break;case 12:this.makeMove(a,12);break;case 9:this.makeMove(a,9);break;case 1:this.makeMove(a,9);break;case 2:this.makeMove(a,
10);break;case 4:this.makeMove(a,12);break;case 8:this.makeMove(a,8);break;case 5:l==a.y-1?this.makeMove(a,9):l==a.y+1?this.makeMove(a,12):this.makeMove(a,8);break;case 3:l==a.y-1?this.makeMove(a,9):g==a.x+1?this.makeMove(a,10):this.makeMove(a,8);break;case 6:l==a.y+1?this.makeMove(a,12):g==a.x+1?this.makeMove(a,10):this.makeMove(a,8)}switch(b.value){case nil:case 16:case 0:this.makeMove(b,2);break;case 5:this.makeMove(b,2);break;case 10:this.makeMove(b,10);break;case 3:this.makeMove(b,3);break;case 6:this.makeMove(b,
6);break;case 12:this.makeMove(b,2);break;case 9:this.makeMove(b,2);break;case 1:this.makeMove(b,3);break;case 2:this.makeMove(b,2);break;case 4:this.makeMove(b,6);break;case 8:this.makeMove(b,10)}}if(b.x==a.x+1&&a.y==b.y){switch(a.value){case nil:case 16:case 0:this.makeMove(a,2);break;case 10:this.makeMove(a,10);break;case 3:this.makeMove(a,3);break;case 6:this.makeMove(a,6);break;case 1:this.makeMove(a,3);break;case 2:this.makeMove(a,2);break;case 4:this.makeMove(a,6);break;case 8:this.makeMove(a,
10);break;case 5:l==a.y-1?this.makeMove(a,3):l==a.y+1?this.makeMove(a,6):this.makeMove(a,2);break;case 12:g==a.x-1?this.makeMove(a,10):l==a.y+1?this.makeMove(a,6):this.makeMove(a,2);break;case 9:l==a.y-1?this.makeMove(a,3):g==a.x-1?this.makeMove(a,10):this.makeMove(a,2)}switch(b.value){case nil:case 16:case 0:this.makeMove(b,8);break;case 5:this.makeMove(b,8);break;case 10:this.makeMove(b,10);break;case 3:this.makeMove(b,8);break;case 6:this.makeMove(b,8);break;case 12:this.makeMove(b,12);break;case 9:this.makeMove(b,
9);break;case 1:this.makeMove(b,9);break;case 2:this.makeMove(b,10);break;case 4:this.makeMove(b,12);break;case 8:this.makeMove(b,8)}}if(b.y==a.y+1&&a.x==b.x){switch(a.value){case nil:case 16:case 0:this.makeMove(a,4);break;case 6:this.makeMove(a,6);break;case 12:this.makeMove(a,12);break;case 1:this.makeMove(a,5);break;case 2:this.makeMove(a,6);break;case 4:this.makeMove(a,4);break;case 8:this.makeMove(a,12);break;case 5:this.makeMove(a,5);break;case 10:g==a.x-1?this.makeMove(a,12):g==a.x+1?this.makeMove(a,
6):this.makeMove(a,4);break;case 3:l==a.y-1?this.makeMove(a,5):g==a.x+1?this.makeMove(a,6):this.makeMove(a,4);break;case 9:g==a.x-1?this.makeMove(a,12):l==a.y-1?this.makeMove(a,5):this.makeMove(a,4)}switch(b.value){case nil:case 16:case 0:this.makeMove(b,1);break;case 5:this.makeMove(b,5);break;case 10:this.makeMove(b,1);break;case 3:this.makeMove(b,3);break;case 6:this.makeMove(b,1);break;case 12:this.makeMove(b,1);break;case 9:this.makeMove(b,9);break;case 1:this.makeMove(b,1);break;case 2:this.makeMove(b,
3);break;case 4:this.makeMove(b,5);break;case 8:this.makeMove(b,9)}}if(b.y==a.y-1&&a.x==b.x){switch(a.value){case nil:case 16:case 0:this.makeMove(a,1);break;case 5:this.makeMove(a,5);break;case 3:this.makeMove(a,3);break;case 9:this.makeMove(a,9);break;case 1:this.makeMove(a,1);break;case 2:this.makeMove(a,3);break;case 4:this.makeMove(a,5);break;case 8:this.makeMove(a,9);break;case 10:g==a.x-1?this.makeMove(a,9):g==a.x+1?this.makeMove(a,3):this.makeMove(a,1);break;case 6:l==a.y+1?this.makeMove(a,
5):g==a.x+1?this.makeMove(a,6):this.makeMove(a,4);break;case 12:g==a.x-1?this.makeMove(a,3):l==a.y+1?this.makeMove(a,5):this.makeMove(a,4)}switch(b.value){case nil:case 16:case 0:this.makeMove(b,4);break;case 5:this.makeMove(b,5);break;case 10:this.makeMove(b,4);break;case 3:this.makeMove(b,4);break;case 6:this.makeMove(b,6);break;case 12:this.makeMove(b,12);break;case 9:this.makeMove(b,4);break;case 1:this.makeMove(b,5);break;case 2:this.makeMove(b,6);break;case 4:this.makeMove(b,4);break;case 8:this.makeMove(b,
12)}}g=a.x;l=a.y;this.moveTo(b)}}catch(d){throw this.exception(d),d;}};this.dragTo2Alt=function(b,a){try{a.value!=nil&&this.makeMove(a,nil,this.current.color),b.value!=nil&&this.makeMove(b,nil,this.current.color),this.moveTo(b)}catch(d){throw this.exception(d),d;}};this.valueToString=function(b,a){switch(b){case 16:return a?"x":"-";case 15:return"nsew";case 0:return"o";case 4:return"s";case 1:return"n";case 2:return"e";case 8:return"w";case 3:return"ne";case 9:return"nw";case 6:return"se";case 12:return"sw";
case 5:return"ns";case 10:return"ew";default:return"-"}};this.paintCell=function(b){try{var a=this.canvas.getContext("2d");a.fillStyle=this.uic.light[0];a.fillRect(b.px,b.py,this.unit.x,this.unit.y);if(b.value!=nil){var d=Math.floor((this.unit.x-Math.floor(this.unit.x/4))/2),c=this.unit.x-2*d,f=c+d;a.fillStyle=this.display.errors&&0<b.count?this.uic.dark[b.count%10]:this.display.errors&&1==b.error?this.uic.error:0==b.color?this.uic.line:this.uic.dark[b.color];16==b.value&&!this.solved&&this.paintCross(b);
0==b.value&&a.fillRect(b.px+d,b.py+d,c,c);0!=(b.value&1)&&a.fillRect(b.px+d,b.py,c,f);0!=(b.value&4)&&a.fillRect(b.px+d,b.py+d,c,f);0!=(b.value&2)&&a.fillRect(b.px+d,b.py+d,f,c);0!=(b.value&8)&&a.fillRect(b.px,b.py+d,f,c)}b.label!=nil&&this.paintText(b.label.toString(),b);1==b.clues&&this.paintSquare(b,{scale:80,width:1,stroke:this.uic.black});this.paintSymbolMarkers(b);b.error&&this.display.errors&&(b.label!=nil?this.paintErrorCircle(b):b.value==nil&&this.paintErrorDot(b))}catch(e){throw this.exception(e),
e;}};this.paintCurrentValue=function(){try{var b=this.uie.value,a=b.getContext("2d");a.fillStyle=this.uic.white;a.fillRect(0,0,b.width,b.height);this.current.value!=nil&&(0==this.current.value?this.paintSquare(a,{x:0,y:0,w:b.width,h:b.height,scale:30,stroke:this.uic.none,fill:this.uic.line}):16==this.current.value?this.paintCross(a,{x:0,y:0,w:b.width,h:b.height,stroke:this.uic.cross,fill:this.uic.cross}):this.paintText("#",a,{x:0,y:0,w:b.width,h:b.height,scale:90,stroke:this.uic.black,fill:this.uic.black}))}catch(d){throw this.exception(d),
d;}}}Linesweeper.prototype=new Puzzle;
