function Magnets(){var a=this;a.constructor();a.uis.puzzle=["Magnets","Magnete"];a.charToValue=a.charToValue.concat(["o",3,".",3,"n",0,",",0,"x",nil,"/",nil,"p",1,"+",1,"m",2,"-",2]);a.codeToValue=a.codeToValue.concat([45,3]);a.cell.values=[1,2,0,3,nil];a.enable.dragging=!0;a.keypad.left=nil;a.keypad.right=a.keypad.values;a.labels.north=a.labels.west=2;a.uic.dark[0]=a.uic.neutral=a.uic.any="#666666";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{a.keypadValues=[[a.paintPlus,
1],[a.paintMinus,2],[a.paintAny,3],[" ",0,a.uic.black],["\u2022",nil]];a.level.areas&&a.reset2areas(2,2,a.size.x,a.size.y,a.level.areas);if(a.level.problem){var e=0;var b=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var c=2;c<a.size.y;c++)for(var d=2;d<a.size.x;d++){var g=a.board.c[d][c];var f=b[e++];if("."==f)g.value=nil;else if("+"==f)g.value=1;else if("-"==f)g.value=2;else if("x"==f||"0"==f)g.value=0;g.value!=nil&&(g.fixed=!0)}}if(a.level.clabels)for(e=0,b=a.level.clabels.replace(/\s+/g,
" ").trim().split(" "),c=0;2>c;c++)for(d=2;d<a.size.x;d++)g=a.board.c[d][c],f=b[e++],g.label="."==f||"-"==f?nil:parseInt(f);if(a.level.rlabels)for(e=0,b=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),d=0;2>d;d++)for(c=2;c<a.size.y;c++)g=a.board.c[d][c],f=b[e++],g.label="."==f||"-"==f?nil:parseInt(f);if(a.level.solution)for(e=0,b=a.level.solution.replace(/\s+/g," ").trim().split(" "),c=2;c<a.size.y;c++)for(d=2;d<a.size.x;d++)if(g=a.board.c[d][c],f=b[e++],"."==f)g.solution=nil;else if("+"==f)g.solution=
1;else if("-"==f)g.solution=2;else if("x"==f||"0"==f)g.solution=0;if(a.level.solution&&!a.level.rlabels&&!a.level.clabels){for(d=0;2>d;d++)for(c=2;c<a.size.y;c++)a.board.c[d][c].label=0;for(c=0;2>c;c++)for(d=2;d<a.size.x;d++)a.board.c[d][c].label=0;for(d=2;d<a.size.x;d++)for(c=2;c<a.size.y;c++)1==a.board.c[d][c].solution?(a.board.c[d][0].label++,a.board.c[0][c].label++):2==a.board.c[d][c].solution&&(a.board.c[d][1].label++,a.board.c[1][c].label++)}a.reset2labels()}catch(h){throw a.exception(h),h;
}};a.check2=function(){var e;try{for(var b=a.board.c,c=2;c<a.size.x;c++)for(var d=2;d<a.size.y;d++)b[c][d].value==nil&&(b[c][d].error=1);for(c=2;c<a.size.x;c++){var g=e=0;for(d=2;d<a.size.y;d++)1==b[c][d].value?e++:2==b[c][d].value&&g++;b[c][0].label!=nil&&b[c][0].label!=e&&(b[c][0].error=4);b[c][1].label!=nil&&b[c][1].label!=g&&(b[c][1].error=4)}for(d=2;d<a.size.y;d++){g=e=0;for(c=2;c<a.size.x;c++)1==b[c][d].value?e++:2==b[c][d].value&&g++;b[0][d].label!=nil&&b[0][d].label!=e&&(b[0][d].error=4);
b[1][d].label!=nil&&b[1][d].label!=g&&(b[1][d].error=4)}for(c=2;c<a.size.x;c++)for(d=2;d<a.size.y-1;d++)0!=b[c][d].value&&0!=b[c][d+1].value&&b[c][d].value==b[c][d+1].value&&(b[c][d].error=b[c][d-1].error=2);for(d=2;d<a.size.y;d++)for(c=2;c<a.size.x-1;c++)0!=b[c][d].value&&0!=b[c+1][d].value&&b[c][d].value==b[c+1][d].value&&(b[c][d].error=b[c+1][d].error=2);for(c=2;c<a.size.x;c++)for(d=2;d<a.size.y;d++)!(c<a.size.x-1&&b[c][d].areas==b[c+1][d].areas)||1==b[c][d].value&&2==b[c+1][d].value||2==b[c][d].value&&
1==b[c+1][d].value||0==b[c][d].value&&0==b[c+1][d].value||(b[c][d].error=3,b[c+1][d].error=3),!(d<a.size.y-1&&b[c][d].areas==b[c][d+1].areas)||1==b[c][d].value&&2==b[c][d+1].value||2==b[c][d].value&&1==b[c][d+1].value||0==b[c][d].value&&0==b[c][d+1].value||(b[c][d].error=3,b[c][d+1].error=3)}catch(f){throw a.exception(f),f;}};a.makeMove2=function(e,b,c){try{Object.getPrototypeOf(this).makeMove2.call(this,e,b,c);var d=a.board.c;b=null;var g=e.x,f=e.y;2<g&&e.areas==d[g-1][f].areas?b=a.board.c[g-1][f]:
2<f&&e.areas==d[g][f-1].areas?b=d[g][f-1]:g<a.size.x-1&&e.areas==d[g+1][f].areas?b=d[g+1][f]:f<a.size.y-1&&e.areas==d[g][f+1].areas&&(b=a.board.c[g][f+1]);ojassert(null!=b,"invalid domino");if(!b.fixed)switch(e.value){case 1:b.value=2;break;case 2:b.value=1;break;case 0:b.value=0;break;case 3:b.value=3;break;case nil:b.value=nil}}catch(h){throw a.exception(h),h;}};a.valueToString=function(a,b){switch(a){case 0:return"x";case 3:return"?";case 1:return"+";case 2:return"-";default:return"%"}};a.paintCell=
function(e){try{e.areas==a.cell.label?a.paintLabelCell(e):a.paintValueCell(e)}catch(b){throw a.exception(b),b;}};a.paintLabelCell=function(e){try{var b=a.canvas.getContext("2d");b.fillStyle=a.uic.label;b.fillRect(e.px,e.py,a.unit.x,a.unit.y);0==e.x&&0==e.y&&(a.paintCircle(e,{stroke:a.uic.black,fill:a.uic.gray}),a.paintPlus(e));1==e.x&&1==e.y&&(a.paintCircle(e,{stroke:a.uic.black,fill:a.uic.gray}),a.paintMinus(e));e.label!=nil&&a.paintText(e.label.toString(),e,{color:a.uic.text});e.error&&a.display.errors&&
a.paintErrorCircle(e)}catch(c){throw a.exception(c),c;}};a.paintValueCell=function(e){try{var b=a.canvas.getContext("2d");b.fillStyle=0==e.value?a.uic.dark[e.color]:a.uic.light[e.color];b.fillRect(e.px,e.py,a.unit.x,a.unit.y);var c=e.fixed?a.uic.clue:a.uic.text;switch(e.value){case 1:a.paintPlus(e,{color:c});break;case 2:a.paintMinus(e,{color:c});break;case 3:a.paintAny(e,{color:c})}a.paintSymbolMarkers(e);e.error&&a.display.errors&&(e.value==nil?a.paintErrorDot(e):a.paintErrorCircle(e))}catch(d){throw a.exception(d),
d;}};a.paintPlus=function(e,b){try{if(b=a.defaultParams(e,b)){e.px&&(e=a.canvas.getContext("2d"));e.strokeStyle=b.color?b.color:a.uic.text;e.fillStyle=b.color?b.color:a.uic.text;e.lineWidth=b.width?b.width:2;var c=Math.floor(b.w/4);e.beginPath();e.moveTo(b.x+c,b.y+b.h/2);e.lineTo(b.x+b.w-c,b.y+b.h/2);e.moveTo(b.x+b.w/2,b.y+c);e.lineTo(b.x+b.w/2,b.y+b.h-c);e.stroke()}}catch(d){throw a.exception(d),d;}};a.paintMinus=function(e,b){try{if(b=a.defaultParams(e,b)){e.px&&(e=a.canvas.getContext("2d"));b.scale||
(b.scale=75);e.strokeStyle=b.color?b.color:a.uic.text;e.fillStyle=b.color?b.color:a.uic.text;e.lineWidth=b.width?b.width:2;var c=Math.floor(b.w/4);e.beginPath();e.moveTo(b.x+c,b.y+b.h/2);e.lineTo(b.x+b.w-c,b.y+b.h/2);e.stroke()}}catch(d){throw a.exception(d),d;}};a.paintAny=function(e,b){try{if(b=a.defaultParams(e,b))e.px&&(e=a.canvas.getContext("2d")),b.fill=a.uic.none,b.stroke=a.uic.any,b.width=2,b.scale=50,a.paintCircle(e,b)}catch(c){throw a.exception(c),c;}};a.paintCurrentValue=function(){try{var e=
a.uie.value,b=e.getContext("2d");b.fillStyle=0==a.current.value?a.uic.black:a.uic.white;b.fillRect(0,0,e.width,e.height);var c={x:0,y:0,w:e.width,h:e.height,fill:a.uic.none,stroke:a.uic.black};switch(a.current.value){case 1:a.paintPlus(b,c);break;case 2:a.paintMinus(b,c);break;case 3:a.paintAny(b,c);break;case 0:a.paintText("0",b,c)}}catch(d){throw a.exception(d),d;}}}Magnets.prototype=new Puzzle;
