function Masyu(){var a=this;a.constructor();a.uis.puzzle=["Masyu"];var h=nil,k=nil;a.charToValue=a.charToValue.concat(["-",nil,"/",nil,".",0,"o",0,",",16,"x",16]);a.enable.dragging=!0;a.enable.pgrid=!0;a.keypad.left=nil;a.cell.nilalias=16;a.uic.noturnedge="#000000";a.uic.noturnfill="#ffffff";a.uic.anyturnedge="#000000";a.uic.anyturnfill="#aaaaaa";a.uic.mustturnedge="#000000";a.uic.mustturnfill="#333333";a.uic.forbidden="#339933";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{a.level.variant||
(a.level.variant="masyu");a.level.areas&&a.reset2areas(0,0,a.size.x,a.size.y,a.level.areas);if(a.level.problem){var c=0;var b=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=0;d<a.size.y;d++)for(var e=0;e<a.size.x;e++){var g=a.board.c[e][d];var f=b[c++];"."==f||"-"==f?g.value=nil:"s"==f||"z"==f?g.label=95:"b"==f||"2"==f?g.label=92:"w"==f||"1"==f?g.label=94:"g"==f||"?"==f?g.label=93:"x"==f||"#"==f?(g.areas=a.cell.black,g.value=16):"@"==f&&(g.areas=a.cell.outside,g.value=16,g.valid=
!1);g.areas!=nil&&(g.fixed=!0)}}if(a.level.solution)for(c=0,b=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=0;d<a.size.y;d++)for(e=0;e<a.size.x;e++)if(g=a.board.c[e][d],f=b[c++],"-"==f||"."==f)g.solution=nil;else{var h=0;f.contains("n")&&(h|=1);f.contains("s")&&(h|=4);if(f.contains("e")||f.contains("o"))h|=2;f.contains("w")&&(h|=8);0!=h&&(g.solution=h)}}catch(m){throw a.exception(m),m;}};a.check2=function(){try{for(var c=0,b=0;b<a.size.x;b++)for(var d=0;d<a.size.y;d++)a.board.c[b][d].checked||
16==a.board.c[b][d].value||0==a.board.c[b][d].value||a.board.c[b][d].value==nil||a.markPath(b,d,c++);if(1!=c)for(a.solved=!1,b=0;b<a.size.x;b++)for(d=0;d<a.size.y;d++)1==a.board.c[b][d].error&&(a.board.c[b][d].error=0);for(b=0;b<a.size.x;b++)for(d=0;d<a.size.y;d++){var e=a.board.c[b][d];1!=e.value&&4!=e.value&&2!=e.value&&8!=e.value||95==e.label||(e.error=3);94!=e.label&&92!=e.label&&93!=e.label||0!=(e.value&15)&&e.value!=nil||(e.error=2);0==e.value&&(e.error=3)}if("path"==a.level.variant)for(b=0;b<
a.size.x;b++)for(d=0;d<a.size.y;d++)e=a.board.c[b][d],e.areas==nil&&e.value==nil&&(a.board.c[b][d].error=2),92==e.label&&3!=e.value&&6!=e.value&&9!=e.value&&12!=e.value&&(e.error=2),94!=e.label||3!=e.value&&6!=e.value&&9!=e.value&&12!=e.value||(e.error=3);if("masyu"==a.level.variant)for(b=0;b<a.size.x;b++)for(d=0;d<a.size.y;d++){e=a.board.c[b][d];if(92==e.label)switch(e.value){case 3:if(0==d||b==a.size.x-1||5!=a.board.c[b][d-1].value||10!=a.board.c[b+1][d].value)e.error=3;break;case 6:if(d==a.size.y-
1||b==a.size.x-1||5!=a.board.c[b][d+1].value||10!=a.board.c[b+1][d].value)e.error=3;break;case 9:if(0==d||0==b||5!=a.board.c[b][d-1].value||10!=a.board.c[b-1][d].value)e.error=3;break;case 12:if(d==a.size.y-1||0==b||5!=a.board.c[b][d+1].value||10!=a.board.c[b-1][d].value)e.error=3;break;default:e.error=3}if(94==e.label)switch(e.value){case 5:0==d||d==a.size.y-1?e.error=3:3!=a.board.c[b][d+1].value&&9!=a.board.c[b][d+1].value&&6!=a.board.c[b][d-1].value&&12!=a.board.c[b][d-1].value&&(e.error=3);break;
case 10:0==b||b==a.size.x-1?e.error=3:12!=a.board.c[b+1][d].value&&9!=a.board.c[b+1][d].value&&6!=a.board.c[b-1][d].value&&3!=a.board.c[b-1][d].value&&(e.error=3);break;default:e.error=3}}}catch(g){throw a.exception(g),g;}};a.markPath=function(c,b,d){try{var e=a.board.c[c][b];if(e.value!=nil){e.checked=!0;e.count=d;var g=0==d?1:d;"path"==a.level.variant||2!=e.value&&8!=e.value&&1!=e.value&&4!=e.value||(e.error=g);if(0!=(e.value&8))if(0==c)e.error=g;else{var f=a.board.c[c-1][b];f.value==nil||0==(f.value&
2)?e.error=g:f.checked||a.markPath(c-1,b,d)}0!=(e.value&2)&&(c==a.size.x-1?e.error=g:(f=a.board.c[c+1][b],f.value==nil||0==(f.value&8)?e.error=g:f.checked||a.markPath(c+1,b,d)));0!=(e.value&1)&&(0==b?e.error=1:(f=a.board.c[c][b-1],f.value==nil||0==(f.value&4)?e.error=g:f.checked||a.markPath(c,b-1,d)));0!=(e.value&4)&&(b==a.size.y-1?e.error=g:(f=a.board.c[c][b+1],f.value==nil||0==(f.value&1)?e.error=g:f.checked||a.markPath(c,b+1,d)))}}catch(l){throw a.exception(l),l;}};a.solve2=function(){try{if("masyu"==
a.level.variant)for(var c=0;c<a.size.x;c++)for(var b=0;b<a.size.y;b++)if(a.board.c[c][b].label!=nil){if(92==a.board.c[c][b].label){if(0==c||1==c)a.solve2Move(c,b,c+1,b),a.solve2Move(c+1,b,c+2,b);if(c==a.size.x-1||c==a.size.x-2)a.solve2Move(c,b,c-1,b),a.solve2Move(c-1,b,c-2,b);if(0==b||1==b)a.solve2Move(c,b,c,b+1),a.solve2Move(c,b+1,c,b+2);if(b==a.size.y-1||b==a.size.y-2)a.solve2Move(c,b,c,b-1),a.solve2Move(c,b-1,c,b-2);c<a.size.x-1&&92==a.board.c[c+1][b].label&&(a.solve2Move(c,b,c-1,b),a.solve2Move(c-
1,b,c-2,b),94==a.board.c[c-2][b].label&&a.solve2Move(c-2,b,c-3,b),a.solve2Move(c+1,b,c+2,b),a.solve2Move(c+2,b,c+3,b),94==a.board.c[c+3][b].label&&a.solve2Move(c+3,b,c+4,b));b<a.size.y-1&&92==a.board.c[c][b+1].label&&(a.solve2Move(c,b,c,b-1),a.solve2Move(c,b-1,c,b-2),94==a.board.c[c][b-2].label&&a.solve2Move(c,b-2,c,b-3),a.solve2Move(c,b+1,c,b+2),a.solve2Move(c,b+2,c,b+3),94==a.board.c[c][b+3].label&&a.solve2Move(c,b+3,c,b+4))}if(94==a.board.c[c][b].label){if(0==c||c==a.size.x-1)a.solve2Move(c,b-
1,c,b),a.solve2Move(c,b,c,b+1);if(0==b||b==a.size.y-1)a.solve2Move(c-1,b,c,b),a.solve2Move(c,b,c+1,b);if(c<a.size.x-2&&94==a.board.c[c+1][b].label&&94==a.board.c[c+2][b].label)for(var d=c;d<a.size.x&&94==a.board.c[d][b].label;d++)0<b&&94==a.board.c[d][b-1].label&&a.solve2Move(d,b-2,d,b-1),a.solve2Move(d,b-1,d,b),a.solve2Move(d,b,d,b+1),b<a.size.y-1&&94==a.board.c[d][b+1].label&&a.solve2Move(d,b+1,d,b+2);if(b<a.size.y-2&&94==a.board.c[c][b+1].label&&94==a.board.c[c][b+2].label)for(d=b;d<a.size.y&&
94==a.board.c[c][d].label;d++)0<c&&94==a.board.c[c-1][d].label&&a.solve2Move(c-2,d,c-1,d),a.solve2Move(c-1,d,c,d),a.solve2Move(c,d,c+1,d),c<a.size.x-1&&94==a.board.c[c+1][d].label&&a.solve2Move(c+1,d,c+2,d)}}}catch(e){throw a.exception(e),e;}};a.solve2Move=function(c,b,d,e){try{a.checking.disable++,a.moves.disable++,a.dragTo(a.board.c[c][b],a.board.c[d][e]),a.moves.disable--,a.checking.disable--}catch(g){throw a.exception(g),g;}};a.makeMove2=function(c,b,d){try{if(void 0===b||null==b)b=a.current.value==
c.value||a.current.value!=nil&&0!=a.current.value&&16!=a.current.value?c.value==nil?0:0==c.value?16:nil:a.current.value;Object.getPrototypeOf(this).makeMove2.call(this,c,b,d)}catch(e){throw a.exception(e),e;}};a.makeMove2Alt=function(c,b,d){try{if(void 0===b||null==b)b=a.current.value==c.value||a.current.value!=nil&&0!=a.current.value&&16!=a.current.value?c.value==nil?16:16==c.value?0:nil:a.current.value;Object.getPrototypeOf(this).makeMove2.call(this,c,b,d)}catch(e){throw a.exception(e),e;}};a.dragTo2=
function(c,b){try{if(!c.fixed&&c.areas!=a.cell.outside){if(c.x==b.x-1&&b.y==c.y){switch(b.value){case nil:case 16:case 0:a.makeMove(b,8);break;case 10:a.makeMove(b,10);break;case 12:a.makeMove(b,12);break;case 9:a.makeMove(b,9);break;case 1:a.makeMove(b,9);break;case 2:a.makeMove(b,10);break;case 4:a.makeMove(b,12);break;case 8:a.makeMove(b,8);break;case 5:k==b.y-1?a.makeMove(b,9):k==b.y+1?a.makeMove(b,12):a.makeMove(b,8);break;case 3:k==b.y-1?a.makeMove(b,9):h==b.x+1?a.makeMove(b,10):a.makeMove(b,
8);break;case 6:k==b.y+1?a.makeMove(b,12):h==b.x+1?a.makeMove(b,10):a.makeMove(b,8)}95==b.label&&a.makeMove(b,8);switch(c.value){case nil:case 16:case 0:a.makeMove(c,2);break;case 5:a.makeMove(c,2);break;case 10:a.makeMove(c,10);break;case 3:a.makeMove(c,3);break;case 6:a.makeMove(c,6);break;case 12:a.makeMove(c,2);break;case 9:a.makeMove(c,2);break;case 1:a.makeMove(c,3);break;case 2:a.makeMove(c,2);break;case 4:a.makeMove(c,6);break;case 8:a.makeMove(c,10)}95==b.label&&a.makeMove(c,2)}if(c.x==b.x+
1&&b.y==c.y){switch(b.value){case nil:case 16:case 0:a.makeMove(b,2);break;case 10:a.makeMove(b,10);break;case 3:a.makeMove(b,3);break;case 6:a.makeMove(b,6);break;case 1:a.makeMove(b,3);break;case 2:a.makeMove(b,2);break;case 4:a.makeMove(b,6);break;case 8:a.makeMove(b,10);break;case 5:k==b.y-1?a.makeMove(b,3):k==b.y+1?a.makeMove(b,6):a.makeMove(b,2);break;case 12:h==b.x-1?a.makeMove(b,10):k==b.y+1?a.makeMove(b,6):a.makeMove(b,2);break;case 9:k==b.y-1?a.makeMove(b,3):h==b.x-1?a.makeMove(b,10):a.makeMove(b,
2)}95==b.label&&a.makeMove(b,2);switch(c.value){case nil:case 16:case 0:a.makeMove(c,8);break;case 5:a.makeMove(c,8);break;case 10:a.makeMove(c,10);break;case 3:a.makeMove(c,8);break;case 6:a.makeMove(c,8);break;case 12:a.makeMove(c,12);break;case 9:a.makeMove(c,9);break;case 1:a.makeMove(c,9);break;case 2:a.makeMove(c,10);break;case 4:a.makeMove(c,12);break;case 8:a.makeMove(c,8)}}95==b.label&&a.makeMove(c,8);if(c.y==b.y+1&&b.x==c.x){switch(b.value){case nil:case 16:case 0:a.makeMove(b,4);break;
case 6:a.makeMove(b,6);break;case 12:a.makeMove(b,12);break;case 1:a.makeMove(b,5);break;case 2:a.makeMove(b,6);break;case 4:a.makeMove(b,4);break;case 8:a.makeMove(b,12);break;case 5:a.makeMove(b,5);break;case 10:h==b.x-1?a.makeMove(b,12):h==b.x+1?a.makeMove(b,6):a.makeMove(b,4);break;case 3:k==b.y-1?a.makeMove(b,5):h==b.x+1?a.makeMove(b,6):a.makeMove(b,4);break;case 9:h==b.x-1?a.makeMove(b,12):k==b.y-1?a.makeMove(b,5):a.makeMove(b,4)}95==b.label&&a.makeMove(b,4);switch(c.value){case nil:case 16:case 0:a.makeMove(c,
1);break;case 5:a.makeMove(c,5);break;case 10:a.makeMove(c,1);break;case 3:a.makeMove(c,3);break;case 6:a.makeMove(c,1);break;case 12:a.makeMove(c,1);break;case 9:a.makeMove(c,9);break;case 1:a.makeMove(c,1);break;case 2:a.makeMove(c,3);break;case 4:a.makeMove(c,5);break;case 8:a.makeMove(c,9)}95==b.label&&a.makeMove(c,1)}if(c.y==b.y-1&&b.x==c.x){switch(b.value){case nil:case 16:case 0:a.makeMove(b,1);break;case 5:a.makeMove(b,5);break;case 3:a.makeMove(b,3);break;case 9:a.makeMove(b,9);break;case 1:a.makeMove(b,
1);break;case 2:a.makeMove(b,3);break;case 4:a.makeMove(b,5);break;case 8:a.makeMove(b,9);break;case 10:h==b.x-1?a.makeMove(b,9):h==b.x+1?a.makeMove(b,3):a.makeMove(b,1);break;case 6:k==b.y+1?a.makeMove(b,5):h==b.x+1?a.makeMove(b,6):a.makeMove(b,4);break;case 12:h==b.x-1?a.makeMove(b,3):k==b.y+1?a.makeMove(b,5):a.makeMove(b,4)}95==b.label&&a.makeMove(b,1);switch(c.value){case nil:case 16:case 0:a.makeMove(c,4);break;case 5:a.makeMove(c,5);break;case 10:a.makeMove(c,4);break;case 3:a.makeMove(c,4);
break;case 6:a.makeMove(c,6);break;case 12:a.makeMove(c,12);break;case 9:a.makeMove(c,4);break;case 1:a.makeMove(c,5);break;case 2:a.makeMove(c,6);break;case 4:a.makeMove(c,4);break;case 8:a.makeMove(c,12)}95==b.label&&a.makeMove(c,4)}h=b.x;k=b.y;a.moveTo(c);a.current.value=0}}catch(d){throw a.exception(d),d;}};a.dragTo2Alt=function(c,b){try{b.value!=nil&&a.makeMove(b,nil,a.current.color),c.value!=nil&&a.makeMove(c,nil,a.current.color),a.moveTo(c)}catch(d){throw a.exception(d),d;}};a.valueToString=
function(a,b){switch(a){case 16:return b?"x":"-";case 15:return"nsew";case 0:return"o";case 4:return"s";case 1:return"n";case 2:return"e";case 8:return"w";case 3:return"ne";case 9:return"nw";case 6:return"se";case 12:return"sw";case 5:return"ns";case 10:return"ew";default:return"-"}};a.paintCell=function(c){try{var b=a.canvas.getContext("2d");b.fillStyle=c.areas==a.cell.black?a.uic.black:a.uic.light[0];b.fillRect(c.px,c.py,a.unit.x,a.unit.y);if(16==c.value)a.paintCross(c);else if(c.value!=nil){var d=
Math.floor((a.unit.x-Math.floor(a.unit.x/4))/2),e=a.unit.x-2*d,g=e+d;b.fillStyle=a.display.errors&&0<c.count?a.uic.dark[c.count%10]:a.display.errors&&1==c.error?a.uic.error:0==c.color?a.uic.line:a.uic.dark[c.color];16!=c.value||a.solved||a.paintCross(c);0==c.value&&b.fillRect(c.px+d,c.py+d,e,e);0!=(c.value&1)&&b.fillRect(c.px+d,c.py,e,g);0!=(c.value&4)&&b.fillRect(c.px+d,c.py+d,e,g);0!=(c.value&2)&&b.fillRect(c.px+d,c.py+d,g,e);0!=(c.value&8)&&b.fillRect(c.px,c.py+d,g,e)}if(95==c.label)a.paintStar(c);
else if(92==c.label){var f={width:1,scale:50};c.error&&a.display.errors?f.fill=f.stroke=a.uic.error:(f.fill=a.uic.mustturnfill,f.stroke=a.uic.mustturnedge);a.paintCircle(c,f)}else 93==c.label?(f={fill:a.uic.anyturnfill,width:1,scale:50},f.stroke=c.error&&a.display.errors?a.uic.error:a.uic.anyturnedge,a.paintCircle(c,f)):94==c.label&&(f={fill:a.uic.noturnfill,width:1,scale:50},f.stroke=c.error&&a.display.errors?a.uic.error:a.uic.noturnedge,a.paintCircle(c,f));a.paintSymbolMarkers(c);c.error&&a.display.errors&&
(95==c.label?a.paintErrorCircle(c):c.value==nil?a.paintErrorDot(c):c.error&&a.paintErrorDot(c))}catch(l){throw a.exception(l),l;}};a.paintCurrentValue=function(){try{var c=a.uie.value,b=c.getContext("2d");b.fillStyle=a.uic.white;b.fillRect(0,0,c.width,c.height);a.current.value!=nil&&(0==a.current.value?a.paintSquare(b,{x:0,y:0,w:c.width,h:c.height,scale:30,stroke:a.uic.none,fill:a.uic.line}):16==a.current.value?a.paintCross(b,{x:0,y:0,w:c.width,h:c.height,stroke:a.uic.cross,fill:a.uic.cross}):a.paintText("#",
b,{x:0,y:0,w:c.width,h:c.height,scale:90,stroke:a.uic.black,fill:a.uic.black}))}catch(d){throw a.exception(d),d;}}}Masyu.prototype=new Puzzle;
