function Mochikoro(){var c=this;c.constructor();c.uis.puzzle=["Mochikoro"];var d=c.board.c,l=0,m=0,g={gray:nil,dark:0,light:1};c.charToValue=c.charToValue.concat(["a",g.dark,"s",g.light,"d",nil,"x",g.dark,"c",g.light,"v",nil,",",g.dark,".",g.light,"-",nil,"/",nil]);c.cell.values=[g.dark,g.light,g.gray];c.enable.dragging=!0;c.enable.pgrid=!0;c.keypad.left=nil;c.cell.nilalias=g.light;c.init=function(){Object.getPrototypeOf(c).init.call(c)};c.reset2=function(){try{l=c.size.x;m=c.size.y;if(c.level.problem){var a=
0;var b=c.level.problem.replace(/\s+/g," ").trim().split(" ");for(var e=0;e<m;e++)for(var h=0;h<l;h++){var k=d[h][e];var f=b[a++];"."!=f&&"-"!=f&&("@"==f?(call.areas=c.cell.outside,k.fixed=!0,k.valid=!1):"x"==f?k.value=g.dark:"o"==f?k.value=g.light:"?"==f?k.label=0:1==f.length&&"a"<=f.charAt(0)&&"z">=f.charAt(0)?k.clues=f.charAt(0)-NaN+1:k.label=parseInt(f));if(k.value!=nil||k.label!=nil||0!=k.clues)k.fixed=!0;k.label!=nil&&(k.value=g.light)}}if(c.level.solution)for(a=0,b=c.level.solution.replace(/\s+/g,
" ").trim().split(" "),e=0;e<m;e++)for(h=0;h<l;h++)k=d[h][e],f=b[a++],k.solution="x"==f?g.dark:g.light}catch(n){throw c.exception(n),n;}};c.check2=function(){try{for(var a=0;a<l-1;a++)for(var b=0;b<m-1;b++)if(d[a][b].value==g.dark){var e=0;d[a][b+1].value==g.dark&&e++;d[a+1][b+1].value==g.dark&&e++;d[a+1][b].value==g.dark&&e++;3==e&&(d[a][b].error=d[a+1][b].error=d[a][b+1].error=d[a+1][b+1].error=4)}for(a=0;a<l;a++)for(b=0;b<m;b++)if(d[a][b].value!=g.black&&!d[a][b].checked){e=0;for(var h=a;h<l&&
d[h][b].value!=g.dark;h++)e++;for(var k=0,f=b;f<m&&d[a][f].value!=g.dark;f++)k++;var n=null,r=!1;for(h=a;h<a+e;h++)for(f=b;f<b+k;f++){var p=d[h][f];p.checked=!0;p.value!=g.light&&(r=!0);p.label!=nil&&(null==n?n=p:p.error=n.error=2)}if(r)for(h=a;h<a+e;h++)for(f=b;f<b+k;f++)d[h][f].error=3;null!=n&&n.label!=e*k&&(n.error=1);if(0<a)for(f=b;f<b+k;f++)d[a-1][f].value==g.light&&(d[a][f].error=d[a-1][f].error=3);if(a+e<l-1)for(f=b;f<b+k;f++)d[a+e][f].value==g.light&&(d[a+e-1][f].error=d[a+e][f].error=3);
if(0<b)for(h=a;h<a+e;h++)d[h][b-1].value==g.light&&(d[h][b].error=d[h][b-1].error=3);if(b+k<m-1)for(h=a;h<a+e;h++)d[h][b+k].value==g.light&&(d[h][b+k-1].error=d[h][b+k].error=3)}p=1;for(a=0;a<l;a++)for(b=0;b<m;b++){var q=d[a][b];q.value!=g.dark&&0==q.count&&c.markArea(q,p++,8)}2!=p&&(c.solved=!1)}catch(t){throw c.exception(t),t;}};c.solve2=function(){try{for(var a=0;a<l;a++)for(var b=0;b<m;b++)1==d[a][b].label?(c.solveCellDark(a-1,b),c.solveCellDark(a,b-1),c.solveCellDark(a+1,b),c.solveCellDark(a,
b+1)):d[a][b].label!=nil&&(1<a&&d[a-2][b].label!=nil&&c.solveCellDark(a-1,b),a<l-2&&d[a+2][b].label!=nil&&c.solveCellDark(a+1,b),1<b&&d[a][b-1].label!=nil&&c.solveCellDark(a,b-1),b<m-2&&d[a][b+2].label!=nil&&c.solveCellDark(a,b+1),0<a&&0<b&&d[a-1][b-1].label!=nil&&(c.solveCellDark(a-1,b),c.solveCellDark(a,b-1)),a<l-1&&b<m-1&&d[a+1][b+1].label!=nil&&(c.solveCellDark(a+1,b),c.solveCellDark(a,b+1)),a<l-1&&0<b&&d[a+1][b-1].label!=nil&&(c.solveCellDark(a+1,b),c.solveCellDark(a,b-1)),0<a&&b<m-1&&d[a-1][b+
1].label!=nil&&(c.solveCellDark(a-1,b),c.solveCellDark(a,b+1)));c.pushEvent(c.moves.typeSolve,0);c.check()}catch(e){throw c.exception(e),e;}};c.solveCellDark=function(a,b){try{0<=a&&a<l&&0<=b&&b<m&&(d[a][b].value=g.dark,d[a][b].color=c.current.color)}catch(e){throw c.exception(e),e;}};c.cleanSolution=function(){for(var a=0;a<l;a++)for(var b=0;b<m;b++){var c=d[a][b];c.value==nil&&(c.value=g.light)}};c.valueToString=function(a,b){try{switch(a){case nil:return"-";case g.dark:return"x";case g.light:return b?
".":"-";default:return"%"}}catch(e){return ojdebug(e.toString()),"%"}};c.labelToString=function(a,b){try{return a==nil?"-":0==a?"?":parseInt(a)}catch(e){return ojdebug(e.toString()),"%"}};c.paintCell=function(a){try{var b=c.canvas.getContext("2d");b.fillStyle=a.value==nil?c.paintToImage&&c.moves.current==nil?c.uic.white:c.uic.gray:a.value==g.dark?c.uic.dark[a.color]:!c.solved&&c.display.errors?c.uic.light[(a.count-1)%10]:c.uic.light[a.color];b.fillRect(a.px,a.py,c.unit.x,c.unit.y);0==a.label?c.paintText("?",
a):a.label!=nil&&c.paintText(a.label.toString(),a);c.paintSymbolMarkers(a);a.error&&c.display.errors&&(a.label!=nil?c.paintErrorCircle(a):c.paintErrorDot(a))}catch(e){throw c.exception(e),e;}};c.paintCurrentValue=function(){try{var a=c.uie.value,b=a.getContext("2d");b.fillStyle=c.current.value==g.gray?c.uic.gray:c.current.value==g.dark?c.uic.black:c.uic.white;b.fillRect(0,0,a.width,a.height)}catch(e){throw c.exception(e),e;}}}Mochikoro.prototype=new Puzzle;
