function Numbersnake(){var a=this;a.constructor();a.uis.puzzle=["Number Snake","Zahlenschlange"];var g=nil,f=nil,h={none:0,path:1,duplicate:2,unused:3};a.charToValue=a.charToValue.concat(["-",nil,"/",nil,".",0,"o",0,",",16,"x",16]);a.enable.dragging=!0;a.enable.pgrid=!0;a.keypad.left=nil;a.cell.nilalias=16;a.uic.line="#ffcc66";a.uic.dimmed="#999999";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{if(a.level.problem){var c=0;var b=a.level.problem.replace(/\s+/g," ").trim().split(" ");
for(var d=0;d<a.size.y;d++)for(var e=0;e<a.size.x;e++){var g=a.board.c[e][d];var f=b[c++];g.label="."==f||"-"==f?nil:parseInt(f)}}if(a.level.solution)for(c=0,b=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=0;d<a.size.y;d++)for(e=0;e<a.size.x;e++)if(g=a.board.c[e][d],f=b[c++],"-"==f||"."==f)g.solution=nil;else{var h=0;f.contains("n")&&(h|=1);f.contains("s")&&(h|=4);if(f.contains("e")||f.contains("o"))h|=2;f.contains("w")&&(h|=8);0!=h&&(g.solution=h)}}catch(m){throw a.exception(m),m;}};a.check2=
function(){try{a.checkPath(a.board.c[0][0],null,1);for(var c=0;c<a.size.x;c++)for(var b=0;b<a.size.y;b++){var d=a.board.c[c][b];d.value!=nil&&16!=d.value&&0==d.count&&(d.error=h.path)}numbersUsed=[];for(var e=0;e<=a.board.c[a.size.x-1][a.size.y-1].label;e++)numbersUsed[e]=null;for(c=0;c<a.size.x;c++)for(b=0;b<a.size.y;b++)d=a.board.c[c][b],d.value!=nil&&16!=d.value&&0!=d.count&&(null==numbersUsed[d.label]?numbersUsed[d.label]=d:numbersUsed[d.label].error=d.error=h.duplicate);for(e=1;e<=a.board.c[a.size.x-
1][a.size.y-1].label;e++)if(null==numbersUsed[e])for(c=0;c<a.size.x;c++)for(b=0;b<a.size.y;b++)a.board.c[c][b].label==e&&(a.board.c[c][b].error=h.unused)}catch(k){throw a.exception(k),k;}};a.checkPath=function(c,b,d){try{c.value==nil&&(c.error=h.empty),0!=c.count&&(c.error=h.path),c.count=d,(0==c.x&&0==c.y||c.x==a.size.x-1&&c.y==a.size.y-1)&&1!=c.value&&4!=c.value&&2!=c.value&&8!=c.value&&(c.error=h.path),1!=c.value&&4!=c.value&&2!=c.value&&8!=c.value||0==c.x&&0==c.y||c.x==a.size.x-1&&c.y==a.size.y-
1||(c.error=h.path),b&&(c.x-1==b.x&&0==(c.value&8)&&(c.error=h.path),c.x+1==b.x&&0==(c.value&2)&&(c.error=h.path),c.y-1==b.y&&0==(c.value&1)&&(c.error=h.path),c.y+1==b.y&&0==(c.value&4)&&(c.error=h.path)),c.error||(0!=(c.value&8)&&(0==c.x?checkPathError=!0:(null==b||b.x!=c.x-1)&&a.checkPath(a.board.c[c.x-1][c.y],c,d)),0!=(c.value&2)&&(c.x==a.size.x-1?checkPathError=!0:(null==b||b.x!=c.x+1)&&a.checkPath(a.board.c[c.x+1][c.y],c,d)),0!=(c.value&1)&&(0==c.y?checkPathError=!0:(null==b||b.y!=c.y-1)&&a.checkPath(a.board.c[c.x][c.y-
1],c,d)),0!=(c.value&4)&&(c.y==a.size.y-1?checkPathError=!0:(null==b||b.y!=c.y+1)&&a.checkPath(a.board.c[c.x][c.y+1],c,d)))}catch(e){throw a.exception(e),e;}};a.makeMove2=function(c,b,d){try{if(void 0===b||null==b)b=a.current.value==c.value||a.current.value!=nil&&0!=a.current.value&&16!=a.current.value?c.value==nil?0:0==c.value?16:nil:a.current.value;Object.getPrototypeOf(this).makeMove2.call(this,c,b,d)}catch(e){throw a.exception(e),e;}};a.makeMove2Alt=function(c,b,d){try{if(void 0===b||null==b)b=
a.current.value==c.value||a.current.value!=nil&&0!=a.current.value&&16!=a.current.value?c.value==nil?16:16==c.value?0:nil:a.current.value;Object.getPrototypeOf(this).makeMove2.call(this,c,b,d)}catch(e){throw a.exception(e),e;}};a.dragTo2=function(c,b){try{if(!c.fixed&&c.areas!=a.cell.outside){if(c.x==b.x-1&&b.y==c.y){switch(b.value){case nil:case 16:case 0:a.makeMove(b,8);break;case 10:a.makeMove(b,10);break;case 12:a.makeMove(b,12);break;case 9:a.makeMove(b,9);break;case 1:a.makeMove(b,9);break;
case 2:a.makeMove(b,10);break;case 4:a.makeMove(b,12);break;case 8:a.makeMove(b,8);break;case 5:f==b.y-1?a.makeMove(b,9):f==b.y+1?a.makeMove(b,12):a.makeMove(b,8);break;case 3:f==b.y-1?a.makeMove(b,9):g==b.x+1?a.makeMove(b,10):a.makeMove(b,8);break;case 6:f==b.y+1?a.makeMove(b,12):g==b.x+1?a.makeMove(b,10):a.makeMove(b,8)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(b,8);switch(c.value){case nil:case 16:case 0:a.makeMove(c,2);break;case 5:a.makeMove(c,2);break;case 10:a.makeMove(c,
10);break;case 3:a.makeMove(c,3);break;case 6:a.makeMove(c,6);break;case 12:a.makeMove(c,2);break;case 9:a.makeMove(c,2);break;case 1:a.makeMove(c,3);break;case 2:a.makeMove(c,2);break;case 4:a.makeMove(c,6);break;case 8:a.makeMove(c,10)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(c,2)}if(c.x==b.x+1&&b.y==c.y){switch(b.value){case nil:case 16:case 0:a.makeMove(b,2);break;case 10:a.makeMove(b,10);break;case 3:a.makeMove(b,3);break;case 6:a.makeMove(b,6);break;case 1:a.makeMove(b,
3);break;case 2:a.makeMove(b,2);break;case 4:a.makeMove(b,6);break;case 8:a.makeMove(b,10);break;case 5:f==b.y-1?a.makeMove(b,3):f==b.y+1?a.makeMove(b,6):a.makeMove(b,2);break;case 12:g==b.x-1?a.makeMove(b,10):f==b.y+1?a.makeMove(b,6):a.makeMove(b,2);break;case 9:f==b.y-1?a.makeMove(b,3):g==b.x-1?a.makeMove(b,10):a.makeMove(b,2)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(b,2);switch(c.value){case nil:case 16:case 0:a.makeMove(c,8);break;case 5:a.makeMove(c,8);break;case 10:a.makeMove(c,
10);break;case 3:a.makeMove(c,8);break;case 6:a.makeMove(c,8);break;case 12:a.makeMove(c,12);break;case 9:a.makeMove(c,9);break;case 1:a.makeMove(c,9);break;case 2:a.makeMove(c,10);break;case 4:a.makeMove(c,12);break;case 8:a.makeMove(c,8)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(c,8)}if(c.y==b.y+1&&b.x==c.x){switch(b.value){case nil:case 16:case 0:a.makeMove(b,4);break;case 6:a.makeMove(b,6);break;case 12:a.makeMove(b,12);break;case 1:a.makeMove(b,5);break;case 2:a.makeMove(b,
6);break;case 4:a.makeMove(b,4);break;case 8:a.makeMove(b,12);break;case 5:a.makeMove(b,5);break;case 10:g==b.x-1?a.makeMove(b,12):g==b.x+1?a.makeMove(b,6):a.makeMove(b,4);break;case 3:f==b.y-1?a.makeMove(b,5):g==b.x+1?a.makeMove(b,6):a.makeMove(b,4);break;case 9:g==b.x-1?a.makeMove(b,12):f==b.y-1?a.makeMove(b,5):a.makeMove(b,4)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(b,4);switch(c.value){case nil:case 16:case 0:a.makeMove(c,1);break;case 5:a.makeMove(c,5);break;case 10:a.makeMove(c,
1);break;case 3:a.makeMove(c,3);break;case 6:a.makeMove(c,1);break;case 12:a.makeMove(c,1);break;case 9:a.makeMove(c,9);break;case 1:a.makeMove(c,1);break;case 2:a.makeMove(c,3);break;case 4:a.makeMove(c,5);break;case 8:a.makeMove(c,9)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(c,1)}if(c.y==b.y-1&&b.x==c.x){switch(b.value){case nil:case 16:case 0:a.makeMove(b,1);break;case 5:a.makeMove(b,5);break;case 3:a.makeMove(b,3);break;case 9:a.makeMove(b,9);break;case 1:a.makeMove(b,1);
break;case 2:a.makeMove(b,3);break;case 4:a.makeMove(b,5);break;case 8:a.makeMove(b,9);break;case 10:g==b.x-1?a.makeMove(b,9):g==b.x+1?a.makeMove(b,3):a.makeMove(b,1);break;case 6:f==b.y+1?a.makeMove(b,5):g==b.x+1?a.makeMove(b,6):a.makeMove(b,4);break;case 12:g==b.x-1?a.makeMove(b,3):f==b.y+1?a.makeMove(b,5):a.makeMove(b,4)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(b,1);switch(c.value){case nil:case 16:case 0:a.makeMove(c,4);break;case 5:a.makeMove(c,5);break;case 10:a.makeMove(c,
4);break;case 3:a.makeMove(c,4);break;case 6:a.makeMove(c,6);break;case 12:a.makeMove(c,12);break;case 9:a.makeMove(c,4);break;case 1:a.makeMove(c,5);break;case 2:a.makeMove(c,6);break;case 4:a.makeMove(c,4);break;case 8:a.makeMove(c,12)}(0==b.x&&0==b.y||b.x==a.size.x-1&&b.y==a.size.y-1)&&a.makeMove(c,4)}g=b.x;f=b.y;a.moveTo(c)}}catch(d){throw a.exception(d),d;}};a.dragTo2Alt=function(c,b){try{b.value!=nil&&a.makeMove(b,nil,a.current.color),c.value!=nil&&a.makeMove(c,nil,a.current.color),a.moveTo(c)}catch(d){throw a.exception(d),
d;}};a.valueToString=function(a,b){switch(a){case 16:return b?"x":"-";case 15:return"nsew";case 0:return"o";case 4:return"s";case 1:return"n";case 2:return"e";case 8:return"w";case 3:return"ne";case 9:return"nw";case 6:return"se";case 12:return"sw";case 5:return"ns";case 10:return"ew";default:return"-"}};a.paintCell=function(c){try{var b=a.canvas.getContext("2d");b.fillStyle=a.uic.light[0];b.fillRect(c.px,c.py,a.unit.x,a.unit.y);if(16==c.value)a.paintCircle(c,{stroke:a.uic.dimmed,scale:90});else if(c.value!=
nil){var d=Math.floor((a.unit.x-Math.floor(a.unit.x/4))/2),e=a.unit.x-2*d,f=e+d;b.fillStyle=0==c.color?a.uic.line:a.uic.light[c.color];16!=c.value||a.solved||a.paintCross(c);0==c.value&&b.fillRect(c.px+d,c.py+d,e,e);0!=(c.value&1)&&b.fillRect(c.px+d,c.py,e,f);0!=(c.value&4)&&b.fillRect(c.px+d,c.py+d,e,f);0!=(c.value&2)&&b.fillRect(c.px+d,c.py+d,f,e);0!=(c.value&8)&&b.fillRect(c.px,c.py+d,f,e)}if(c.label!=nil){var g=16==c.value?a.uic.dimmed:a.uic.text;a.paintText(c.label.toString(),c,{color:g,scale:60})}a.paintSymbolMarkers(c);
c.error&&a.display.errors&&(c.label!=nil?a.paintErrorCircle(c):a.paintErrorDot(c))}catch(l){throw a.exception(l),l;}};a.paintCurrentValue=function(){try{var c=a.uie.value,b=c.getContext("2d");b.fillStyle=a.uic.white;b.fillRect(0,0,c.width,c.height);a.current.value!=nil&&(0==a.current.value?a.paintSquare(b,{x:0,y:0,w:c.width,h:c.height,scale:30,stroke:a.uic.none,fill:a.uic.line}):16==a.current.value?a.paintCross(b,{x:0,y:0,w:c.width,h:c.height,stroke:a.uic.cross,fill:a.uic.cross}):a.paintText("#",
b,{x:0,y:0,w:c.width,h:c.height,scale:90,stroke:a.uic.black,fill:a.uic.black}))}catch(d){throw a.exception(d),d;}}}Numbersnake.prototype=new Puzzle;
