function Nurikabe(){var a=this;a.constructor();a.uis.puzzle=["Nurikabe"];var g=a.board.c;rlist=a.rlist;var k=0,l=0,m=0,n=0;a.variant.nurikabe=["nurikabe",["Nurikabe"]];a.variant.std=["std",["Nurikabe"]];a.variant.liar=["liar",["Nurikabe (Liar)"]];a.variant.araf=["araf",["Nurikabe (Araf)"]];a.variant.pairs=["pairs",["Nurikabe (Pairs)"]];a.variant.cipher=["cipher",["Nurikabe (Cipher)"]];a.variant.outside=["outside",["Nurikabe (Outside)"]];var p=nil;a.charToValue=a.charToValue.concat(["a",0,"s",1,"d",
nil,"x",0,"c",1,"v",nil,",",0,".",1,"-",nil,"/",nil]);a.cell.values=[0,1,p];a.enable.dragging=!0;a.enable.pgrid=!0;a.keypad.left=nil;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.setup2=function(){try{if(a.labels.north=a.labels.south=a.labels.east=a.labels.west=0,a.level.nlabels){var b=a.level.nlabels.replace(/\s+/g," ").trim().split(" ");a.labels.west=parseInt(b[0]);a.labels.north=parseInt(b[1]);a.labels.east=parseInt(b[2]);a.labels.south=parseInt(b[3])}}catch(c){throw a.exception(c),
c;}};a.reset2=function(){try{a.variant.init(a.variant.nurikabe,a.variant.std);a.variant.isv(a.variant.std)&&(a.uis.puzzle=a.variant.std[1]);a.variant.isv(a.variant.liar)&&(a.uis.puzzle=a.variant.liar[1]);a.variant.isv(a.variant.araf)&&(a.uis.puzzle=a.variant.araf[1]);a.variant.isv(a.variant.pairs)&&(a.uis.puzzle=a.variant.pairs[1]);a.variant.isv(a.variant.cipher)&&(a.uis.puzzle=a.variant.cipher[1]);a.variant.isv(a.variant.outside)&&(a.uis.puzzle=a.variant.outside[1]);k=a.labels.west;l=a.labels.north;
m=a.size.x-a.labels.east;n=a.size.y-a.labels.south;if(a.level.problem){var b=0;var c=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=l;d<n;d++)for(var e=k;e<m;e++){var h=g[e][d];var f=c[b++];"."!=f&&"-"!=f&&("@"==f?(h.areas=a.cell.outside,h.fixed=!0,h.valid=!1):"x"==f?h.value=0:"o"==f?h.value=1:"?"==f?h.label=0:a.variant.isv(a.variant.cipher)||a.variant.isv(a.variant.liar)?h.clues="a"<=f&&"z">=f?f.charCodeAt(0)+1E3-96:"A"<=f&&"Z">=f?f.charCodeAt(0)+1E3-64:parseInt(f):h.label=parseInt(f));
if(h.label!=nil||0!=h.clues)h.value=1;h.value!=nil&&(h.fixed=!0)}}if(a.level.clabels){b=0;c=a.level.clabels.replace(/\s+/g," ").trim().split(" ");for(d=0;d<a.labels.north;d++)for(e=k;e<m;e++)h=g[e][d],f=c[b++],h.label="-"==f||"."==f?nil:parseInt(f);for(d=a.size.y-a.labels.south;d<a.size.y;d++)for(e=k;e<m;e++)h=g[e][d],f=c[b++],h.label="-"==f||"."==f?nil:parseInt(f)}if(a.level.rlabels){b=0;c=a.level.rlabels.replace(/\s+/g," ").trim().split(" ");for(e=0;e<a.labels.west;e++)for(d=l;d<n;d++)h=g[e][d],
f=c[b++],h.label="-"==f||"."==f?nil:parseInt(f);for(e=a.size.x-a.labels.east;e<a.size.x;e++)for(d=l;d<n;d++)h=g[e][d],f=c[b++],h.label="-"==f||"."==f?nil:parseInt(f)}a.reset2labels();if(a.level.solution)for(b=0,c=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=l;d<n;d++)for(e=k;e<m;e++)h=g[e][d],f=c[b++],h.solution="x"==f?0:1}catch(q){throw a.exception(q),q;}};a.check2=function(){try{for(var b=k;b<m;b++)for(var c=l;c<n;c++)g[b][c].value==nil&&(g[b][c].error=1);for(b=k;b<m-1;b++)for(c=l;c<
n-1;c++)if(0==g[b][c].value){var d=0;0==g[b][c+1].value&&d++;0==g[b+1][c+1].value&&d++;0==g[b+1][c].value&&d++;3==d&&(g[b][c].error=g[b+1][c].error=g[b][c+1].error=g[b+1][c+1].error=4)}rlist.length=0;d=1;for(b=k;b<m;b++)for(c=l;c<n;c++){var e=g[b][c];0==e.value&&0==e.count&&a.markArea(e,d++)}2!=d&&(a.solved=!1);d=1;for(b=k;b<m;b++)for(c=l;c<n;c++)e=g[b][c],1==e.value&&0==e.count&&a.markArea(e,d++);for(d=1;d<rlist.length;d++){b=e=null;for(c=0;c<rlist[d].length;c++)rlist[d][c].label!=nil&&(null==e?
e=rlist[d][c]:null==b?b=rlist[d][c]:e.error=b.error=rlist[d][c].error=3);if(null==e)for(c=0;c<rlist[d].length;c++)rlist[d][c].error=3;else if(a.variant.isv(a.variant.std)&&(null!=b&&(e.error=b.error=3),0!=e.label&&e.label!=rlist[d].length&&(e.error=2)),(a.variant.isv(a.variant.pairs)||a.variant.isv(a.variant.araf))&&null==b)for(c=0;c<rlist[d].length;c++)rlist[d][c].error=3;else a.variant.isv(a.variant.pairs)&&e.label+b.label!=rlist[d].length&&(e.error=2),a.variant.isv(a.variant.araf)&&(rlist[d].length<=
Math.min(e.label,b.label)||rlist[d].length>=Math.max(e.label,b.label))&&(e.error=b.error=2)}}catch(h){throw a.exception(h),h;}};a.solve2=function(){try{if(a.variant.isv(a.variant.std)){for(var b=k;b<m;b++)for(var c=l;c<n;c++)1==g[b][c].label?(a.solveCellDark(b-1,c),a.solveCellDark(b,c-1),a.solveCellDark(b+1,c),a.solveCellDark(b,c+1)):g[b][c].label!=nil&&(b>k+1&&g[b-2][c].label!=nil&&a.solveCellDark(b-1,c),b<m-2&&g[b+2][c].label!=nil&&a.solveCellDark(b+1,c),c>l+1&&g[b][c-1].label!=nil&&a.solveCellDark(b,
c-1),c<n-2&&g[b][c+2].label!=nil&&a.solveCellDark(b,c+1),b>k&&c>l&&g[b-1][c-1].label!=nil&&(a.solveCellDark(b-1,c),a.solveCellDark(b,c-1)),b<m-1&&c<n-1&&g[b+1][c+1].label!=nil&&(a.solveCellDark(b+1,c),a.solveCellDark(b,c+1)),b<m-1&&c>l&&g[b+1][c-1].label!=nil&&(a.solveCellDark(b+1,c),a.solveCellDark(b,c-1)),b>k&&c<n-1&&g[b-1][c+1].label!=nil&&(a.solveCellDark(b-1,c),a.solveCellDark(b,c+1)));a.pushEvent(a.moves.typeSolve,0);a.check()}}catch(d){throw a.exception(d),d;}};a.solveCellDark=function(b,c){try{b>=
k&&b<m&&c>=l&&c<n&&(g[b][c].value=0,g[b][c].color=a.current.color)}catch(d){throw a.exception(d),d;}};a.cleanSolution=function(){for(var a=k;a<m;a++)for(var c=l;c<n;c++){var d=g[a][c];d.value==nil&&(d.value=1)}};a.valueToString=function(a,c){switch(a){case nil:return"-";case 0:return"x";case 1:return c?".":"-";default:return"%"}};a.labelToString=function(a,c){try{return a==nil?"-":0==a?"?":parseInt(a)}catch(d){return ojdebug(d.toString()),"%"}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):
a.paintValueCell(b)}catch(c){throw a.exception(c),c;}};a.paintLabelCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.label;c.fillRect(b.px,b.py,a.unit.x,a.unit.y);b.label!=nil&&a.paintText(b.label.toString(),b)}catch(d){throw a.exception(d),d;}};a.paintValueCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=b.value==nil?a.paintToImage&&a.moves.current==nil?a.uic.white:a.uic.gray:1==b.value?a.uic.light[b.color]:!a.solved&&a.display.errors?a.uic.dark[(b.count-1)%10]:
a.uic.dark[b.color];c.fillRect(b.px,b.py,a.unit.x,a.unit.y);if(0<b.clues){c.textAlign="left";c.textBaseline="top";c.font=Math.floor(40*a.unit.x/100).toString()+"px sans-serif";c.fillStyle=a.uic.text;var d=1E3<=b.clues?String.fromCharCode(b.clues-1E3+64):b.clues.toString();c.fillText(d,b.px+4,b.py+4)}0==b.label?a.paintText("?",b):b.label!=nil&&a.paintText(b.label.toString(),b);a.paintSymbolMarkers(b);b.error&&a.display.errors&&(b.label!=nil||0!=b.clues?a.paintErrorCircle(b):a.paintErrorDot(b))}catch(e){throw a.exception(e),
e;}};a.paintCurrentValue=function(){try{var b=a.uie.value,c=b.getContext("2d");c.fillStyle=a.current.value==p?a.uic.gray:0==a.current.value?a.uic.black:a.uic.white;c.fillRect(0,0,b.width,b.height)}catch(d){throw a.exception(d),d;}}}Nurikabe.prototype=new Puzzle;
