function Rectangles(){var a=this;a.constructor();a.uis.puzzle=["Rectangles","Rechtecke"];var h=a.board.c,w=a.board.h,q=a.board.v,g=a.alist,r=0,t=0,k=0,n=0;a.variant.generic=["generic",["Rectangles","Rechtecke"]];a.variant.firumatto=["firumatto",["Firumatto"]];a.variant.kapetto=["kapetto",["Kapetto"]];a.variant.meadows=["meadows",["Meadows","Kuhweide"]];a.variant.nawabari=["nawabari",["Nawabari"]];a.variant.rekuto=["rekuto",["Rekuto"]];a.variant.sikaku=["sikaku",["Shikaku","Sikaku"]];a.variant.tatamibari=
["tatamibari",["Tatamibari"]];a.variant.usotatami=["usotatami",["Usotatami"]];var H=nil-1,E=nil-2,A=nil-3,C=nil-4,D=nil-5,u=null,x=null;a.line.values=[a.line.wall,a.line.cross,a.line.grid];a.enable.dragging=!0;a.enable.cells=!0;a.enable.lines=!a.config.touch;a.keypad.left=nil;a.moves.collapse=!1;a.uic.area="#cccccc";a.uic.temp="#ffdddd";a.uic.work="#99cc99";a.uic.circleedge="#000000";a.uic.circlefill="#cccccc";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.setup2=function(){try{a.labels.north=
a.labels.south=a.labels.east=a.labels.west=0;if(a.level.nlabels){var b=a.level.nlabels.replace(/\s+/g," ").trim().split(" ");a.labels.west=parseInt(b[0]);a.labels.north=parseInt(b[1]);a.labels.east=parseInt(b[2]);a.labels.south=parseInt(b[3])}a.level.image&&(a.enable.pgrid=a.enable.pframe=!1)}catch(c){throw a.exception(c),c;}};a.reset2=function(){try{u=null;!a.level.puzzle&&a.level.variant&&(a.level.puzzle=a.level.variant);a.variant.init(a.variant.sikaku);r=a.labels.west;t=a.labels.north;k=a.size.x-
a.labels.east;n=a.size.y-a.labels.south;if(a.level.problem){var b=0;var c=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=t;d<n;d++)for(var f=r;f<k;f++){var l=h[f][d];var e=c[b++];l.label="-"==e?nil:"x"==e?H:"o"==e?1:"#"==e?E:"s"==e||"|"==e?D:"h"==e||"-"==e?A:"v"==e||"|"==e?C:parseInt(e)}}if(a.level.solution){b=0;c=a.level.solution.replace(/\s+/g," ").trim().split(" ");for(d=t;d<n;d++)for(f=r;f<k;f++)l=h[f][d],e=c[b++],l.work="."==e||"-"==e?nil:parseInt(e);e=1;for(f=r;f<k;f++)for(d=
t;d<n;d++)if(l=h[f][d],l.work!=nil){var g=l.work;for(c=r;c<k;c++)for(b=t;b<n;b++){var v=h[c][b];v.work==g&&(v.solution=e,v.work=nil)}e++}}a.level.lines&&a.reset2lines(r,t,k,n,a.level.lines);for(f=r;f<k;f++)w[f][t].valid=w[f][n].valid=!1;for(d=t;d<n;d++)q[r][d].valid=q[k][d].valid=!1}catch(p){throw a.exception(p),p;}};a.check2=function(){try{for(var b=1,c=r;c<k;c++)for(var d=t;d<n;d++){var f=h[c][d];0==f.count&&f.value!=nil&&f.label!=E&&a.markArea(c,d,b++)}g.length=0;for(c=r;c<k;c++)for(d=t;d<n;d++){f=
h[c][d];var l=f.value==nil?0:f.count;g[l]||(g[l]=[]);g[l][g[l].length]=f}if(null!=g[0])for(var e=0;e<g[0].length;e++)a.variant.is(a.variant.kapetto)||(g[0][e].error=1),g[0][e].label!=nil&&(g[0][e].error=2);for(b=1;b<g.length;b++){var m=g[b][g[b].length-1].x-g[b][0].x+1,v=g[b][g[b].length-1].y-g[b][0].y+1;l=m*v;if(l!=g[b].length)for(e=0;e<g[b].length;e++)g[b][e].error=7;else{var p=null;for(e=0;e<g[b].length;e++)f=g[b][e],f.label!=nil&&(null!=p&&(p.error=f.error=2),p=f);if(a.variant.is(a.variant.firumatto)||
null!=p){(a.variant.is(a.variant.tatamibari)||a.variant.is(a.variant.usotatami)||a.variant.is(a.variant.firumatto))&&a.check2tatami();a.variant.is(a.variant.tatamibari)&&(p.label==D&&v!=m&&(p.error=10),p.label==A&&m<=v&&(p.error=10),p.label==C&&v<=m&&(p.error=10));if((a.variant.is(a.variant.sikaku)||a.variant.is(a.variant.kapetto)||a.variant.is(a.variant.firumatto))&&null!=p&&l!=p.label)for(e=0;e<g[b].length;e++)g[b][e].error=8;if(a.variant.is(a.variant.usotatami)&&null!=p&&l==p.label)for(e=0;e<g[b].length;e++)g[b][e].error=
8;if(a.variant.is(a.variant.rekuto)&&null!=p&&m+v!=p.label)for(e=0;e<g[b].length;e++)g[b][e].error=8;if(a.variant.is(a.variant.meadows)&&v!=m)for(e=0;e<g[b].length;e++)g[b][e].error=5;if((a.variant.is(a.variant.firumatto)||a.variant.is(a.variant.usotatami))&&1!=m&&1!=v)for(e=0;e<g[b].length;e++)g[b][e].error=6;if(a.variant.is(a.variant.firumatto)&&(4<m||4<v))for(e=0;e<g[b].length;e++)g[b][e].error=6}else for(e=0;e<g[b].length;e++)g[b][e].error=2}}for(c=0;c<k;c++)for(d=1;d<n;d++)w[c][d].value==a.line.wall&&
h[c][d-1].count==h[c][d].count&&(w[c][d].error=9);for(c=1;c<k;c++)for(d=0;d<n;d++)q[c][d].value==a.line.wall&&h[c-1][d].count==h[c][d].count&&(q[c][d].error=9);a.variant.is(a.variant.nawabari)&&a.check2nawabari();a.variant.is(a.variant.firumatto)&&a.check2firumatto()}catch(F){throw a.exception(F),F;}};a.check2tatami=function(){try{if(null!=g[0])for(var b=0;b<g[0].length;b++)g[0][b].work=nil;for(var c=1;c<g.length;c++)for(b=0;b<g[c].length;b++)g[c][b].work=g[c].length;for(b=r;b<k-1;b++)for(c=t;c<n-
1;c++){var d=h[b][c],f=h[b+1][c],l=h[b][c+1],e=h[b+1][c+1],m=[];d.value!=nil&&-1==m.indexOf(d.value)&&(m[m.length]=d.value);f.value!=nil&&-1==m.indexOf(f.value)&&(m[m.length]=f.value);l.value!=nil&&-1==m.indexOf(l.value)&&(m[m.length]=l.value);e.value!=nil&&-1==m.indexOf(e.value)&&(m[m.length]=e.value);4==m.length&&(d.error=f.error=l.error=e.error=4)}}catch(v){throw a.exception(v),v;}};a.check2firumatto=function(){try{for(var b=r;b<k;b++)for(var c=t;c<n;c++){var d=h[b][c];if(b<k-1){var f=h[b+1][c];
d.value!=f.value&&d.work==f.work&&(d.error=f.error=4)}if(c<n-1){var l=h[b][c+1];d.value!=l.value&&d.work==l.work&&(d.error=l.error=4)}}}catch(e){throw a.exception(e),e;}};a.check2nawabari=function(){try{for(var b=r;b<k;b++)for(var c=t;c<n;c++)if(h[b][c].label!=nil){var d=0;0!=b&&q[b][c].value!=a.line.wall||d++;0!=c&&w[b][c].value!=a.line.wall||d++;b!=k-1&&q[b+1][c].value!=a.line.wall||d++;c!=n-1&&w[b][c+1].value!=a.line.wall||d++;d!=h[b][c].label&&(h[b][c].error=3)}}catch(f){throw a.exception(f),
f;}};a.markArea=function(b,c,d){try{h[b][c].count=d,0!=b&&0==h[b-1][c].count&&q[b][c].value!=a.line.wall&&a.markArea(b-1,c,d),b!=k-1&&0==h[b+1][c].count&&q[b+1][c].value!=a.line.wall&&a.markArea(b+1,c,d),0!=c&&0==h[b][c-1].count&&w[b][c].value!=a.line.wall&&a.markArea(b,c-1,d),c!=n-1&&0==h[b][c+1].count&&w[b][c+1].value!=a.line.wall&&a.markArea(b,c+1,d)}catch(f){throw a.exception(f),f;}};a.solve2=function(){try{a.variant.is(a.variant.firumatto)&&a.solve2firumatto()}catch(b){throw a.exception(b),b;
}};a.solve2firumatto=function(){try{for(var b=r;b<k;b++)for(var c=t;c<n;c++){var d=h[b][c];d.label!=nil&&(1==d.label?(d.value=b*k+c,w[b][c].value=q[b][c].value=w[b][c+1].value=q[b+1][c].value=a.line.wall):b<k-1&&h[b+1][c].label!=nil?q[b+1][c].value=a.line.wall:c<n-1&&h[b][c+1].label!=nil&&(w[b][c+1].value=a.line.wall))}}catch(f){throw a.exception(f),f;}};a.isNewSolution=function(){try{if(null==a.level.solution)return!0;for(var b=!0,c=r;c<k;c++)for(var d=t;d<n;d++)for(var f=h[c][d],l=r;l<k;l++)for(var e=
t;e<n;e++){var g=h[l][e];if(g.value==f.value&&g.solution!=f.solution||g.value!=f.value&&g.solution==f.solution)b=!1}return!b}catch(v){throw a.exception(v),v;}};a.cleanSolution=function(){if(!(2>g.length))for(var a=1;a<g.length;a++)for(var c=0;c<g[a].length;c++)g[a][c].value=a};a.makeMove2=function(b,c,d){var f,g;try{if(b.type!=a.item.cell)Object.getPrototypeOf(this).makeMove2.call(this,b,c,d),u=x=null;else if(c!=b.value)if(c==nil)a.deleteArea(b.value),a.pushMove(b),a.updateLines();else if(void 0!==
c&&null!=c&&(u=h[Math.floor(c/n)][c%n]),null==u)u=x=b;else{var e=Math.min(u.x,b.x),m=Math.max(u.x,b.x),k=Math.min(u.y,b.y),p=Math.max(u.y,b.y);u=null;if(h[e][k].value!=nil){var w=g=1E5;var q=f=-1;var A=h[e][k].value;for(b=r;b<=m;b++)for(var z=t;z<=p;z++)h[b][z].value==A&&(b<g&&(g=b),z<w&&(w=z),b>f&&(f=b),z>q&&(q=z))}if(h[e][k].value!=nil&&e==g&&k==w&&m==f&&p==q)a.pushMove(h[m][p]),a.deleteArea(h[e][k].value);else{if(void 0===d||null==d)d=a.current.color;for(q=e;q<=m;q++)for(var y=k;y<=p;y++)h[q][y].value!=
nil&&a.deleteArea(h[q][y].value);for(q=e;q<=m;q++)for(y=k;y<=p;y++){var B=h[q][y];c==nil?(B.value=nil,B.color=0):(B.value=e*n+k,B.color=d)}a.pushMove(h[m][p])}a.updateLines()}}catch(G){throw a.exception(G),G;}};a.deleteArea=function(b){try{for(var c=r;c<k;c++)for(var d=t;d<n;d++){var f=h[c][d];f.value==b&&(f.value=nil,f.color=0)}}catch(l){throw a.exception(l),l;}};a.updateLines=function(){try{for(var b=r;b<k;b++)for(var c=t;c<n;c++){if(c<n-1){var d=h[b][c];var f=h[b][c+1];var g=w[b][c+1];d.areas<=
a.cell.outside&&f.areas<=a.cell.outside?g.value=a.line.cross:d.value!=f.value?g.value=a.line.wall:d.value!=nil&&f.value!=nil&&(g.value=a.line.grid)}if(b<k-1){d=h[b][c];f=h[b+1][c];var e=q[b+1][c];d.areas<=a.cell.outside&&f.areas<=a.cell.outside?e.value=a.line.cross:d.value!=f.value?e.value=a.line.wall:d.value!=nil&&f.value!=nil&&(e.value=a.line.grid)}}}catch(m){throw a.exception(m),m;}};a.dragStart=function(b,c,d){try{u=x=c,Object.getPrototypeOf(this).dragStart.call(this,b,c,d)}catch(f){throw a.exception(f),
f;}};a.dragTo2=function(b,c,d){try{!u||u.type==a.item.cell&&b.type!=a.item.cell||u.type>a.item.line&&b.type<=a.item.line||(x=b,b.type==a.item.cell?a.moveTo(b):Object.getPrototypeOf(this).dragTo2.call(this,b,c,d))}catch(f){throw a.exception(f),f;}};a.dragEnd=function(){try{Object.getPrototypeOf(this).dragEnd.call(this),x&&x.type==a.item.cell&&a.makeMove(x),u=x=null}catch(b){throw a.exception(b),b;}};a.showSolution2=function(){try{for(var b=r;b<k;b++)for(var c=t;c<n;c++){var d=h[b][c];d.value=d.solution;
d.color=a.current.color}a.updateLines()}catch(f){throw a.exception(f),f;}};a.showHint2=function(b){try{if(b&&b.type==a.item.cell){for(var c=null,d=null,f=r;f<k;f++)for(var g=t;g<n;g++){var e=h[f][g];e.solution==b.solution&&(null==c&&(c=e),d=e)}u=c;a.makeMove2(d)}}catch(m){throw a.exception(m),m;}};a.acceptColor2=function(b){try{for(var c=r;c<k;c++)for(var d=t;d<n;d++){var f=h[c][d];f.color==b&&(f.color=0)}a.updateLines()}catch(l){throw a.exception(l),l;}};a.rejectColor2=function(b){try{for(var c=
r;c<k;c++)for(var d=t;d<n;d++){var f=h[c][d];f.color==b&&(f.value=nil,f.color=0)}a.updateLines()}catch(l){throw a.exception(l),l;}};a.onValues=function(){try{a.config.touch?a.enable.lines?(a.enable.lines=!1,a.enable.cells=!0):(a.enable.lines=!0,a.enable.cells=!1):Object.getPrototypeOf(this).onValues.call(this)}catch(b){throw a.exception(b),b;}};a.paintCell=function(b){try{var c=a.canvas.getContext("2d");if(null!=u&&null!=x&&u.type==a.item.cell){var d=Math.min(u.x,x.x);var f=Math.max(u.x,x.x);var g=
Math.min(u.y,x.y);var e=Math.max(u.y,x.y)}a.level.image||(null!=u&&null!=x&&b.x>=d&&b.x<=f&&b.y>=g&&b.y<=e?c.fillStyle=a.uic.work:b.value==nil?c.fillStyle=a.uic.light[0]:b.error?c.fillStyle=a.uic.temp:a.solved&&a.paintToImage&&!a.variant.is(a.variant.kapetto)?c.fillStyle=a.uic.light[0]:c.fillStyle=a.uic.area,c.fillRect(b.px,b.py,a.unit.x,a.unit.y));if(b.label!=nil)if(a.variant.is(a.variant.meadows))a.paintCircle(b,{scale:50,fill:a.uic.circlefill,stroke:a.uic.circleedge});else if(a.variant.is(a.variant.nawabari)||
a.variant.is(a.variant.usotatami)||a.variant.is(a.variant.firumatto))a.paintText(b.label.toString(),b,{color:a.uic.text});else if(a.variant.is(a.variant.tatamibari))b.label==D&&a.paintText("+",b,{color:a.uic.text}),b.label==A&&a.paintText("\u2014",b,{color:a.uic.text}),b.label==C&&a.paintText("|",b,{color:a.uic.text});else{e={};e.stroke=b.error&&a.display.errors?e.fill=a.uic.error:e.fill=a.uic.text;a.paintCircle(b,e);var h=b.label.toString();a.paintText(h,b,{color:a.uic.text2,scale:1==h.length?70:
50})}a.paintSymbolMarkers(b);b.error&&a.display.errors&&(b.label==nil?a.paintErrorDot(b):a.variant.is(a.variant.nawabari)&&a.paintErrorCircle(b))}catch(v){throw a.exception(v),v;}};a.paintCurrentValue=function(){try{var b=a.uie.value,c=b.getContext("2d");c.fillStyle=a.uic.white;c.fillRect(0,0,b.width,b.height);a.enable.lines&&!a.enable.cells&&a.paintText("#",c,{x:0,y:0,w:b.width,h:b.height,scale:90})}catch(d){throw a.exception(d),d;}}}Rectangles.prototype=new Puzzle;
