function Seeknum(){var a=this;a.constructor();a.uis.puzzle=["Trace Numbers"];var g=nil,e=nil;a.charToValue=a.charToValue.concat([",",nil,"x",nil,"-",nil,"/",nil,".",nil]);a.enable.dragging=!0;a.enable.pgrid=!0;a.enable.values=!1;a.enable.currentValue=!1;a.keypad.left=nil;a.uic.line="#aaaaaa";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{if(a.level.problem){var b=0;var c=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=0;d<a.size.y;d++)for(var f=0;f<
a.size.x;f++){var g=a.board.c[f][d];var h=c[b++];g.label="."==h||"-"==h?nil:"s"==h||"S"==h?-2:"g"==h||"G"==h?-3:parseInt(h)}}if(a.level.solution)for(b=0,c=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=0;d<a.size.y;d++)for(f=0;f<a.size.x;f++)if(g=a.board.c[f][d],h=c[b++],"-"==h||"."==h)g.solution=nil;else{var e=0;h.contains("n")&&(e|=1);h.contains("s")&&(e|=4);if(h.contains("e")||h.contains("o"))e|=2;h.contains("w")&&(e|=8);0!=e&&(g.solution=e)}}catch(n){throw a.exception(n),n;}};a.check2=
function(){try{for(var b=1,c=0;c<a.size.x;c++)for(var d=0;d<a.size.y;d++){var f=a.board.c[c][d];-2==f.label&&a.checkPath(f,null,b++)}for(c=0;c<a.size.x;c++)for(d=0;d<a.size.y;d++)f=a.board.c[c][d],f.value!=nil&&0==f.count&&(a.board.c[c][d].error=1);for(c=0;c<a.size.x;c++)for(d=0;d<a.size.y;d++)f=a.board.c[c][d],f.value==nil&&(f.error=2)}catch(m){throw a.exception(m),m;}};var k=0,l=null;a.checkPath=function(b,c,d){try{b.value==nil&&(b.error=2),0!=b.count&&(b.error=1),b.count=d,-2==b.label&&(k=0,l=
b),-2!=b.label&&-3!=b.label||1==b.value||4==b.value||2==b.value||8==b.value||(b.error=1),1!=b.value&&4!=b.value&&2!=b.value&&8!=b.value||-2==b.label||-3==b.label||(b.error=1),c&&(b.x-1==c.x&&0==(b.value&8)&&(b.error=1),b.x+1==c.x&&0==(b.value&2)&&(b.error=1),b.y-1==c.y&&0==(b.value&1)&&(b.error=1),b.y+1==c.y&&0==(b.value&4)&&(b.error=1)),b.error||(b.label!=nil||3!=b.value&&6!=b.value&&9!=b.value&&12!=b.value||k--,b.label!=nil&&-2!=b.label&&(0!=k&&(l.error=1),k=b.label,l=b),0!=(b.value&8)&&(0==b.x?
checkPathError=!0:(null==c||c.x!=b.x-1)&&a.checkPath(a.board.c[b.x-1][b.y],b,d)),0!=(b.value&2)&&(b.x==a.size.x-1?checkPathError=!0:(null==c||c.x!=b.x+1)&&a.checkPath(a.board.c[b.x+1][b.y],b,d)),0!=(b.value&1)&&(0==b.y?checkPathError=!0:(null==c||c.y!=b.y-1)&&a.checkPath(a.board.c[b.x][b.y-1],b,d)),0!=(b.value&4)&&(b.y==a.size.y-1?checkPathError=!0:(null==c||c.y!=b.y+1)&&a.checkPath(a.board.c[b.x][b.y+1],b,d)))}catch(f){throw a.exception(f),f;}};a.dragTo2=function(b,c){try{if(!b.fixed&&b.areas!=a.cell.outside){if(b.x==
c.x-1&&c.y==b.y){switch(c.value){case nil:case 16:case 0:a.makeMove(c,8);break;case 10:a.makeMove(c,10);break;case 12:a.makeMove(c,12);break;case 9:a.makeMove(c,9);break;case 1:a.makeMove(c,9);break;case 2:a.makeMove(c,10);break;case 4:a.makeMove(c,12);break;case 8:a.makeMove(c,8);break;case 5:e==c.y-1?a.makeMove(c,9):e==c.y+1?a.makeMove(c,12):a.makeMove(c,8);break;case 3:e==c.y-1?a.makeMove(c,9):g==c.x+1?a.makeMove(c,10):a.makeMove(c,8);break;case 6:e==c.y+1?a.makeMove(c,12):g==c.x+1?a.makeMove(c,
10):a.makeMove(c,8)}-3==c.label&&a.makeMove(c,8);switch(b.value){case nil:case 16:case 0:a.makeMove(b,2);break;case 5:a.makeMove(b,2);break;case 10:a.makeMove(b,10);break;case 3:a.makeMove(b,3);break;case 6:a.makeMove(b,6);break;case 12:a.makeMove(b,2);break;case 9:a.makeMove(b,2);break;case 1:a.makeMove(b,3);break;case 2:a.makeMove(b,2);break;case 4:a.makeMove(b,6);break;case 8:a.makeMove(b,10)}b.label!=nil&&a.makeMove(b,2)}if(b.x==c.x+1&&c.y==b.y){switch(c.value){case nil:case 16:case 0:a.makeMove(c,
2);break;case 10:a.makeMove(c,10);break;case 3:a.makeMove(c,3);break;case 6:a.makeMove(c,6);break;case 1:a.makeMove(c,3);break;case 2:a.makeMove(c,2);break;case 4:a.makeMove(c,6);break;case 8:a.makeMove(c,10);break;case 5:e==c.y-1?a.makeMove(c,3):e==c.y+1?a.makeMove(c,6):a.makeMove(c,2);break;case 12:g==c.x-1?a.makeMove(c,10):e==c.y+1?a.makeMove(c,6):a.makeMove(c,2);break;case 9:e==c.y-1?a.makeMove(c,3):g==c.x-1?a.makeMove(c,10):a.makeMove(c,2)}-3==c.label&&a.makeMove(c,2);switch(b.value){case nil:case 16:case 0:a.makeMove(b,
8);break;case 5:a.makeMove(b,8);break;case 10:a.makeMove(b,10);break;case 3:a.makeMove(b,8);break;case 6:a.makeMove(b,8);break;case 12:a.makeMove(b,12);break;case 9:a.makeMove(b,9);break;case 1:a.makeMove(b,9);break;case 2:a.makeMove(b,10);break;case 4:a.makeMove(b,12);break;case 8:a.makeMove(b,8)}b.label!=nil&&a.makeMove(b,8)}if(b.y==c.y+1&&c.x==b.x){switch(c.value){case nil:case 16:case 0:a.makeMove(c,4);break;case 6:a.makeMove(c,6);break;case 12:a.makeMove(c,12);break;case 1:a.makeMove(c,5);break;
case 2:a.makeMove(c,6);break;case 4:a.makeMove(c,4);break;case 8:a.makeMove(c,12);break;case 5:a.makeMove(c,5);break;case 10:g==c.x-1?a.makeMove(c,12):g==c.x+1?a.makeMove(c,6):a.makeMove(c,4);break;case 3:e==c.y-1?a.makeMove(c,5):g==c.x+1?a.makeMove(c,6):a.makeMove(c,4);break;case 9:g==c.x-1?a.makeMove(c,12):e==c.y-1?a.makeMove(c,5):a.makeMove(c,4)}-3==c.label&&a.makeMove(c,4);switch(b.value){case nil:case 16:case 0:a.makeMove(b,1);break;case 5:a.makeMove(b,5);break;case 10:a.makeMove(b,1);break;
case 3:a.makeMove(b,3);break;case 6:a.makeMove(b,1);break;case 12:a.makeMove(b,1);break;case 9:a.makeMove(b,9);break;case 1:a.makeMove(b,1);break;case 2:a.makeMove(b,3);break;case 4:a.makeMove(b,5);break;case 8:a.makeMove(b,9)}b.label!=nil&&a.makeMove(b,1)}if(b.y==c.y-1&&c.x==b.x){switch(c.value){case nil:case 16:case 0:a.makeMove(c,1);break;case 5:a.makeMove(c,5);break;case 3:a.makeMove(c,3);break;case 9:a.makeMove(c,9);break;case 1:a.makeMove(c,1);break;case 2:a.makeMove(c,3);break;case 4:a.makeMove(c,
5);break;case 8:a.makeMove(c,9);break;case 10:g==c.x-1?a.makeMove(c,9):g==c.x+1?a.makeMove(c,3):a.makeMove(c,1);break;case 6:e==c.y+1?a.makeMove(c,5):g==c.x+1?a.makeMove(c,6):a.makeMove(c,4);break;case 12:g==c.x-1?a.makeMove(c,3):e==c.y+1?a.makeMove(c,5):a.makeMove(c,4)}-3==c.label&&a.makeMove(c,1);switch(b.value){case nil:case 16:case 0:a.makeMove(b,4);break;case 5:a.makeMove(b,5);break;case 10:a.makeMove(b,4);break;case 3:a.makeMove(b,4);break;case 6:a.makeMove(b,6);break;case 12:a.makeMove(b,12);
break;case 9:a.makeMove(b,4);break;case 1:a.makeMove(b,5);break;case 2:a.makeMove(b,6);break;case 4:a.makeMove(b,4);break;case 8:a.makeMove(b,12)}-3==c.label&&a.makeMove(b,4)}g=c.x;e=c.y;a.moveTo(b)}}catch(d){throw a.exception(d),d;}};a.dragTo2Alt=function(b,c){try{c.value!=nil&&a.makeMove(c,nil,a.current.color),b.value!=nil&&a.makeMove(b,nil,a.current.color),a.moveTo(b)}catch(d){throw a.exception(d),d;}};a.valueToString=function(a,c){switch(a){case 16:return c?"x":"-";case 15:return"nsew";case 0:return"o";
case 4:return"s";case 1:return"n";case 2:return"e";case 8:return"w";case 3:return"ne";case 9:return"nw";case 6:return"se";case 12:return"sw";case 5:return"ns";case 10:return"ew";default:return"-"}};a.paintCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.light[0];c.fillRect(b.px,b.py,a.unit.x,a.unit.y);if(b.value!=nil){var d=Math.floor((a.unit.x-Math.floor(a.unit.x/4))/2),f=a.unit.x-2*d,e=f+d;c.fillStyle=0==b.color?a.uic.line:a.uic.light[b.color];0!=(b.value&1)&&c.fillRect(b.px+
d,b.py,f,e);0!=(b.value&4)&&c.fillRect(b.px+d,b.py+d,f,e);0!=(b.value&2)&&c.fillRect(b.px+d,b.py+d,e,f);0!=(b.value&8)&&c.fillRect(b.px,b.py+d,e,f)}-2==b.label?(a.paintCircle(b,{fill:a.uic.white,stroke:a.uic.black,scale:80}),a.paintText("0",b)):-3==b.label?(c.strokeStyle=a.uic.black,c.fillStyle=a.uic.black,a.paintCircle(b,{fill:a.uic.black,stroke:a.uic.black,scale:80})):b.label!=nil&&(c.fillStyle=c.strokeStyle=a.uic.line,a.paintCircle(b,{fill:a.uic.line,stroke:a.uic.line,scale:80}),a.paintText(b.label.toString(),
b));a.paintSymbolMarkers(b);b.error&&a.display.errors&&(b.label!=nil?a.paintErrorCircle(b):a.paintErrorDot(b))}catch(h){throw a.exception(h),h;}}}Seeknum.prototype=new Puzzle;
