function Shakashaka(){var a=this;a.constructor();a.uis.puzzle=["Shakashaka"];a.charToValue=a.charToValue.concat(["a",1,"s",0,"d",nil,".",1,",",0,"-",nil,"o",1,"x",0,"/",nil,"0",nil,"7",18,"8",0,"9",6,"6",nil,"5",1,"4",nil,"1",24,"2",0,"3",12]);a.cell.values=[1,6,12,24,18,0,nil];a.keypadValues=[["\u25e4",18],["\u25e5",6],["o",1],["X",0],["\u25e3",24],["\u25e2",12],["\u2022",nil]];a.enable.pgrid=!0;a.keypad.left=nil;a.keypad.right=a.keypad.values;a.cell.nilalias=0;a.uic.corner="#333333";a.init=function(){Object.getPrototypeOf(a).init.call(a)};
a.reset2=function(){try{if(a.level.problem){var c=0;var b=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var e=0;e<a.size.y;e++)for(var d=0;d<a.size.x;d++){var g=a.board.c[d][e];var f=b[c++];g.label="."==f||"-"==f?nil:"x"==f?5:parseInt(f);g.label!=nil&&(g.fixed=!0)}}if(a.level.solution)for(c=0,b=a.level.solution.replace(/\s+/g," ").trim().split(" "),e=0;e<a.size.y;e++)for(d=0;d<a.size.x;d++)g=a.board.c[d][e],f=b[c++],g.solution="-"==f||"."==f?nil:"ne"==f?6:"se"==f?12:"nw"==f?18:"sw"==f?
24:nil}catch(h){throw a.exception(h),h;}};a.check2=function(){try{for(var c=0;c<a.size.y;c++)for(var b=0;b<a.size.x;b++)a.board.c[b][c].errnum=0;for(c=0;c<a.size.y;c++)for(b=0;b<a.size.x;b++)if(0<=a.board.c[b][c].label&&4>=a.board.c[b][c].label){var e=0;0<b&&(12==a.board.c[b-1][c].value||6==a.board.c[b-1][c].value)&&e++;b<a.size.x-1&&(24==a.board.c[b+1][c].value||18==a.board.c[b+1][c].value)&&e++;0<c&&(12==a.board.c[b][c-1].value||24==a.board.c[b][c-1].value)&&e++;c<a.size.y-1&&(6==a.board.c[b][c+
1].value||18==a.board.c[b][c+1].value)&&e++;e!=a.board.c[b][c].label&&(a.board.c[b][c].error=2)}for(c=0;c<a.size.y;c++)for(b=0;b<a.size.x;b++){var d=a.board.c[b][c];d.label!=nil&&(d.value=30)}for(c=0;c<a.size.y;c++)for(b=0;b<a.size.x;b++)d=a.board.c[b][c],d.checked||18!=d.value||a.checkSlantedSquare(b,c);for(c=0;c<a.size.y;c++)for(b=0;b<a.size.x;b++)d=a.board.c[b][c],!d.checked&&1>d.value&&a.checkOrthoSquare(b,c);for(c=0;c<a.size.y;c++)for(b=0;b<a.size.x;b++)d=a.board.c[b][c],d.label!=nil&&(d.value=
nil);for(b=0;b<a.size.x;b++)for(c=0;c<a.size.y;c++)d=a.board.c[b][c],d.checked||d.label!=nil||(d.error=1)}catch(g){throw a.exception(g),g;}};a.checkOrthoSquare=function(c,b){try{var e=c;for(a.board.c[e][b].checked=!0;e<a.size.x-1&&1>a.board.c[e+1][b].value;)e++,a.board.c[e][b].checked=!0;var d=b;for(a.board.c[c][d].checked=!0;d<a.size.y-1&&1>a.board.c[c][d+1].value;)d++,a.board.c[c][d].checked=!0;for(var g=c;g<=e;g++)for(var f=b;f<=d;f++)1<=a.board.c[g][f].value&&(a.solved=!1,a.markWhiteArea(c,b)),
1>a.board.c[g][f].value&&(a.board.c[g][f].checked=!0);for(g=c;g<=e;g++)0<b&&(a.board.c[g][b-1].value==nil||0==(a.board.c[g][b-1].value&8))&&(a.solved=!1,a.markWhiteArea(c,b)),d<a.size.y-1&&(a.board.c[g][d+1].value==nil||0==(a.board.c[g][d+1].value&2))&&(a.solved=!1,a.markWhiteArea(c,b));for(f=b;f<=d;f++)0<c&&(a.board.c[c-1][f].value==nil||0==(a.board.c[c-1][f].value&4))&&(a.solved=!1,a.markWhiteArea(c,b)),e<a.size.x-1&&(a.board.c[e+1][f].value==nil||0==(a.board.c[e+1][f].value&16))&&(a.solved=!1,
a.markWhiteArea(c,b))}catch(h){throw a.exception(h),h;}};a.checkSlantedSquare=function(c,b){try{a.board.c[c][b].marked=!0;for(var e=c,d=b;0<e&&d<a.size.y-1&&18==a.board.c[e-1][d+1].value;)e--,d++,a.board.c[e][d].marked=!0;if(c==a.size.x-1||6!=a.board.c[c+1][b].value)a.board.c[c][b].error=1;else{var g=c+1,f=b;for(a.board.c[g][f].marked=!0;g<a.size.x-1&&f<a.size.y-1&&6==a.board.c[g+1][f+1].value;)g++,f++,a.board.c[g][f].marked=!0;if(d==a.size.y-1||24!=a.board.c[e][d+1].value)a.board.c[c][b].error=1;
else{var h=e;d+=1;for(a.board.c[h][d].marked=!0;h<a.size.x-1&&d<a.size.y-1&&24==a.board.c[h+1][d+1].value;)h++,d++,a.board.c[h][d].marked=!0;if(f==a.size.y-1||12!=a.board.c[g][f+1].value)a.board.c[c][b].error=1;else{var k=g;f+=1;for(a.board.c[k][f].marked=!0;0<k&&f<a.size.y-1&&12==a.board.c[k-1][f+1].value;)k--,f++,a.board.c[k][f].marked=!0;if(k!=h+1||f!=d)a.board.c[c][b].error=1;else for(c=!1;e<=g;e++)for(h=b;h<=d;h++){var l=a.board.c[e][h];l.marked?(c=!c,l.checked=!0,l.marked=!1):c&&(1<=l.value&&
(l.error=1),l.checked=!0)}}}}}catch(m){throw a.exception(m),m;}};a.markWhiteArea=function(c,b){try{var e=a.board.c[c][b];e.errnum=1;e.error=1;0<c&&1!=a.board.c[c-1][b].errnum&&1>a.board.c[c-1][b].value&&a.markWhiteArea(c-1,b);0<b&&1!=a.board.c[c][b-1].errnum&&1>a.board.c[c][b-1].value&&a.markWhiteArea(c,b-1);c<a.size.x-1&&1!=a.board.c[c+1][b].errnum&&1>a.board.c[c+1][b].value&&a.markWhiteArea(c+1,b);b<a.size.y-1&&1!=a.board.c[c][b+1].errnum&&1>a.board.c[c][b+1].value&&a.markWhiteArea(c,b+1)}catch(d){throw a.exception(d),
d;}};a.valueToString=function(a){return a==nil?"-":1==a?"o":6==a?"ne":12==a?"se":18==a?"nw":24==a?"sw":"?"};a.paintCell=function(c){try{var b=a.canvas.getContext("2d");b.fillStyle=c.label!=nil?a.uic.corner:a.uic.light[c.color];b.fillRect(c.px,c.py,a.unit.x,a.unit.y);switch(c.value){case 1:a.paintCircle(c,{fill:a.uic.corner,scale:50});break;case 0:a.paintCross(c,{color:a.uic.corner});break;case 18:case 6:case 12:case 24:a.paintCorner(c)}c.label>nil&&5>c.label&&a.paintText(c.label.toString(),c,{color:a.uic.white});
a.paintSymbolMarkers(c);0!=c.error&&a.display.errors&&(c.label!=nil?a.paintErrorCircle(c):a.paintErrorDot(c))}catch(e){throw a.exception(e),e;}};a.paintCorner=function(c,b){try{if(b=a.defaultParams(c,b)){c.px?(b.corner||(b.corner=c.value),c=a.canvas.getContext("2d")):b.corner||(b.corner=0);c.strokeStyle=b.stroke?b.stroke:a.uic.corner;c.fillStyle=b.fill?b.fill:a.uic.corner;c.lineWidth=b.width?b.width:1;c.beginPath();switch(b.corner){case 18:c.moveTo(b.x,b.y);c.lineTo(b.x+b.w,b.y);c.lineTo(b.x,b.y+
b.h);c.lineTo(b.x,b.y);break;case 6:c.moveTo(b.x,b.y);c.lineTo(b.x+b.w,b.y+b.h);c.lineTo(b.x+b.w,b.y);c.lineTo(b.x,b.y);break;case 12:c.moveTo(b.x+b.w,b.y);c.lineTo(b.x+b.w,b.y+b.h);c.lineTo(b.x,b.y+b.h);c.moveTo(b.x+b.w,b.y);break;case 24:c.moveTo(b.x,b.y),c.lineTo(b.x+b.w,b.y+b.h),c.lineTo(b.x,b.y+b.h),c.lineTo(b.x,b.y)}c.fill()}}catch(e){throw a.exception(e),e;}};a.paintCurrentValue=function(){try{var c=a.uie.value,b=c.getContext("2d");b.fillStyle=a.uic.white;b.fillRect(0,0,c.width,c.height);var e=
{x:0,y:0,w:c.width,h:c.height,scale:90,corner:a.current.value,fill:a.uic.none,stroke:a.uic.corner,color:a.uic.corner};switch(a.current.value){case 1:a.paintCircle(b,e);break;case 0:a.paintCross(b,e);break;case 18:case 6:case 12:case 24:a.paintCorner(b,e)}}catch(d){throw a.exception(d),d;}}}Shakashaka.prototype=new Puzzle;
