function Skyscrapers(){var a=this;a.constructor();a.uis.puzzle=["Skyscrapers","Wolkenkratzer"];var n=a.board.c,v=a.alist,m=0,k=0,l=0,p=0;zmax=0;a.variant.std=["std",["Skyscrapers","Wolkenkratzer"]];a.variant.sums=["sums",["Skyscrapers (Sums)","Wolkenkratzer (Summen)"]];a.variant.frame=["frame",["Skyscrapers (Frame)","Wolkenkratzer (Rahmen)"]];a.variant.haido=["haido",["Skyscrapers (Haido)","Wolkenkratzer (Haido)"]];a.variant.diagonals=["diagonals",["Diagonals","Diagonalen"]];var u={none:0,visibility:1,
missing:2,duplicate:3};a.cell.nilalias=0;a.enable.vmarkers=!0;a.enable.pgrid=!0;a.enable.values=!1;a.enable.currentValue=!1;a.labels.north=a.labels.south=a.labels.east=a.labels.west=1;a.charToValue=a.charToValue.concat(["x",0,"0",0,",",0,"-",nil,"/",nil]);a.valueToMarker=[0,a.marker.letterX];a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){var b;try{a.variant.init(null,a.variant.std);a.variant.isv(a.variant.std)&&(a.uis.puzzle=a.variant.std[1]);a.variant.isv(a.variant.sums)&&
(a.uis.puzzle=a.variant.sums[1]);a.variant.isv(a.variant.frame)&&(a.uis.puzzle=a.variant.frame[1]);a.variant.isv(a.variant.haido)&&(a.uis.puzzle=a.variant.haido[1]);m=a.labels.south;k=a.labels.north;zmin=1;l=a.size.x-a.labels.east;p=a.size.y-a.labels.south;zmax=a.size.z;a.cell.min=1;a.cell.max=zmax;a.cell.values=[];var c=0;for(b=zmin;b<=zmax;b++)a.cell.values[c++]=b;a.cell.values[c++]=0;a.cell.values[c++]=nil;c=zmax;a.keypadValues=a.keypad.numbers.slice(0,c);a.keypadValues[c++]=["\u00d7",0];a.keypadValues[c++]=
["\u2022",nil];a.infoText=a.uis.get("numbers")+": 1~"+zmax;a.level.areas&&(a.reset2areas(m,k,l,p,a.level.areas),a.enable.pgrid=!1);if(a.level.problem){b=0;var e=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=k;d<p;d++)for(var g=m;g<l;g++){var h=n[g][d];var f=e[b++];h.value="."==f||"-"==f?nil:parseInt(f);h.value!=nil&&(h.fixed=!0)}}if(a.level.solution)for(b=0,e=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=k;d<p;d++)for(g=m;g<l;g++)h=n[g][d],f=e[b++],h.solution="."==f||
"-"==f?nil:parseInt(f);if(a.level.clabels)for(b=0,e=a.level.clabels.replace(/\s+/g," ").trim().split(" "),d=0;d<a.size.y;d+=p)for(g=m;g<l;g++)h=n[g][d],f=e[b++],h.label="-"==f||"."==f?nil:parseInt(f);if(a.level.rlabels)for(b=0,e=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),g=0;g<a.size.x;g+=l)for(d=k;d<p;d++)h=n[g][d],f=e[b++],h.label="-"==f||"."==f?nil:parseInt(f);a.reset2labels()}catch(r){throw a.exception(r),r;}};a.check2=function(){try{for(var b=k;b<p;b++)a.checkLine(m,b,1,0);for(var c=
m;c<l;c++)a.checkLine(c,k,0,1);a.variant.isv(a.variant.diagonals)&&(a.checkLine(m,k,1,1),a.checkLine(l-1,k,-1,1));if(null!=v)for(var e=1;e<v.length;e++)for(var d=[],g=0;g<v[e].length;g++){var h=v[e][g];h.value==nil?h.error=u.empty:d[h.value]?h.error=d[h.value].error=u.duplicate:d[h.value]=h}for(c=m;c<l;c++)a.checkEdges(c,0,0,1);for(c=m;c<l;c++)a.checkEdges(c,a.size.y-1,0,-1);for(b=k;b<p;b++)a.checkEdges(0,b,1,0);for(b=k;b<p;b++)a.checkEdges(a.size.x-1,b,-1,0)}catch(f){throw a.exception(f),f;}};a.checkLine=
function(b,c,e,d){try{for(var g=[],h=0,f=0;;++f){var r=b+e*f;var t=c+d*f;if(r<m||r==l||t<k||t==p)break;var q=n[r][t];q.value!=nil&&q.value!=a.cell.nilalias&&(g[q.value]?q.error=g[q.value].error=u.duplicate:(g[q.value]=q,h++))}if(h!=zmax)for(f=0;f<l;++f){r=b+e*f;t=c+d*f;if(r<m||r==l||t<k||t==p)break;q=n[r][t];if(q.value==nil||q.value==a.cell.nilalias)q.error=u.missing}}catch(w){throw a.exception(w),w;}};a.checkEdges=function(b,c,e,d){try{var g=n[b][c];b+=e;c+=d;for(var h=0,f=0,r=0;b>=m&&b<l&&c>=k&&
c<p;)n[b][c].value>r&&(r=n[b][c].value,h+=n[b][c].value,f++),b+=e,c+=d;var t=a.variant.isv(a.variant.sums);g.label!=nil&&(t&&h!=g.label||!t&&f!=g.label)&&(g.error=u.visibility);return t?h:f}catch(q){throw a.exception(q),q;}};a.initValueMarkers2=function(){for(var b=m;b<l;b++)for(var c=k;c<p;c++)for(var e=zmin;e<=zmax;e++)n[b][c].markers.set(a.marker.numberBase+e)};a.updateValueMarkers2=function(){for(var b=m;b<l;b++)for(var c=k;c<p;c++){var e=n[b][c];if(e.value!=nil){for(var d=0;d<a.size.x;d++)n[d][c].markers.clear(a.marker.numberBase+
e.value);for(d=0;d<a.size.y;d++)n[b][d].markers.clear(a.marker.numberBase+e.value)}}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):a.paintValueCell(b)}catch(c){throw a.exception(c),c;}};a.paintLabelCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.label;c.fillRect(b.px,b.py,a.unit.x,a.unit.y);b.label!=nil&&a.paintText(b.label.toString(),b);b.error&&a.display.errors&&a.paintErrorCircle(b)}catch(e){throw a.exception(e),e;}};a.paintValueCell=function(b){try{var c=
a.canvas.getContext("2d");c.fillStyle=a.uic.light[b.color];c.fillRect(b.px,b.py,a.unit.x,a.unit.y);a.variant.isv(a.variant.diagonals)&&(b.x==b.y&&a.paintDiagonal(b,1),b.x==a.size.y-b.y-1&&a.paintDiagonal(b,2));a.paintSymbolMarkers(b);a.paintValueMarkers(b);0==b.value?a.paintCross(b):b.value!=nil&&a.paintText(b.value.toString(),b,{color:b.fixed?a.uic.clue:a.uic.text});b.error&&a.display.errors&&(b.value==nil?a.paintErrorDot(b):a.paintErrorCircle(b))}catch(e){throw a.exception(e),e;}}}
Skyscrapers.prototype=new Puzzle;
