function Snake(){var a=this;a.constructor();a.uis.puzzle=["Snake","Schlange"];var e=a.board.c,n=0,p=0,l=0,m=0,u=nil,v=[-1,1,0,0],w=[0,0,-1,1],x=[-1,1,-1,1],y=[-1,1,1,-1];a.charToValue=a.charToValue.concat(["a",0,"s",1,"d",nil,"x",0,"c",1,"v",nil,",",0,".",1,"-",nil,"/",nil]);a.cell.values=[0,1,u];a.enable.dragging=!0;a.enable.pgrid=!0;a.keypad.left=nil;a.cell.nilalias=1;a.uic.fixed="#88ccff";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.setup2=function(){try{if(a.labels.north=a.labels.west=
1,a.labels.south=a.labels.east=0,a.level.nlabels){var d=a.level.nlabels.replace(/\s+/g," ").trim().split(" ");a.labels.west=parseInt(d[0]);a.labels.north=parseInt(d[1]);a.labels.east=parseInt(d[2]);a.labels.south=parseInt(d[3])}}catch(b){return ojdebug(b.toString()),"%"}};a.reset2=function(){try{n=a.labels.west;p=a.labels.north;l=a.size.x-a.labels.east;m=a.size.y-a.labels.south;if(a.level.problem){var d=0;var b=0;var h=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var c=p;c<m;c++)for(var f=
n;f<l;f++){var k=e[f][c];var g=h[b++];"."==g||"-"==g?k.value=nil:"o"==g?k.value=1:"x"==g?(k.value=0,d++):"#"==g?(k.label=0,k.fixed=!0):k.label=parseInt(g);k.value!=nil&&(k.fixed=!0)}}if(a.level.clabels)for(b=0,h=a.level.clabels.replace(/\s+/g," ").trim().split(" "),f=n;f<l;f++)k=e[f][0],g=h[b++],k.label="-"==g||"."==g?nil:parseInt(g);if(a.level.rlabels)for(b=0,h=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),c=p;c<m;c++)k=e[0][c],g=h[b++],k.label="-"==g||"."==g?nil:parseInt(g);if(a.level.solution)for(b=
0,h=a.level.solution.replace(/\s+/g," ").trim().split(" "),c=p;c<m;c++)for(f=n;f<l;f++)k=e[f][c],g=h[b++],k.solution="x"==g?0:1;if(1==a.labels.north&&1==a.labels.west&&!a.level.cabels&&!a.level.rlabels&&a.level.solution){for(f=n;f<l;f++)for(e[f][0].label=0,c=p;c<m;c++)0==e[f][c].solution&&e[f][0].label++;for(c=p;c<m;c++)for(e[0][c].label=0,f=n;f<l;f++)0==e[f][c].solution&&e[0][c].label++;for(f=n;f<l;f++)for(c=p;c<m;c++)if(k=e[f][c],0==k.solution){for(b=g=0;4>b;b++){var q=f+v[b],r=c+w[b];0<q&&q<l&&
0<r&&r<m&&0==e[q][r].solution&&g++}1==g&&(k.value=0,k.fixed=!0)}}0==a.labels.north&&0==a.labels.south&&0==a.labels.east&&0==a.labels.west||a.reset2labels()}catch(t){return ojdebug(t.toString()),"%"}};a.check2=function(){var a,b;try{for(b=n;b<l;++b)if(e[b][0].label!=nil){var h=0;for(a=p;a<m;++a)0==e[b][a].value&&h++;h!=e[b][0].label&&(e[b][0].error=2)}for(a=p;a<m;++a)if(e[0][a].label!=nil){h=0;for(b=n;b<l;++b)0==e[b][a].value&&h++;h!=e[0][a].label&&(e[0][a].error=2)}var c=null;for(b=n;b<l;b++)for(a=
p;a<m;a++)e[b][a].fixed&&(c=e[b][a]);h=1;for(var f=null;;){c.count=h++;for(var k=0,g=0;4>g;g++)if(b=c.x+v[g],a=c.y+w[g],0<b&&0<a&&b<l&&a<m){var q=e[b][a];0==q.value&&0==q.count&&(k++,f=q)}if(0==k){c.fixed||(c.error=3);break}else 1!=k&&(c.error=4),c=f}for(b=n;b<l;b++)for(a=p;a<m;a++)c=e[b][a],0==c.value&&0==c.count&&(c.error=3);for(b=n;b<l;b++)for(a=p;a<m;a++)if(c=e[b][a],0==c.value&&0!=c.count)for(g=0;4>g;g++){var r=c.x+x[g],t=c.y+y[g];0<r&&0<t&&r<l&&t<m&&(q=e[r][t],0==q.value&&q.count!=c.count+2&&
q.count!=c.count-2&&(q.error=4))}}catch(z){return ojdebug(z.toString()),"%"}};a.cleanSolution=function(){try{for(var a=n;a<l;a++)for(var b=p;b<m;b++)e[a][b].value==nil&&(e[a][b].value=1)}catch(h){return ojdebug(h.toString()),"%"}};a.solve2=function(){try{for(var a=0;a<l;a++)if(0==e[a][0].label)for(var b=p;b<m;b++)e[a][b].value=1;for(b=0;b<m;b++)if(0==e[0][b].label)for(a=n;a<l;a++)e[a][b].value=1}catch(h){return ojdebug(h.toString()),"%"}};a.valueToString=function(a){return 0==a?"x":"-"};a.paintCell=
function(d){d.areas==a.cell.label?a.paintLabelCell(d):a.paintValueCell(d)};a.paintLabelCell=function(d){try{var b=a.canvas.getContext("2d");b.fillStyle=a.uic.label;b.fillRect(d.px,d.py,a.unit.x,a.unit.y);d.label!=nil&&a.paintText(d.label.toString(),d);d.error&&a.display.errors&&a.paintErrorCircle(d)}catch(h){return ojdebug(h.toString()),"%"}};a.paintValueCell=function(d){try{var b=a.canvas.getContext("2d");b.fillStyle=d.value==nil?a.paintToImage&&a.moves.current==nil?a.uic.white:a.uic.gray:0==d.value?
a.uic.dark[d.color]:a.uic.light[d.color];b.fillRect(d.px,d.py,a.unit.x,a.unit.y);d.label!=nil&&(0==d.label?a.paintCross(d):a.paintText(d.label.toString(),d,{color:0!=d.value?a.uic.text:a.uic.text2}));d.fixed&&(a.paintCross(d,{color:a.uic.fixed,width:2}),a.paintCircle(d,{stroke:a.uic.fixed,scale:40}));a.paintSymbolMarkers(d);d.error&&a.display.errors&&a.paintErrorDot(d)}catch(h){return ojdebug(h.toString()),"%"}};a.paintCurrentValue=function(){try{var d=a.uie.value,b=d.getContext("2d");b.fillStyle=
a.current.value==u?a.uic.gray:0==a.current.value?a.uic.black:a.uic.white;b.fillRect(0,0,d.width,d.height)}catch(h){return ojdebug(h.toString()),"%"}}}Snake.prototype=new Puzzle;
