function Starnight(){var a=this;a.constructor();a.uis.puzzle=["Starry Night","Sternennacht"];var f=a.board.c,k=0,l=0;a.labels.north=a.labels.west=1;var p=[-1,-1,1,1],q=[-1,1,-1,1];a.charToValue=a.charToValue.concat(["s",1,"*",1,"o",2,"u",2,"m",3,".",3,"x",0,"-",nil,"/",nil]);a.valueToMarker=[0,a.marker.letterX,1,a.marker.letterBase+18,2,a.marker.letterBase+14,3,a.marker.letterBase+12];a.cell.values=[1,2,3,0,nil];a.enable.vmarkers=!0;a.enable.pgrid=!0;a.keypad.left=nil;a.keypad.right=a.keypad.values;
a.cell.nilalias=0;a.uic.starfill="#ffff00";a.uic.staredge="#888800";a.uic.moonfill="#999999";a.uic.moonedge="#000000";a.uic.sunfill="#ffffff";a.uic.sunedge="#000000";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{k=a.size.x;l=a.size.y;a.keypadValues=[[a.paintStar,1],[a.paintSun,2],[a.paintMoon,3],[a.paintCross,0],["\u2022",nil]];if(a.level.problem){var b=0;var e=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var c=1;c<l;c++)for(var g=1;g<k;g++){var d=f[g][c];
var h=e[b++];"."==h||"-"==h?d.value=nil:"x"==h?d.value=0:"*"==h?d.value=1:"s"==h?d.value=2:"m"==h&&(d.value=3);d.value!=nil&&(d.fixed=!0)}}if(a.level.solution)for(b=0,e=a.level.solution.replace(/\s+/g," ").trim().split(" "),c=1;c<l;c++)for(g=1;g<k;g++)d=f[g][c],h=e[b++],"."==h||"-"==h?d.solution=nil:"x"==h?d.solution=0:"*"==h?d.solution=1:"s"==h?d.solution=2:"m"==h&&(d.solution=3);if(a.level.clabels)for(b=0,e=a.level.clabels.replace(/\s+/g," ").trim().split(" "),g=1;g<k;g++)d=f[g][0],h=e[b++],"."==
h||"-"==h?d.label=nil:"*"==h?d.label=1:"s"==h?d.label=2:"m"==h&&(d.label=3);if(a.level.rlabels)for(b=0,e=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),c=1;c<l;c++)d=f[0][c],h=e[b++],"."==h||"-"==h?d.label=nil:"*"==h?d.label=1:"s"==h?d.label=2:"m"==h&&(d.label=3);a.reset2labels()}catch(m){throw a.exception(m),m;}};a.check2=function(){var b,e;try{for(var c=1;c<l;c++){var g=b=e=nil;for(var d=1;d<k;d++)1==f[d][c].value?g==nil?g=d:f[d][c].error=f[g][c].error=1:3==f[d][c].value?b==nil?b=d:f[d][c].error=
f[b][c].error=1:2==f[d][c].value&&(e==nil?e=d:f[d][c].error=f[e][c].error=1);e==nil||b==nil||g==nil?f[0][c].error=1:1==f[0][c].label?Math.abs(g-b)!=Math.abs(g-e)&&(f[0][c].error=2):3==f[0][c].label?Math.abs(g-b)>=Math.abs(g-e)&&(f[0][c].error=2):2==f[0][c].label&&Math.abs(g-b)<=Math.abs(g-e)&&(f[0][c].error=2)}for(d=1;d<k;d++){g=b=e=nil;for(c=1;c<l;c++)1==f[d][c].value?g==nil?g=c:(f[d][c].error=1,f[d][g].error=1):3==f[d][c].value?b==nil?b=c:(f[d][c].error=1,f[d][b].error=1):2==f[d][c].value&&(e==
nil?e=c:(f[d][c].error=1,f[d][e].error=1));e==nil||b==nil||g==nil?f[d][0].error=1:1==f[d][0].label?Math.abs(g-b)!=Math.abs(g-e)&&(f[d][0].error=2):3==f[d][0].label?Math.abs(g-b)>=Math.abs(g-e)&&(f[d][0].error=2):2==f[d][0].label&&Math.abs(g-b)<=Math.abs(g-e)&&(f[d][0].error=2)}for(d=1;d<k;d++)for(c=1;c<l;c++)if(f[d][c].value!=nil&&0!=f[d][c].value)for(g=0;4>g;g++){var h=d+p[g],m=c+q[g];0<=h&&h<k&&0<=m&&m<l&&f[h][m].value==f[d][c].value&&(f[d][c].error=f[h][m].error=3)}}catch(n){throw a.exception(n),
n;}};a.valueToString=function(a,e){switch(a){case 0:return e?"x":"-";case 2:return"s";case 3:return"m";case 1:return"*";default:return"-"}};a.labelToString=function(b){try{return a.valueToString(b)}catch(e){return ojdebug(e.toString()),"%"}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):a.paintValueCell(b)}catch(e){throw a.exception(e),e;}};a.paintLabelCell=function(b){try{var e=a.canvas.getContext("2d");e.fillStyle=a.uic.label;e.fillRect(b.px,b.py,a.unit.x,a.unit.y);1==b.label?
a.paintStar(b):3==b.label?a.paintMoon(b):2==b.label&&a.paintSun(b);b.error&&a.display.errors&&a.paintErrorCircle(b)}catch(c){throw a.exception(c),c;}};a.paintValueCell=function(b){try{var e=a.canvas.getContext("2d");0!=b.color&&(e.fillStyle=a.uic.light[b.color],e.fillRect(b.px,b.py,a.unit.x,a.unit.y));a.paintSymbolMarkers(b);a.paintValueMarkers(b);2==b.value?a.paintSun(b):3==b.value?a.paintMoon(b):1==b.value?a.paintStar(b):0==b.value&&a.paintCross(b);b.error&&a.display.errors&&a.paintErrorDot(b)}catch(c){throw a.exception(c),
c;}};a.paintSun=function(b,e){try{e||(e={}),e.scale=50,e.width=1,e.stroke=a.uic.sunedge,e.fill=a.uic.sunfill,a.paintCircle(b,e)}catch(c){throw a.exception(c),c;}};a.paintMoon=function(b,e){try{e||(e={}),e.scale=50,e.width=1,e.stroke=a.uic.moonedge,e.fill=a.uic.moonfill,a.paintCircle(b,e)}catch(c){throw a.exception(c),c;}};a.paintCurrentValue=function(){try{var b=a.uie.value,e=b.getContext("2d");e.fillStyle=a.uic.white;e.fillRect(0,0,b.width,b.height);var c={x:0,y:0,w:b.width,h:b.height};1==a.current.value?
a.paintStar(e,c):2==a.current.value?a.paintSun(e,c):3==a.current.value?a.paintMoon(e,c):0==a.current.value&&a.paintCross(e,c)}catch(g){throw a.exception(g),g;}}}Starnight.prototype=new Puzzle;
