function Starcluster(){var c=this;c.constructor();c.uis.puzzle=["Star Cluster","Sternenhaufen"];var e=c.board.c,k=0,l=0;c.charToValue=c.charToValue.concat(["a",1,"s",0,"d",nil,"c",2,".",1,",",0,"-",nil,"#",2,"o",1,"x",0,"/",nil,"w",2,"*",1]);c.cell.values=[1,2,0,nil];c.enable.dragging=!0;c.enable.pgrid=!0;c.keypad.left=nil;c.keypad.right=c.keypad.values;c.cell.nilalias=0;c.uic.starfill="#ffff00";c.uic.staredge="#888800";c.uic.cloudfill="#aaaaaa";c.uic.cloudedge="#000000";c.uic.planetfill="#333333";
c.uic.planetedge="#000000";c.init=function(){Object.getPrototypeOf(c).init.call(c)};c.reset2=function(){try{k=c.size.x;l=c.size.y;c.keypadValues=[[c.paintStar,1],[c.paintCloud,2],[c.paintCross,0],["\u2022",nil]];if(c.level.problem){var a=0;var b=c.level.problem.replace(/\s+/g," ").trim().split(" ");for(var f=0;f<l;f++)for(var d=0;d<k;d++){var g=e[d][f];var h=b[a++];"."==h||"-"==h?g.value=nil:"*"==h||"s"==h?g.value=1:"#"==h||"x"==h?g.value=2:(g.value=3,g.label=parseInt(h));g.value!=nil&&(g.fixed=!0)}}if(c.level.solution)for(a=
0,b=c.level.solution.replace(/\s+/g," ").trim().split(" "),f=0;f<l;f++)for(d=0;d<k;d++)g=e[d][f],h=b[a++],"-"==h||"."==h?g.solution=nil:"*"==h||"s"==h?g.solution=1:"#"==h||"x"==h?g.solution=2:(g.value=3,g.fixed=!0,g.label=parseInt(h),g.solution=3)}catch(m){throw c.exception(m),m;}};c.check2=function(){try{for(var a=0;a<l;a++){for(var b=nil,f=nil,d=0;d<k;d++)1==e[d][a].value&&(b==nil?b=d:(e[b][a].error=1,e[d][a].error=1)),2==e[d][a].value&&(f==nil?f=d:(e[f][a].error=1,e[d][a].error=1));if(b==nil||
f==nil)for(d=0;d<k;d++)e[d][a].error=2}for(d=0;d<k;d++){f=b=nil;for(a=0;a<l;a++)1==e[d][a].value&&(b==nil?b=a:(e[d][b].error=1,e[d][a].error=1)),2==e[d][a].value&&(f==nil?f=a:(e[d][f].error=1,e[d][a].error=1));if(b==nil||f==nil)for(a=0;a<l;a++)e[d][a].error=2}for(d=0;d<k;d++)for(a=0;a<l;a++)e[d][a].work=0;for(d=0;d<k;d++)for(a=0;a<l;a++)if(1==e[d][a].value){for(b=d;b<k&&2!=e[b][a].value;b++)if(e[b][a].label!=nil){e[b][a].work|=4;break}for(b=d;0<=b&&2!=e[b][a].value;b--)if(e[b][a].label!=nil){e[b][a].work|=
1;break}for(b=a;b<l&&2!=e[d][b].value;b++)if(e[d][b].label!=nil){e[d][b].work|=8;break}for(b=a;0<=b&&2!=e[d][b].value;b--)if(e[d][b].label!=nil){e[d][b].work|=2;break}}for(d=0;d<k;d++)for(a=0;a<l;a++)e[d][a].label!=nil&&e[d][a].label!=e[d][a].work&&(e[d][a].error=3)}catch(g){throw c.exception(g),g;}};c.valueToString=function(a,b){switch(a){case 0:return b?"x":"-";case 1:return"s";case 2:return"#";default:return"-"}};c.paintCell=function(a){try{var b=c.canvas.getContext("2d");b.fillStyle=c.uic.light[a.color];
b.fillRect(a.px,a.py,c.unit.x,c.unit.y);if(a.areas!=c.cell.black){switch(a.value){case 0:c.paintCross(a);break;case 1:c.paintStar(a);break;case 2:c.paintCloud(a);break;case 3:c.paintPlanet(a)}c.paintSymbolMarkers(a);0!=a.error&&c.display.errors&&(3==a.error||1==a.error&&1==a.value?c.paintErrorSquare(a):a.value==nil&&c.paintErrorDot(a))}}catch(f){throw c.exception(f),f;}};c.paintCloud=function(a,b){try{b||(b={}),b.scale=50,b.width=1,b.stroke=c.uic.cloudedge,b.fill=c.uic.cloudfill,c.paintSquare(a,b)}catch(f){throw c.exception(f),
f;}};c.paintPlanet=function(a,b){try{if(b=c.defaultParams(a,b)){a.px?(b.planet||(b.planet=a.label),a=c.canvas.getContext("2d")):b.planet||(b.planet=0);a.strokeStyle=b.stroke?b.stroke:c.uic.planetedge;a.fillStyle=b.fill?b.fill:c.uic.planetfill;a.lineWidth=b.width?b.width:1;var e=b.w/4;a.fillStyle=c.uic.planetfill;a.beginPath();a.arc(b.x+b.w/2,b.y+b.h/2,e,0,2*Math.PI);a.fill();a.fillStyle=c.uic.starfill;a.beginPath();0!=(b.planet&1)&&a.arc(b.x+b.w/2,b.y+b.h/2,e,1.5*Math.PI,.5*Math.PI);a.fill();a.beginPath();
0!=(b.planet&8)&&a.arc(b.x+b.w/2,b.y+b.h/2,e,Math.PI,0);a.fill();a.beginPath();0!=(b.planet&4)&&a.arc(b.x+b.w/2,b.y+b.h/2,e,.5*Math.PI,1.5*Math.PI);a.fill();a.beginPath();0!=(b.planet&2)&&a.arc(b.x+b.w/2,b.y+b.h/2,e,0,Math.PI);a.fill();a.beginPath();a.arc(b.x+b.w/2,b.y+b.h/2,e,0,2*Math.PI);a.stroke()}}catch(d){throw c.exception(d),d;}};c.paintCurrentValue=function(){try{var a=c.uie.value,b=a.getContext("2d");b.fillStyle=c.uic.white;b.fillRect(0,0,a.width,a.height);var e={x:0,y:0,w:a.width,h:a.height};
1==c.current.value?c.paintStar(b,e):2==c.current.value?c.paintCloud(b,e):0==c.current.value&&c.paintCross(b,e)}catch(d){throw c.exception(d),d;}}}Starcluster.prototype=new Puzzle;
