function Starmap(){var a=this;a.constructor();a.uis.puzzle=["Star Map","Sternenhimmel"];var h=a.board.c,l=0,k=0;a.variant.exactly=["exactly",["Exactly one Star","Genau ein Stern"]];a.variant.atleast=["atleast",["At least one Star","Mindestens ein Stern"]];var n=[0,0,1,-1,-1,-1,1,1],p=[-1,1,0,0,-1,1,1,-1];a.charToValue=a.charToValue.concat(["a",1,"s",0,"d",nil,".",1,",",0,"-",nil,"o",1,"x",0,"/",nil,"*",1]);a.cell.values=[1,0,nil];a.enable.pgrid=!0;a.enable.dragging=!0;a.keypad.left=nil;a.labels.north=
a.labels.west=1;a.cell.nilalias=0;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{a.variant.init(a.variant.atleast);a.uis.puzzle=["Star Map","Sternenhimmel"];a.variant.isv(a.variant.atleast)&&(a.infoText=a.variant.atleast[1][a.uis.lang]);a.variant.isv(a.variant.exactly)&&(a.infoText=a.variant.exactly[1][a.uis.lang]);l=a.size.x;k=a.size.y;if(a.level.problem){var c=0;var b=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var e=1;e<k;e++)for(var d=1;d<l;d++){var g=
h[d][e];var f=b[c++];if("."!=f&&"-"!=f)if("*"==f||"o"==f)g.value=1;else if("x"==f)g.value=0;else if("n"==f)g.label=0;else if("s"==f)g.label=1;else if("e"==f)g.label=2;else if("w"==f)g.label=3;else if("nw"==f)g.label=4;else if("sw"==f)g.label=5;else if("se"==f||"so"==f)g.label=6;else if("ne"==f||"no"==f)g.label=7;if(g.value!=nil||g.label!=nil)g.fixed=!0}}if(a.level.solution)for(c=0,b=a.level.solution.replace(/\s+/g," ").trim().split(" "),e=1;e<k;e++)for(d=1;d<l;d++)if(g=h[d][e],f=b[c++],"x"==f||"*"==
f)g.solution=1;if(a.level.clabels)for(c=0,b=a.level.clabels.replace(/\s+/g," ").trim().split(" "),d=1;d<l;d++)g=h[d][0],f=b[c++],g.label="-"==f||"."==f?nil:parseInt(f);if(a.level.rlabels)for(c=0,b=a.level.rlabels.replace(/\s+/g," ").trim().split(" "),e=1;e<k;e++)g=h[0][e],f=b[c++],g.label="-"==f||"."==f?nil:parseInt(f);if(!a.level.rlabels&&a.level.solution){for(d=1;d<a.size.x;d++)a.board.c[d][0].label=0;for(e=1;e<a.size.y;e++)a.board.c[0][e].label=0;for(e=1;e<a.size.y;e++)for(d=1;d<a.size.x;d++)1==
a.board.c[d][e].solution&&(a.board.c[d][0].label++,a.board.c[0][e].label++)}a.reset2labels()}catch(m){throw a.exception(m),m;}};a.check2=function(){try{for(var c=[1,0,3,2,6,7,4,5],b=1;b<k;b++){var e=0;for(var d=1;d<l;d++)1==h[d][b].value&&e++;h[0][b].label!=nil&&h[0][b].label!=e&&(h[0][b].error=1)}for(d=1;d<l;d++){e=0;for(b=1;b<k;b++)1==h[d][b].value&&e++;h[d][0].label!=nil&&h[d][0].label!=e&&(h[d][0].error=1)}for(d=1;d<l;d++)for(b=1;b<k;b++)if(h[d][b].label!=nil){var g=d;var f=b;for(var m=0;0<g&&
g<l&&0<f&&f<k;)1==h[g][f].value&&m++,g+=n[h[d][b].label],f+=p[h[d][b].label];if(a.variant.isv(a.variant.exactly)&&1!=m||a.variant.isv(a.variant.atleast)&&0==m)h[d][b].error=1}for(d=1;d<l;d++)for(b=1;b<k;b++)if(1==h[d][b].value){for(e=m=0;8>e;e++)for(g=d,f=b;1<=g&&g<l&&1<=f&&f<k;)h[g][f].label==c[e]&&m++,g+=n[e],f+=p[e];1!=m&&(solved=!1,h[d][b].error=1)}}catch(q){throw a.exception(q),q;}};a.solve2=function(){for(var a=1;a<l;a++)for(var b=1;b<k;b++)if(h[a][b].label!=nil)for(var e=n[h[a][b].label],d=
p[h[a][b].label],g=a,f=b;!(h[g][f].marked=!0,g+=e,f+=d,1>g||g>=l||1>f||f>=k););for(a=1;a<l;a++)for(b=1;b<k;b++)h[a][b].marked||(h[a][b].value=0)};a.valueToString=function(a,b){switch(a){case 0:return b?"x":"-";case 1:return"*";default:return"-"}};a.labelToString=function(c,b){try{switch(c){case 0:return"n";case 1:return"s";case 2:return"e";case 3:return"w";case 4:return"nw";case 5:return"sw";case 6:return"se";case 7:return"ne";default:return a.numberToString(c)}}catch(e){return ojdebug(e.toString()),
"%"}};a.paintCell=function(c){try{c.areas==a.cell.label?a.paintLabelCell(c):a.paintValueCell(c)}catch(b){throw a.exception(b),b;}};a.paintLabelCell=function(c){try{var b=a.canvas.getContext("2d");b.fillStyle=a.uic.label;b.fillRect(c.px,c.py,a.unit.x,a.unit.y);c.label!=nil&&a.paintText(c.label.toString(),c);c.error&&a.display.errors&&a.paintErrorCircle(c)}catch(e){throw a.exception(e),e;}};a.paintValueCell=function(c){try{var b=a.canvas.getContext("2d");0!=c.color&&(b.fillStyle=a.uic.light[c.color],
b.fillRect(c.px,c.py,a.unit.x,a.unit.y));1==c.value?a.paintStar(c):0==c.value&&a.paintCross(c);c.label!=nil&&a.paintArrow(c);a.paintSymbolMarkers(c);c.error&&a.display.errors&&(c.label!=nil||c.value!=nil?a.paintErrorCircle(c):a.paintErrorDot(c))}catch(e){throw a.exception(e),e;}};a.paintArrow=function(c,b){try{if(b=a.defaultParams(c,b)){c.px?(b.v||(b.v=c.label),c=a.canvas.getContext("2d")):b.v||(b.v=0);b.scale||(b.scale=75);c.strokeStyle=b.stroke?b.stroke:a.uic.arrowedge;c.fillStyle=b.fill?b.fill:
a.uic.arrowfill;c.lineWidth=b.width?b.width:1;var e=[[50,95,75,75,25,25,5],[50,95,75,75,25,25,5],[95,50,50,5,5,50,50],[5,50,50,95,95,50,50],[5,75,60,95,55,20,5],[5,20,55,95,60,75,5],[45,80,95,95,25,40,5],[25,95,95,80,45,5,40]],d=[[5,50,50,95,95,50,50],[95,50,50,5,5,50,50],[50,95,75,75,25,25,5],[50,95,75,75,25,25,5],[5,5,20,55,95,60,75],[25,40,5,45,75,95,95],[5,40,25,95,95,80,45],[5,5,75,60,95,55,20]],g=Math.floor(b.w/6),f=b.w-g-g,h=b.x+g,l=b.y+g,k=e[b.v].length-1;c.beginPath();c.moveTo(h+e[b.v][k]*
f/100,l+d[b.v][k]*f/100);for(g=0;g<=k;g++)c.lineTo(h+e[b.v][g]*f/100,l+d[b.v][g]*f/100);c.fillStyle!=a.uic.none&&c.fill();c.strokeStyle!=a.uic.none&&c.stroke()}}catch(r){throw a.exception(r),r;}};a.paintCurrentValue=function(){try{var c=a.uie.value,b=c.getContext("2d");b.fillStyle=a.uic.white;b.fillRect(0,0,c.width,c.height);var e={x:0,y:0,w:c.width,h:c.height};1==a.current.value?a.paintStar(b,e):0==a.current.value&&a.paintCross(b,e)}catch(d){throw a.exception(d),d;}}}Starmap.prototype=new Puzzle;
