function Tateboo(){var d=this;d.constructor();d.uis.puzzle=["Tateboo Yokoboo"];var c=d.board.c,k=0,l=0;d.charToValue=d.charToValue.concat(["h",10,"v",5,"x",nil,",",nil,".",nil,"-",nil,"/",nil]);d.cell.values=[5,10,nil];d.keypadValues=[["\u2014",10],["|",5],["\u2022",nil]];d.enable.dragging=!0;d.enable.pgrid=!0;d.enable.values=!1;d.enable.currentValue=!1;d.keypad.left=nil;d.uic.smarkers="#000000";d.uic.line="#cccccc";d.init=function(){Object.getPrototypeOf(d).init.call(d)};d.reset2=function(){try{k=
d.size.x;l=d.size.y;if(d.level.problem){var a=0;var b=d.level.problem.replace(/\s+/g," ").trim().split(" ");for(var f=0;f<l;f++)for(var h=0;h<k;h++){var e=c[h][f];var g=b[a++];"."==g||"-"==g?e.value=nil:"ns"==g||"v"==g?e.value=5:"ew"==g||"h"==g?e.value=10:(g.contains("x")&&(e.clues=1,e.fixed=!0,g=g.replace("x","")),""!=g&&(e.label=parseInt(g)));e.value!=nil&&(e.fixed=!0)}}if(d.level.solution)for(a=0,b=d.level.solution.replace(/\s+/g," ").trim().split(" "),f=0;f<l;f++)for(h=0;h<k;h++)if(e=c[h][f],
g=b[a++],"."==g||"-"==g)e.solution=nil;else if("n"==g)e.solution=1;else if("e"==g)e.solution=2;else if("s"==g)e.solution=4;else if("w"==g)e.solution=8;else if("ns"==g||"v"==g)e.solution=5;else if("ew"==g||"h"==g)e.solution=10}catch(m){throw d.exception(m),m;}};d.check2=function(){try{for(var a=0;a<k;a++)for(var b=0;b<l;b++){var f=c[a][b];if(f.label!=nil){var h=0;if(1==f.clues)0<a&&10==c[a-1][b].value&&h++,a<k-1&&10==c[a+1][b].value&&h++,0<b&&5==c[a][b-1].value&&h++,b<l-1&&5==c[a][b+1].value&&h++,
f.label!=h&&(f.error=2);else if(10==f.value){h++;for(var e=a;0<e&&10==c[e-1][b].value;e--)h++,c[e-1][b].label!=nil&&(c[e-1][b].error=f.error=3);for(e=a;e<k-1&&10==c[e+1][b].value;e++)h++,c[e+1][b].label!=nil&&(c[e+1][b].error=f.error=3);f.label!=h&&(f.error=4)}else if(5==f.value){h++;for(e=b;0<e&&5==c[a][e-1].value;e--)h++,c[a][e-1].label!=nil&&(c[a][e-1].error=f.error=3);for(e=b;e<l-1&&5==c[a][e+1].value;e++)h++,c[a][e+1].label!=nil&&(c[a][e+1].error=f.error=3);f.label!=h&&(f.error=4)}}}for(a=0;a<
k;a++)for(b=0;b<l;b++)f=c[a][b],f.value!=nil||f.fixed||(f.error=1)}catch(g){throw d.exception(g),g;}};d.solve2=function(){try{for(var a=0;a<k;a++)for(var b=0;b<l;b++)1==c[a][b].clues&&(0==c[a][b].label?(0<a&&1!=c[a-1][b].clues&&(c[a-1][b].value=5),0<b&&1!=c[a][b-1].clues&&(c[a][b-1].value=10),a<k-1&&1!=c[a+1][b].clues&&(c[a+1][b].value=5),b<l-1&&1!=c[a][b+1].clues&&(c[a][b+1].value=10)):4==c[a][b].label?(0<a&&(c[a-1][b].value=10),0<b&&(c[a][b-1].value=5),a<k-1&&(c[a+1][b].value=10),b<l-1&&(c[a][b+
1].value=5)):2==c[a][b].label?(0==a&&0==b&&(c[a+1][b].value=10,c[a][b+1].value=5),0==a&&b==l-1&&(c[a+1][b].value=10,c[a][b-1].value=5),a==k-1&&0==b&&(c[a-1][b].value=10,c[a][b+1].value=5),a==k-1&&b==l-1&&(c[a-1][b].value=10,c[a][b-1].value=5)):3==c[a][b].label&&(0==a&&(c[a+1][b].value=10,c[a][b-1].value=5,c[a][b+1].value=5),0==b&&(c[a][b+1].value=5,c[a-1][b].value=10,c[a+1][b].value=10),a==k-1&&(c[a-1][b].value=10,c[a][b-1].value=5,c[a][b+1].value=5),b==l-1&&(c[a][b-1].value=5,c[a-1][b].value=10,
c[a+1][b].value=10)));d.pushEvent(d.moves.typeSolve,0);d.check()}catch(f){throw d.exception(f),f;}};d.dragTo2=function(a,b){a.x==b.x-1&&b.y==a.y&&(d.makeMove(b,10),d.makeMove(a,10));a.x==b.x+1&&b.y==a.y&&(d.makeMove(b,10),d.makeMove(a,10));a.y==b.y+1&&b.x==a.x&&(d.makeMove(b,5),d.makeMove(a,5));a.y==b.y-1&&b.x==a.x&&(d.makeMove(b,5),d.makeMove(a,5))};d.valueToString=function(a,b){switch(a){case 16:return b?"x":"-";case 15:return"nsew";case 0:return"o";case 4:return"s";case 1:return"n";case 2:return"e";
case 8:return"w";case 3:return"ne";case 9:return"nw";case 6:return"se";case 12:return"sw";case 5:return"ns";case 10:return"ew";default:return"-"}};d.paintCell=function(a){try{var b=d.canvas.getContext("2d");b.fillStyle=1==a.clues?d.uic.dark[0]:d.uic.light[0];b.fillRect(a.px,a.py,d.unit.x,d.unit.y);if(a.value!=nil){var c=Math.floor((d.unit.x-Math.floor(d.unit.x/4))/2),h=d.unit.x-2*c,e=h+c;b.fillStyle=d.display.errors&&0<a.count?d.uic.dark[a.count%10]:0==a.color?d.uic.line:d.uic.light[a.color];0!=(a.value&
1)&&b.fillRect(a.px+c,a.py,h,e);0!=(a.value&4)&&b.fillRect(a.px+c,a.py+c,h,e);0!=(a.value&2)&&b.fillRect(a.px+c,a.py+c,e,h);0!=(a.value&8)&&b.fillRect(a.px,a.py+c,e,h)}a.label!=nil&&(1==a.clues?d.paintText(a.label.toString(),a,{color:d.uic.white}):d.paintText(a.label.toString(),a,{color:d.uic.black}));d.paintSymbolMarkers(a);a.error&&d.display.errors&&(a.value==nil&&a.label==nil?d.paintErrorDot(a):d.paintErrorCircle(a))}catch(g){throw d.exception(g),g;}}}Tateboo.prototype=new Puzzle;
