function Tents2(){var a=this;a.constructor();a.uis.puzzle=["Tents and Trees 2","Zeltlager 2"];a.labels.north=a.labels.west=1;var l=!1;a.charToValue=a.charToValue.concat(["a",1,"s",0,"d",nil,".",1,",",0,"-",nil,"z",1,"x",0,"/",nil,"t",2,"o",2,"b",2]);a.cell.values=[1,2,0,nil];a.line.values=[a.line.cross,a.line.wall,a.line.grid];a.uic.treefill="#00bb00";a.uic.treeedge="#004400";a.uic.tentfill="#0000ff";a.uic.tentedge="#000000";a.enable.dragging=!0;a.enable.cells=!0;a.enable.lines=!a.config.touch;a.keypad.left=
nil;a.cell.nilalias=0;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.setup2=function(){var b;try{a.labels.north=0;a.labels.west=0;if(a.level.rlabels&&a.level.clabels){var c=a.level.clabels.trim().split("\n");for(b=0;b<c.length;b++){var d=c[b].replace(/\s+/g," ").trim();a.labels.north=Math.max(a.labels.north,(d.length+1)/2)}c=a.level.rlabels.trim().split("\n");for(b=0;b<c.length;b++)d=c[b].replace(/\s+/g," ").trim(),a.labels.west=Math.max(a.labels.west,(d.length+1)/2)}if(a.level.solution&&
!a.level.rlabels&&!a.level.clabels){c=[];for(var f=0;f<a.size.x;f++)c[f]=[];b=0;for(var e=a.level.solution.replace(/\s+/g," ").trim().split(" "),g=0;g<a.size.y;g++)for(f=0;f<a.size.x;f++)c[f][g]="o"==e[b]?1:"x"==e[b]?2:nil,b++;a.level.rlabels="";for(g=0;g<a.size.y;g++){d="";for(f=0;f<a.size.x;f++)1==c[f][g]?d+="o ":2==c[f][g]&&(d+="x ");a.labels.west=Math.max(a.labels.west,d.length/2);a.level.rlabels+=d+"\n"}a.level.clabels="";for(f=0;f<a.size.x;f++){d="";for(g=0;g<a.size.y;g++)1==c[f][g]?d+="o ":
2==c[f][g]&&(d+="x ");a.labels.north=Math.max(a.labels.north,d.length/2);a.level.clabels+=d+"\n"}}}catch(k){return ojdebug(k.toString()),"%"}};a.reset2=function(){try{for(var b=a.labels.west,c=a.labels.north,d=a.level.clabels.trim().split("\n"),f=0,e=a.labels.west;e<a.size.x;e++){var g=d[f++].replace(/\s+/g," ").trim().split(" ");var k=a.labels.north-g.length;for(var h=0;h<a.labels.north;h++)"o"==g[h]?a.board.c[e][h+k].label=1:"x"==g[h]&&(a.board.c[e][h+k].label=2)}d=a.level.rlabels.trim().split("\n");
f=0;for(h=a.labels.north;h<a.size.y;h++)for(g=d[f++].replace(/\s+/g," ").trim().split(" "),k=a.labels.west-g.length,e=0;e<a.labels.west;e++)"o"==g[e]?a.board.c[e+k][h].label=1:"x"==g[e]&&(a.board.c[e+k][h].label=2);if(a.level.solution){k=0;var l=a.level.solution.replace(/\s+/g," ").trim().split(" ");for(h=c;h<a.size.y;h++)for(e=b;e<a.size.x;e++){var n=a.board.c[e][h],m=l[k++];"."==m||"-"==m?n.solution=nil:"x"==m?n.solution=2:"o"==m&&(n.solution=1)}}a.reset2labels()}catch(p){return ojdebug(p.toString()),
"%"}};l=!1;a.check2=function(){try{for(var b=a.labels.west,c=a.labels.north,d=c;d<a.size.y;d++){for(var f=0;a.board.c[f][d].label==nil;)f++;for(var e=b;e<a.size.x;e++)a.board.c[e][d].value!=nil&&0!=a.board.c[e][d].value&&(f==b?a.board.c[e][d].error=1:a.board.c[e][d].value==a.board.c[f][d].label?f++:(a.board.c[e][d].error=1,a.board.c[f][d].error=1));for(e=f;e<b;e++)a.board.c[e][d].label!=nil&&(a.board.c[e][d].error=1)}for(e=b;e<a.size.x;e++){for(f=0;a.board.c[e][f].label==nil;)f++;for(d=c;d<a.size.y;d++)a.board.c[e][d].value!=
nil&&0!=a.board.c[e][d].value&&(a.board.c[e][d].value==a.board.c[e][f].label?f++:f==c?a.board.c[e][d].error=1:(a.board.c[e][d].error=1,a.board.c[e][f].error=1));for(d=f;d<c;d++)a.board.c[e][d].label!=nil&&(a.board.c[e][d].error=1)}for(e=b;e<a.size.x;e++)for(d=c;d<a.size.y;d++)1==a.board.c[e][d].value&&(e<a.size.x-1&&1==a.board.c[e+1][d].value&&(a.board.c[e][d].error=a.board.c[e+1][d].error=3),e<a.size.x-1&&d<a.size.y-1&&1==a.board.c[e+1][d+1].value&&(a.board.c[e][d].error=a.board.c[e+1][d+1].error=
3),d<a.size.y-1&&1==a.board.c[e][d+1].value&&(a.board.c[e][d].error=a.board.c[e][d+1].error=3),e>b&&d<a.size.y-1&&1==a.board.c[e-1][d+1].value&&(a.board.c[e][d].error=a.board.c[e-1][d+1].error=3));l=!1;a.checkPaired(1,1);l||(a.solved=!1)}catch(g){return ojdebug(g.toString()),"%"}};a.checkPaired=function(b,c){try{l||(1!=a.board.c[b][c].value||a.board.c[b][c].marked?a.check4(b,c):(1<b&&2==a.board.c[b-1][c].value&&!a.board.c[b-1][c].marked&&(a.board.c[b][c].marked=a.board.c[b-1][c].marked=!0,a.check4(b,
c),a.board.c[b][c].marked=a.board.c[b-1][c].marked=!1),b<a.size.x-1&&2==a.board.c[b+1][c].value&&!a.board.c[b+1][c].marked&&(a.board.c[b][c].marked=a.board.c[b+1][c].marked=!0,a.check4(b,c),a.board.c[b][c].marked=a.board.c[b+1][c].marked=!1),1<c&&2==a.board.c[b][c-1].value&&!a.board.c[b][c-1].marked&&(a.board.c[b][c].marked=a.board.c[b][c-1].marked=!0,a.check4(b,c),a.board.c[b][c].marked=a.board.c[b][c-1].marked=!1),c<a.size.y-1&&2==a.board.c[b][c+1].value&&!a.board.c[b][c+1].marked&&(a.board.c[b][c].marked=
a.board.c[b][c+1].marked=!0,a.check4(b,c),a.board.c[b][c].marked=a.board.c[b][c+1].marked=!1)))}catch(d){return ojdebug(d.toString()),"%"}};a.check4=function(b,c){try{if(c<a.size.y-1)a.checkPaired(b,c+1);else if(b<a.size.x-1)a.checkPaired(b+1,1);else for(l=!0,b=1;b<a.size.x;b++)for(c=1;c<a.size.y;c++)2!=a.board.c[b][c].value||a.board.c[b][c].marked||(l=!1)}catch(d){return ojdebug(d.toString()),"%"}};a.valueToString=function(a){switch(a){case 1:return"o";case 2:return"x";default:return"-"}};a.onValues=
function(){try{a.config.touch?a.enable.lines?(a.enable.lines=!1,a.enable.cells=!0):(a.enable.lines=!0,a.enable.cells=!1):Object.getPrototypeOf(this).onValues.call(this)}catch(b){return ojdebug(b.toString()),"%"}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):a.paintValueCell(b)}catch(c){return ojdebug(c.toString()),"%"}};a.paintLabelCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.label;c.fillRect(b.px,b.py,a.unit.x,a.unit.y);1==b.label&&a.paintTent(b);
2==b.label&&a.paintTree(b);b.error&&a.display.errors&&a.paintErrorCircle(b)}catch(d){return ojdebug(d.toString()),"%"}};a.paintValueCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.light[b.color];c.fillRect(b.px,b.py,a.unit.x,a.unit.y);a.paintSymbolMarkers(b);1==b.value?a.paintTent(b):2==b.value?a.paintTree(b):0==b.value&&a.paintCross(b);b.error&&a.display.errors&&(b.value==nil?a.paintErrorDot(b):a.paintErrorSquare(b))}catch(d){return ojdebug(d.toString()),"%"}};a.paintTree=
function(b,c){try{if(c=a.defaultParams(b,c)){b.px&&(b=a.canvas.getContext("2d"));c.scale||(c.scale=75);b.strokeStyle=c.stroke?c.stroke:a.uic.treeedge;b.fillStyle=c.fill?c.fill:a.uic.treefill;b.lineWidth=c.width?c.width:1;var d=c.w/7;b.beginPath();b.rect(c.x+c.w/2+.5-d/2,c.y+2*d,d,c.h-3*d);b.arc(c.x+c.w/2+.5-d,c.y+3*d,d,0,2*Math.PI);b.arc(c.x+c.w/2+.5,c.y+2*d,d,0,2*Math.PI);b.arc(c.x+c.w/2+.5+d,c.y+3*d,d,0,2*Math.PI);b.stroke();b.fill()}}catch(f){return ojdebug(f.toString()),"%"}};a.paintTent=function(b,
c){try{if(c=a.defaultParams(b,c)){b.px&&(b=a.canvas.getContext("2d"));c.scale||(c.scale=75);b.strokeStyle=c.stroke?c.stroke:a.uic.tentedge;b.fillStyle=c.fill?c.fill:a.uic.tentfill;b.lineWidth=c.width?c.width:1;var d=c.w/5;b.lineWidth=1;b.beginPath();b.moveTo(c.x+c.w/2,c.y+d);b.lineTo(c.x+c.w-d,c.y+c.h-d);b.lineTo(c.x+d,c.y+c.h-d);b.lineTo(c.x+c.w/2,c.y+d);b.fill();b.stroke()}}catch(f){return ojdebug(f.toString()),"%"}};a.paintCurrentValue=function(){try{var b=a.uie.value,c=b.getContext("2d");c.fillStyle=
a.uic.white;c.fillRect(0,0,b.width,b.height);c.fillStyle=a.uic.none;c.strokeStyle=a.uic.black;var d={x:0,y:0,w:b.width,h:b.height,scale:90};a.enable.lines&&!a.enable.cells?a.paintText("#",c,d):1==a.current.value||a.current.type!=a.item.cell?a.paintTent(c,d):2==a.current.value?a.paintTree(c,d):0==a.current.value&&a.paintCross(c,d)}catch(f){return ojdebug(f.toString()),"%"}}}Tents2.prototype=new Puzzle;
