function Tents(){var a=this;a.constructor();a.uis.puzzle=["Tents and Trees","Zeltlager"];a.labels.north=a.labels.west=1;a.charToValue=a.charToValue.concat(["t",1,"z",1,"a",1,"s",0,"d",nil,".",1,",",0,"-",nil,"o",1,"x",0,"/",nil]);a.cell.values=[1,0,nil];a.line.values=[a.line.cross,a.line.wall,a.line.grid];a.uic.treefill="#00bb00";a.uic.treeedge="#004400";a.uic.tentfill="#0000ff";a.uic.tentedge="#000000";a.enable.dragging=!0;a.enable.cells=!0;a.enable.lines=!a.config.touch;a.keypad.left=nil;a.cell.nilalias=
0;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{if(a.level.problem){var b=0;var c=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var d=0;d<a.size.y;d++)for(var e=0;e<a.size.x;e++){var f=a.board.c[e][d];var g=c[b++];"."==g||"-"==g?f.value=nil:"x"==g?f.value=2:"o"==g?f.value=1:"#"==g?f.value=0:f.label=parseInt(g);f.value!=nil&&(f.fixed=!0)}}if(a.level.solution)for(b=0,c=a.level.solution.replace(/\s+/g," ").trim().split(" "),d=1;d<a.size.y;d++)for(e=1;e<
a.size.x;e++)f=a.board.c[e][d],g=c[b++],"."==g||"-"==g?f.solution=nil:"x"==g?f.solution=2:"o"==g&&(f.solution=1);if(a.level.solution&&!a.level.problem){for(e=1;e<a.size.x;e++)a.board.c[e][0].label=0;for(d=1;d<a.size.y;d++)a.board.c[0][d].label=0;for(d=1;d<a.size.y;d++)for(e=1;e<a.size.x;e++)2==a.board.c[e][d].solution?(a.board.c[e][d].value=2,a.board.c[e][d].fixed=!0):1==a.board.c[e][d].solution&&(a.board.c[e][0].label++,a.board.c[0][d].label++)}a.reset2labels()}catch(k){throw a.exception(k),k;}};
var h=!1;a.check2=function(){try{for(var b=1;b<a.size.y;b++)if(a.board.c[0][b].label!=nil){var c=0;for(var d=1;d<a.size.x;d++)1==a.board.c[d][b].value&&c++;c!=a.board.c[0][b].label&&(a.board.c[0][b].error=1)}for(d=1;d<a.size.x;d++)if(a.board.c[d][0].label!=nil){c=0;for(b=1;b<a.size.y;b++)1==a.board.c[d][b].value&&c++;c!=a.board.c[d][0].label&&(a.board.c[d][0].error=1)}for(d=1;d<a.size.x;d++)for(b=1;b<a.size.y;b++)1==a.board.c[d][b].value&&(d<a.size.x-1&&1==a.board.c[d+1][b].value&&(a.board.c[d][b].error=
3,a.board.c[d+1][b].error=3),d<a.size.x-1&&b<a.size.y-1&&1==a.board.c[d+1][b+1].value&&(a.board.c[d][b].error=3,a.board.c[d+1][b+1].error=3),b<a.size.y-1&&1==a.board.c[d][b+1].value&&(a.board.c[d][b].error=3,a.board.c[d][b+1].error=3),1<d&&b<a.size.y-1&&1==a.board.c[d-1][b+1].value&&(a.board.c[d][b].error=3,a.board.c[d-1][b+1].error=3));h=!1;a.checkPaired(1,1);h||(a.solved=!1);for(d=1;d<a.size.x;d++)for(b=1;b<a.size.y;b++)if(1==a.board.c[d][b].value||2==a.board.c[d][b].value){var e=1==a.board.c[d][b].value?
2:1;1<d&&a.board.c[d-1][b].value==e||1<b&&a.board.c[d][b-1].value==e||d<a.size.x-1&&a.board.c[d+1][b].value==e||b<a.size.y-1&&a.board.c[d][b+1].value==e||(a.board.c[d][b].error=2)}}catch(f){throw a.exception(f),f;}};a.checkPaired=function(b,c){try{h||(1!=a.board.c[b][c].value||a.board.c[b][c].marked?a.check4(b,c):(1<b&&2==a.board.c[b-1][c].value&&!a.board.c[b-1][c].marked&&(a.board.c[b][c].marked=!0,a.board.c[b-1][c].marked=!0,a.check4(b,c),a.board.c[b][c].marked=!1,a.board.c[b-1][c].marked=!1),b<
a.size.x-1&&2==a.board.c[b+1][c].value&&!a.board.c[b+1][c].marked&&(a.board.c[b][c].marked=!0,a.board.c[b+1][c].marked=!0,a.check4(b,c),a.board.c[b][c].marked=!1,a.board.c[b+1][c].marked=!1),1<c&&2==a.board.c[b][c-1].value&&!a.board.c[b][c-1].marked&&(a.board.c[b][c].marked=!0,a.board.c[b][c-1].marked=!0,a.check4(b,c),a.board.c[b][c].marked=!1,a.board.c[b][c-1].marked=!1),c<a.size.y-1&&2==a.board.c[b][c+1].value&&!a.board.c[b][c+1].marked&&(a.board.c[b][c].marked=!0,a.board.c[b][c+1].marked=!0,a.check4(b,
c),a.board.c[b][c].marked=!1,a.board.c[b][c+1].marked=!1)))}catch(d){throw a.exception(d),d;}};a.check4=function(b,c){try{if(c<a.size.y-1)a.checkPaired(b,c+1);else if(b<a.size.x-1)a.checkPaired(b+1,1);else for(h=!0,b=1;b<a.size.x;b++)for(c=1;c<a.size.y;c++)2!=a.board.c[b][c].value||a.board.c[b][c].marked||(h=!1)}catch(d){throw a.exception(d),d;}};a.solve2=function(){try{for(var b=0;b<a.size.y;b++)if(0==a.board.c[0][b].label)for(var c=1;c<a.size.x;c++)a.board.c[c][b].value==nil&&(a.board.c[c][b].value=
0);for(c=0;c<a.size.x;c++)if(0==a.board.c[c][0].label)for(b=1;b<a.size.y;b++)a.board.c[c][b].value==nil&&(a.board.c[c][b].value=0);for(c=1;c<a.size.x;c++)for(b=1;b<a.size.y;b++)a.board.c[c][b].value!=nil||1<c&&2==a.board.c[c-1][b].value||1<b&&2==a.board.c[c][b-1].value||c<a.size.x-1&&2==a.board.c[c+1][b].value||b<a.size.y-1&&2==a.board.c[c][b+1].value||(a.board.c[c][b].value=0)}catch(d){throw a.exception(d),d;}};a.valueToString=function(a){switch(a){case 1:return"o";case 2:return"x";default:return"-"}};
a.onValues=function(){try{a.config.touch?a.enable.lines?(a.enable.lines=!1,a.enable.cells=!0):(a.enable.lines=!0,a.enable.cells=!1):Object.getPrototypeOf(this).onValues.call(this)}catch(b){throw a.exception(b),b;}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):a.paintValueCell(b)}catch(c){throw a.exception(c),c;}};a.paintLabelCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.label;c.fillRect(b.px,b.py,a.unit.x,a.unit.y);b.label!=nil&&a.paintText(b.label,
b);b.error&&a.display.errors&&a.paintErrorCircle(b)}catch(d){throw a.exception(d),d;}};a.paintValueCell=function(b){try{var c=a.canvas.getContext("2d");c.fillStyle=a.uic.light[b.color];c.fillRect(b.px,b.py,a.unit.x,a.unit.y);a.paintSymbolMarkers(b);1==b.value?a.paintTent(b):2==b.value?a.paintTree(b):0==b.value&&a.paintCross(b);b.error&&a.display.errors&&(b.value==nil?a.paintErrorDot(b):a.paintErrorSquare(b))}catch(d){throw a.exception(d),d;}};a.paintTree=function(b,c){try{if(c=a.defaultParams(b,c)){b.px&&
(b=a.canvas.getContext("2d"));c.scale||(c.scale=75);b.strokeStyle=c.stroke?c.stroke:a.uic.treeedge;b.fillStyle=c.fill?c.fill:a.uic.treefill;b.lineWidth=c.width?c.width:1;var d=c.w/7;b.beginPath();b.rect(c.x+c.w/2+.5-d/2,c.y+2*d,d,c.h-3*d);b.arc(c.x+c.w/2+.5-d,c.y+3*d,d,0,2*Math.PI);b.arc(c.x+c.w/2+.5,c.y+2*d,d,0,2*Math.PI);b.arc(c.x+c.w/2+.5+d,c.y+3*d,d,0,2*Math.PI);b.stroke();b.fill()}}catch(e){return ojdebug(e.toString()),"%"}};a.paintTent=function(b,c){try{if(c=a.defaultParams(b,c)){b.px&&(b=a.canvas.getContext("2d"));
c.scale||(c.scale=75);b.strokeStyle=c.stroke?c.stroke:a.uic.tentedge;b.fillStyle=c.fill?c.fill:a.uic.tentfill;b.lineWidth=c.width?c.width:1;var d=c.w/5;b.lineWidth=1;b.beginPath();b.moveTo(c.x+c.w/2,c.y+d);b.lineTo(c.x+c.w-d,c.y+c.h-d);b.lineTo(c.x+d,c.y+c.h-d);b.lineTo(c.x+c.w/2,c.y+d);b.fill();b.stroke()}}catch(e){return ojdebug(e.toString()),"%"}};a.paintCurrentValue=function(){try{var b=a.uie.value,c=b.getContext("2d");c.fillStyle=a.uic.white;c.fillRect(0,0,b.width,b.height);c.fillStyle=a.uic.none;
c.strokeStyle=a.uic.black;var d={x:0,y:0,w:b.width,h:b.height,scale:90};a.enable.lines&&!a.enable.cells?a.paintText("#",c,d):1==a.current.value||a.current.type!=a.item.cell?a.paintTent(c,d):0==a.current.value&&a.paintCross(c,d)}catch(e){throw a.exception(e),e;}}}Tents.prototype=new Puzzle;
