function Yagit(){var a=this;a.constructor();a.uis.puzzle=["Yagit (Wolves and Sheep)","Yagit (W\u00f6lfe und Schafe)"];var m=a.board.c,t=a.board.n,n=a.board.h,p=a.board.v,k=0,l=0,u={none:0,empty:1,node:2,loop:3,both:4};a.charToValue=a.charToValue.concat(["8",8,"2",2,"4",4,"6",1,"i",8,"m",2,"j",4,"k",1]);a.line.values=[a.line.grid,a.line.wall,a.line.cross];a.enable.lines=!0;a.enable.cells=!0;a.enable.nodes=!1;a.enable.pnodes=!0;a.enable.values=!1;a.keypad.left=nil;a.uic.dotfill="#000000";a.uic.dotedge=
"#000000";a.uic.wolffill="#88cc88";a.uic.wolfedge="#008800";a.uic.sheepfill="#8888ff";a.uic.sheepedge="#0000cc";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{k=a.size.x;l=a.size.y;if(a.level.problem){var b=0;var d=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var c=0;c<l;c++)for(var e=0;e<k;e++){var f=m[e][c];var g=d[b++];"-"==g||"."==g?f.label=nil:g.contains("s")?f.label=2:g.contains("w")?f.label=1:"@"==g&&(f.areas=a.cell.outside,f.label=cross,f.fixed=
!0,f.valid=!1);g.contains("x")&&(t[e+1][c+1].label=1)}}if(a.level.solution){b=0;d=a.level.solution.replace(/\s+/g," ").trim().split(" ");for(c=0;c<l;c++)for(e=0;e<k;e++)f=m[e][c],g=d[b++],f.count="."==g||"-"==g?0:parseInt(g);g=1;for(e=0;e<k;e++)for(c=0;c<l;c++){var q=m[e][c].count;if(0!=q){for(d=0;d<k;d++)for(b=0;b<l;b++)f=m[d][b],f.count==q&&(f.solution=g,f.count=0);g++}}for(e=1;e<k;e++)for(c=0;c<l;c++)p[e][c].solution=m[e][c].solution!=m[e-1][c].solution?a.line.wall:a.line.grid;for(c=1;c<l;c++)for(e=
0;e<k;e++)n[e][c].solution=m[e][c].solution!=m[e][c-1].solution?a.line.wall:a.line.grid}for(e=0;e<k;e++)n[e][0].valid=n[e][l].valid=!1,n[e][0].value=n[e][0].solution=n[e][l].value=n[e][l].solution=a.line.wall;for(c=0;c<l;c++)p[0][c].valid=p[k][c].valid=!1,p[0][c].value=p[0][c].solution=p[k][c].value=p[k][c].solution=a.line.wall}catch(r){throw a.exception(r),r;}};a.check2=function(){try{var b=1;for(var d=0;d<k;d++)for(var c=0;c<l;c++)0==m[d][c].count&&a.markArea(d,c,b++);for(d=0;d<k;d++)for(c=1;c<
l;c++)n[d][c].value==a.line.wall&&m[d][c-1].count==m[d][c].count&&(n[d][c].error=u.line);for(d=1;d<k;d++)for(c=0;c<l;c++)p[d][c].value==a.line.wall&&m[d-1][c].count==m[d][c].count&&(p[d][c].error=u.line);for(var e=1;e<b;e++){var f=null,g=null;for(d=0;d<k;d++)for(c=0;c<l;c++){var q=m[d][c];q.count==e&&(2==q.label?g=q:1==q.label&&(f=q))}if(!(f&&!g||g&&!f))for(d=0;d<k;d++)for(c=0;c<l;c++)if(q=m[d][c],q.count==e)f||g?q.label!=nil&&(q.error=u.both):q.error=u.empty}q=!0;for(d=1;d<k;d++)for(c=1;c<l;c++){var r=
t[d][c];1==r.label&&(b=0,n[r.x][r.y].value==a.line.wall&&b++,n[r.x-1][r.y].value==a.line.wall&&b++,p[r.x][r.y].value==a.line.wall&&b++,p[r.x][r.y-1].value==a.line.wall&&b++,0!=b&&2!=b&&(r.error=u.node,q=!1))}if(q){for(d=b=1;d<k;d++){var h=p[d][0];h.value==a.line.wall&&0==h.count&&a.markPath(8,h,b++);h=p[d][l-1];h.value==a.line.wall&&0==h.count&&a.markPath(2,h,b++)}for(c=1;c<l;c++)h=n[0][c],h.value==a.line.wall&&0==h.count&&a.markPath(4,h,b++),h=n[k-1][c],h.value==a.line.wall&&0==h.count&&a.markPath(1,
h,b++);for(e=0;e<a.board.l.length;e++)h=a.board.l[e],h.value==a.line.wall&&0==h.count&&0!=h.x&&0!=h.y&&h.x!=k&&h.y!=l?(h.error=u.loop,h.count=1):h.count=0}}catch(v){throw a.exception(v),v;}};a.markArea=function(b,d,c){try{m[b][d].count=c,0!=b&&0==m[b-1][d].count&&p[b][d].value!=a.line.wall&&a.markArea(b-1,d,c),b!=k-1&&0==m[b+1][d].count&&p[b+1][d].value!=a.line.wall&&a.markArea(b+1,d,c),0!=d&&0==m[b][d-1].count&&n[b][d].value!=a.line.wall&&a.markArea(b,d-1,c),d!=l-1&&0==m[b][d+1].count&&n[b][d+1].value!=
a.line.wall&&a.markArea(b,d+1,c)}catch(e){throw a.exception(e),e;}};a.markPath=function(b,d,c){try{var e=d.x,f=d.y;8==b&&f++;4==b&&e++;for(d.count=c;;){var g=t[e][f];if(e<k&&(4==b&&1!=g.label||1!=b&&1==g.label&&n[e][f].value==a.line.wall)){d=n[e][f];if(0!=d.count)break;d.count=c;b=4;e++}else if(f<l&&(8==b&&1!=g.label||2!=b&&1==g.label&&p[e][f].value==a.line.wall)){d=p[e][f];if(0!=d.count)break;d.count=c;b=8;f++}else if(0<e&&(1==b&&1!=g.label||4!=b&&1==g.label&&n[e-1][f].value==a.line.wall)){d=n[e-
1][f];if(0!=d.count)break;d.count=c;b=1;e--}else if(0<f&&(2==b&&1!=g.label||8!=b&&1==g.label&&p[e][f-1].value==a.line.wall)){d=p[e][f-1];if(0!=d.count)break;d.count=c;b=2;f--}else break}}catch(q){throw a.exception(q),q;}};a.makeMove2=function(b,d,c){try{Object.getPrototypeOf(this).makeMove2.call(this,b,d,c);if(b.type==a.item.hline){for(var e=b.x;e<k-1&&1!=t[e+1][b.y].label;e++)n[e+1][b.y].value=b.value;for(e=b.x;0<e&&1!=t[e][b.y].label;e--)n[e-1][b.y].value=b.value}if(b.type==a.item.vline){for(var f=
b.y;f<l-1&&1!=t[b.x][f+1].label;f++)p[b.x][f+1].value=b.value;for(f=b.y;0<f&&1!=t[b.x][f].label;f--)p[b.x][f-1].value=b.value}}catch(g){throw a.exception(g),g;}};a.cleanSolution=function(){try{for(var b=0;b<l;b++)for(var d=0;d<k;d++){var c=m[d][b];c.value=c.count}}catch(e){throw a.exception(e),e;}};a.showSolution2=function(){try{for(var b=0;b<a.board.a.length;b++){var d=a.board.a[b];d.value=d.solution}}catch(c){throw a.exception(c),c;}};a.paintCell=function(b){try{var d=a.canvas.getContext("2d");
d.fillStyle=a.paintToImage&&a.solved?a.uic.light[b.value%9+1]:a.uic.light[b.color];d.fillRect(b.px,b.py,a.unit.x,a.unit.y);if(1==b.label){var c={scale:50};c.fill=a.uic.wolffill;c.stroke=b.error&&a.display.errors?a.uic.error:a.uic.wolfedge;a.paintSquare(b,c)}else 2==b.label&&(c={scale:50},c.fill=a.uic.sheepfill,c.stroke=b.error&&a.display.errors?a.uic.error:a.uic.sheepedge,a.paintCircle(b,c));a.paintSymbolMarkers(b);b.error&&a.display.errors&&b.label==nil&&a.paintErrorDot(b)}catch(e){throw a.exception(e),
e;}};a.paintNode=function(b){try{if(b.label!=nil){var d=a.canvas.getContext("2d");d.fillStyle=b.error&&a.display.errors?a.uic.error:a.uic.dotfill;d.strokeStyle=a.uic.dotedge;d.lineWidth=1;d.beginPath();d.arc(b.px,b.py,a.unit.x/8,0,2*Math.PI);d.fill();d.stroke()}}catch(c){throw a.exception(c),c;}}}Yagit.prototype=new Puzzle;
