var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,h){a!=Array.prototype&&a!=Object.prototype&&(a[f]=h.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var f=0;return $jscomp.iteratorPrototype(function(){return f<a.length?{done:!1,value:a[f++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,f){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var h=0,g={next:function(){if(h<a.length){var m=h++;return{value:f(m,a[m]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(a,f,h,g){if(f){h=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var m=a[g];m in h||(h[m]={});h=h[m]}a=a[a.length-1];g=h[a];f=f(g);f!=g&&null!=f&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:f})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,h,g){var f=this.length||0;0>h&&(h=Math.max(0,f+h));if(null==g||g>f)g=f;g=Number(g);0>g&&(g=Math.max(0,f+g));for(h=Number(h||0);h<g;h++)this[h]=a;return this}},"es6","es3");
function Fillomino(){var a=this;a.constructor();a.uis.puzzle=["Fillomino (Optimizer)"];var f=a.board.c,h=0,g=0;a.enable.cells=!0;a.enable.lines=!a.config.touchscreen;a.enable.dragging=!0;a.enable.tilt=!1;a.enable.hint=!1;a.enable.colors=!1;a.enable.smarkers=!1;a.enable.values=!0;a.keypadValues=a.keypad.numbers;a.score.label=a.uis.get("score");a.score.optimize=a.score.maximize;a.isNewSolution=a.isNewSolutionGame;a.uic.done="#dddddd";a.cell.min=1;a.cell.max=9;a.keys=a.keys.concat(["fill"]);a.line.values=
[a.line.wall,a.line.cross,a.line.grid];a.charToValue=["/",nil,"-",nil,",",nil];a.infoText="\u2022";var m=null,n=null;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.run2=function(){try{a.config.mode==a.config.modeGame&&(a.level.size=(8).toString(),a.level.depth=(5).toString()),Object.getPrototypeOf(this).run2.call(this)}catch(b){throw a.exception(b),b;}};a.reset2=function(){try{h=a.size.x;g=a.size.y;a.cell.max=a.level.depth?parseInt(a.level.depth):9;a.score.optimize=a.level.variant?"minimize"==
a.level.variant?a.score.minimize:a.score.maximize:a.score.maximize;if(a.level.problem){var b=0;var d=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var c=0;c<a.size.y;c++)for(var e=0;e<a.size.x;e++){var k=f[e][c];var l=d[b++];"."==l||"-"==l?k.value=nil:"a"<=l&&"z">=l?k.label=l.charCodeAt(0)-96:"A"<=l&&"Z">=l?k.label=l.charCodeAt(0)-64:k.value=parseInt(l);k.value!=nil&&(k.fixed=!0)}}if(a.level.solution)for(b=0,d=a.level.solution.replace(/\s+/g," ").trim().split(" "),c=0;c<a.size.y;c++)for(e=
0;e<a.size.x;e++)k=f[e][c],l=d[b++],k.solution="."==l||"-"==l||"0"==l?nil:parseInt(l);if(a.level.lines)for(b=0,d=a.level.lines.replace(/\s+/g," ").trim().split(" "),c=0;c<a.size.y;c++)for(e=0;e<a.size.x;e++)l=d[b++],0!=(l&4)&&(f[e][c].value=a.line.wall,f[e][c].fixed=!0),0!=(l&1)&&(f[e+1][c].value=a.line.wall,f[e+1][c].fixed=!0),0!=(l&8)&&(f[e][c].value=a.line.wall,f[e][c].fixed=!0),0!=(l&2)&&(f[e][c+1].value=a.line.wall,f[e][c+1].fixed=!0);for(e=0;e<a.size.x-1;e++)for(c=0;c<a.size.y;c++)if(1==a.board.c[e][c].value||
1==a.board.c[e+1][c].value||a.board.c[e][c].value!=nil&&a.board.c[e+1][c].value!=nil&&a.board.c[e][c].value!=a.board.c[e+1][c].value)a.board.v[e+1][c].value=a.line.wall,a.board.v[e+1][c].fixed=a.board.v[e+1][c].auto=!0;for(e=0;e<a.size.x;e++)for(c=0;c<a.size.y-1;c++)if(1==a.board.c[e][c].value||1==a.board.c[e][c+1].value||a.board.c[e][c].value!=nil&&a.board.c[e][c+1].value!=nil&&a.board.c[e][c].value!=a.board.c[e][c+1].value)a.board.h[e][c+1].value=a.line.wall,a.board.h[e][c+1].fixed=a.board.h[e][c+
1].auto=!0;for(e=0;e<a.size.x;e++)a.board.h[e][0].valid=!1,a.board.h[e][a.size.y].valid=!1;for(c=0;c<a.size.y;c++)a.board.v[0][c].valid=!1,a.board.v[a.size.x][c].valid=!1}catch(p){throw a.exception(p),p;}};a.make2=function(){try{h=a.size.x;g=a.size.y;for(var b=h*g*parseInt(a.level.fill)/100,d=0;d<b;){var c=a.random.getInt(h),e=a.random.getInt(g);f[c][e].value==nil&&(f[c][e].value=a.random.getInt(a.size.z)+1,d++)}b="";for(d=0;d<g;d++)for(c=0;c<h;c++)b=f[c][d].value==nil?b+"- ":b+(parseInt(f[c][d].value)+
" ");a.level.problem=b;a.level.author="Otto Janko";a.level.source="Script/Gen";a.level.info=a.level.seed}catch(k){throw a.exception(k),k;}};a.check2=function(){try{for(var b=0;b<a.size.x;b++)for(var d=0;d<a.size.y;d++){var c=f[b][d];c.value==nil?c.error=1:c.checked||(checkNum=0,a.check3values(b,d,c.value),checkNum!=c.value&&a.check3markers(b,d,c.value))}for(b=a.score.current=0;b<h;b++)for(d=0;d<g;d++)c=f[b][d],c.value!=nil&&(d<g-1&&f[b][d+1].value!=nil&&(a.score.current+=Math.abs(f[b][d+1].value-
c.value)),b<h-1&&f[b+1][d].value!=nil&&(a.score.current+=Math.abs(f[b+1][d].value-c.value)))}catch(e){throw a.exception(e),e;}};a.check3values=function(b,d,c){try{f[b][d].checked=!0,checkNum++,0<b&&(f[b-1][d].checked||f[b-1][d].value!=c||a.check3values(b-1,d,c)),0<d&&(f[b][d-1].checked||f[b][d-1].value!=c||a.check3values(b,d-1,c)),b<h-1&&(f[b+1][d].checked||f[b+1][d].value!=c||a.check3values(b+1,d,c)),d<g-1&&(f[b][d+1].checked||f[b][d+1].value!=c||a.check3values(b,d+1,c))}catch(e){throw a.exception(e),
e;}};a.check3markers=function(b,d,c){try{f[b][d].error=3,0<b&&(f[b-1][d].error||f[b-1][d].value!=c||a.check3markers(b-1,d,c)),0<d&&(f[b][d-1].error||f[b][d-1].value!=c||a.check3markers(b,d-1,c)),b<h-1&&(f[b+1][d].error||f[b+1][d].value!=c||a.check3markers(b+1,d,c)),d<g-1&&(f[b][d+1].error||f[b][d+1].value!=c||a.check3markers(b,d+1,c))}catch(e){throw a.exception(e),e;}};a.onValues=function(){try{a.config.touchscreen?a.enable.lines?(a.enable.lines=!1,a.enable.cells=!0):(a.enable.lines=!0,a.enable.cells=
!1):Object.getPrototypeOf(this).onValues.call(this)}catch(b){throw a.exception(b),b;}};a.onRun=function(){try{if(a.config.mode==a.config.modeGame&&(a.enable.make=!0),Object.getPrototypeOf(this).onRun.call(this),a.config.mode==a.config.modeGame){for(var b=document.createElement("select"),d=6;14>=d;d+=1){var c=document.createElement("option");c.value=d.toString();c.textContent=d.toString()+"\u00d7"+d.toString();b.appendChild(c)}b.value=8;b.style.position="relative";b.style.top="-6px";a.uie.toolbar.insertBefore(b,
a.uie.make);m=b;b=document.createElement("select");for(d=2;9>=d;d+=1)c=document.createElement("option"),c.value=d.toString(),c.textContent="Zahlen: "+d.toString(),b.appendChild(c);b.value=5;b.style.position="relative";b.style.top="-6px";a.uie.toolbar.insertBefore(b,a.uie.make);n=b}}catch(e){throw a.exception(e),e;}};a.onMake=function(b){try{a.enable.make&&(a.level.depth=n.value,a.level.rows=a.level.cols=m.value,a.setup())}catch(d){throw a.exception(d),d;}};a.onDisplayScores2=function(b){try{b='<table class="scores">\n';
b+=" <tr>\n  <th>Nr.</th>\n  <th>Rekord von</th>\n  <th>"+a.score.label+"</th>\n </tr>\n";for(var d=0;d<a.levels.length;d++){a.select(d);if(0<a.level.score&&a.level.solution)try{a.server.timingSent=!0,a.showSolution(),a.check(),a.solved?a.score.high!=a.score.current&&(b="<p>ERROR \u2013 INVALID SCORE: "+(d+1)+"</p>\n"+b):b="<p>ERROR \u2013 NOT SOLVED: "+(d+1)+"</p>\n"+b}catch(k){b="<p>EXCEPTION: "+(d+1)+"</p>\n"+b}var c=a.config.documentName,e=c.lastIndexOf("/");c=c.substring(e+1)+"?level=";b+=' <tr>\n  <td><a href="'+
c+(d+1)+'">'+(d+1)+"</a></td>\n  <td>"+(a.level.solver?a.level.solver:"-")+"</td>\n  <td>"+(a.level.score?a.level.score:"-")+"</td>\n </tr>\n"}new ojpopup(b+"</table>\n");a.select(0)}catch(k){throw a.exception(k),k;}finally{a.hideSpinner()}};a.paintInfo=function(b){try{b="";if(a.score.optimize=a.score.maximize)b="MAX";else if(a.score.optimize=a.score.maximize)b="MIN";0!=b.length&&(b=a.uis.get("goal")+": "+b+" \u2022 ");b+=a.score.label+": "+a.score.current+" ("+a.score.best+") ["+a.score.high+"] ";
Object.getPrototypeOf(this).paintInfo.call(this,b)}catch(d){throw a.exception(d),d;}};a.paintCell=function(b){try{var d=a.canvas.getContext("2d");d.fillStyle=a.paintToImage&&a.solved?9<b.value?a.uic.light[0]:a.uic.light[b.value%9+1]:a.paintToImage&&a.moves.current==nil?a.uic.white:b.error?a.uic.light[b.color]:a.uic.done;d.fillRect(b.px,b.py,a.unit.x,a.unit.y);if(!b.error&&0!=b.color){d.save();d.beginPath();d.rect(b.px,b.py,a.unit.x,a.unit.y);d.clip();d.beginPath();d.strokeStyle=a.uic.light[b.color];
for(var c=5;c<2*a.unit.x;c+=5)d.moveTo(b.px+c,b.py),d.lineTo(b.px,b.py+c);d.stroke();d.restore()}a.paintSymbolMarkers(b);var e=b.fixed?a.uic.clue:a.uic.text;a.paintToImage&&a.moves.current==nil||b.value!=nil&&a.paintText(b.value.toString(),b,{color:e});0!=b.error&&a.display.errors&&(b.value!=nil?a.paintErrorCircle(b):a.paintErrorDot(b))}catch(k){throw a.exception(k),k;}};a.paintLine=function(b){try{if(a.paintToImage&&a.moves.current==nil){var d=b.value;b.auto&&(b.value=a.line.grid)}else{d=b.value;
var c=b.x,e=b.y;if(!b.fixed)if(b.type==a.item.vline)if(1==a.board.c[c-1][e].value||1==a.board.c[c][e].value)b.value=a.line.wall;else if(a.board.c[c-1][e].value==a.board.c[c][e].value)a.board.c[c][e].value!=nil&&(b.value=a.line.none);else if(a.board.c[c-1][e].value!=nil&&a.board.c[c][e].value!=nil)b.value=a.line.wall;else{if(a.board.c[c-1][e].value!=nil&&!a.board.c[c-1][e].error||a.board.c[c][e].value!=nil&&!a.board.c[c][e].error)b.value=a.line.wall}else if(b.type==a.item.hline)if(1==a.board.c[c][e-
1].value||1==a.board.c[c][e].value)b.value=a.line.wall;else if(a.board.c[c][e-1].value==a.board.c[c][e].value)a.board.c[c][e].value!=nil&&(b.value=a.line.none);else if(a.board.c[c][e-1].value!=nil&&a.board.c[c][e].value!=nil)b.value=a.line.wall;else if(a.board.c[c][e-1].value!=nil&&!a.board.c[c][e-1].error||a.board.c[c][e].value!=nil&&!a.board.c[c][e].error)b.value=a.line.wall}Object.getPrototypeOf(this).paintLine.call(this,b);b.value=d}catch(k){throw a.exception(k),k;}};a.paintCurrentValue=function(){try{var b=
a.uie.value,d=b.getContext("2d");d.fillStyle=a.uic.white;d.fillRect(0,0,b.width,b.height);d.fillStyle=a.uic.none;d.strokeStyle=a.uic.black;var c={x:0,y:0,w:b.width,h:b.height,scale:90};a.enable.lines&&!a.enable.cells?a.paintText("#",d,c):a.current.type!=a.item.cell?a.paintText("1",d,c):a.current.value!=nil&&a.paintText(a.current.value.toString(),d,c)}catch(e){throw a.exception(e),e;}}}Fillomino.prototype=new Puzzle;
