function SameGame(){var a=this;a.constructor();a.uis.puzzle=["Same Game"];var f=a.board.c,l=0,k=0;a.enable.hint=!1;a.enable.check=!1;a.enable.colors=!1;a.enable.smarkers=!1;a.enable.values=!1;a.enable.pgrid=!0;a.enable.pgridlines=!1;a.keypad.left=nil;a.keypad.right=nil;a.moves.collapse=!1;a.uim.cellCursor=3;a.score.label=a.uis.get("score");a.score.optimize=a.score.maximize;a.solutionToString=a.solutionToStringGame;a.showSolution=a.showSolutionGame;a.isNewSolution=a.isNewSolutionGame;a.infoText="\u2022";
var p=null,q=null,m=0;a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.run2=function(){try{a.config.mode==a.config.modeGame&&(a.level.size=(6).toString(),a.level.depth=(4).toString()),Object.getPrototypeOf(this).run2.call(this)}catch(b){throw a.exception(b),b;}};a.reset2=function(){try{l=a.size.x;k=a.size.y;if(a.level.problem)for(var b=0,c=a.level.problem.replace(/\s+/g," ").trim().split(" "),d=0;d<k;d++)for(var e=0;e<l;e++){var h=f[e][d],g=c[b++];h.value=parseInt(g)}a.level.solution?a.level.moves=
a.level.solution:a.level.moves&&(a.level.solution=a.level.moves)}catch(n){throw a.exception(n),n;}};a.make2=function(){try{for(var b="",c=0;c<a.size.y;c++)for(var d=0;d<a.size.x;d++)b+=a.random.getInt(a.size.z)+" ";a.level.problem=b;a.level.author="Otto Janko";a.level.source="Script/Gen";a.level.info=a.level.seed}catch(e){throw a.exception(e),e;}};a.check2=function(){try{if(a.solved=f[0][k-1].value==nil,!a.solved){a.solved=!0;var b=0;a:for(;b<l;b++)for(var c=0;c<k;c++){var d=f[b][c].value;if(d!=nil){var e=
0;0<b&&f[b-1][c].value==d&&e++;0<c&&f[b][c-1].value==d&&e++;b<l-1&&f[b+1][c].value==d&&e++;c<k-1&&f[b][c+1].value==d&&e++;if(0!=e){a.solved=!1;break a}}}}}catch(h){throw a.exception(h),h;}};a.movesToString=function(){try{for(var b="",c="",d=0;d<a.moves.current+1;d++){var e=a.moves.list[d].split(",");c+=(parseInt(e[1])*k+parseInt(e[2])).toString()+",";if(50<c.length||d==a.moves.current)b+=c+"\n",c=""}return b}catch(h){throw a.exception(h),h;}};a.movesFromString=function(b){try{a.checking.disable++;
a.reset();a.moves.current=-1;a.moves.last=-1;b=b.replace(/[\s,;]+/g," ").trim();for(var c=b.split(" "),d=0;d<c.length;d++){var e=parseInt(c[d]);a.makeMove(f[Math.floor(e/k)][e%k],0,0)}}catch(h){ojdebug("Movelist: "+d+"\n",b),a.exception(h)}finally{a.checking.disable--}};a.makeMove2=function(b,c,d){try{if(!a.solved&&b.value!=nil){m=0;var e=b.value;a.makeMove3(b.x,b.y,b.value);if(1==m)b.value=e;else{a.score.current+=m*(m+1)/2;b.value=0;Object.getPrototypeOf(this).makeMove2.call(this,b,nil,d);for(b=
0;b<l;b++){var h=k-1;for(var g=k-1;0<=g;g--)f[b][g].value!=nil&&(f[b][h--].value=f[b][g].value);for(g=h;0<=g;g--)f[b][g].value=nil}for(b=h=0;b<l;b++)if(f[b][k-1].value!=nil){for(g=0;g<k;g++)f[h][g].value=f[b][g].value;h++}for(b=h;b<l;b++){for(g=0;g<k;g++)f[b][g].value=nil;h++}}}}catch(n){throw a.exception(n),n;}};a.makeMove3=function(b,c,d){try{f[b][c].value=nil,m++,0<b&&f[b-1][c].value==d&&a.makeMove3(b-1,c,d),0<c&&f[b][c-1].value==d&&a.makeMove3(b,c-1,d),b<l-1&&f[b+1][c].value==d&&a.makeMove3(b+
1,c,d),c<k-1&&f[b][c+1].value==d&&a.makeMove3(b,c+1,d)}catch(e){throw a.exception(e),e;}};a.onRun=function(){try{if(a.config.mode==a.config.modeGame&&(a.enable.make=!0),Object.getPrototypeOf(this).onRun.call(this),a.config.mode==a.config.modeGame){for(var b=document.createElement("select"),c=4;10>=c;c+=1){var d=document.createElement("option");d.value=c.toString();d.textContent=c.toString()+"\u00d7"+c.toString();b.appendChild(d)}b.value=6;b.style.position="relative";b.style.top="-6px";a.uie.toolbar.insertBefore(b,
a.uie.make);p=b;b=document.createElement("select");for(c=3;8>=c;c+=1)d=document.createElement("option"),d.value=c.toString(),d.textContent="Farben: "+c.toString(),b.appendChild(d);b.value=4;b.style.position="relative";b.style.top="-6px";a.uie.toolbar.insertBefore(b,a.uie.make);q=b}}catch(e){throw a.exception(e),e;}};a.onMake=function(b){try{a.enable.make&&(a.level.depth=q.value,a.level.rows=a.level.cols=p.value,a.setup())}catch(c){throw a.exception(c),c;}};a.paintInfo=function(b){try{b=a.uis.get("score")+
": "+a.score.current+" ("+a.score.best+") ["+a.score.high+"] ",Object.getPrototypeOf(this).paintInfo.call(this,b)}catch(c){throw a.exception(c),c;}};a.paintCell=function(b){try{var c=a.canvas.getContext("2d");c.save();if(b.value==nil)c.fillStyle=a.uic.gray;else{var d=c.createRadialGradient(b.px+a.unit.x/2,b.py+a.unit.y/2,0,b.px+a.unit.x/2,b.py+a.unit.y/2,a.unit.x);d.addColorStop(0,"#eeeeee");d.addColorStop(.4,a.uic.light[b.value+1]);d.addColorStop(1,a.uic.dark[b.value+1]);c.fillStyle=d}c.fillRect(b.px,
b.py,a.unit.x,a.unit.y);c.restore();b.value!=nil&&(c.lineWidth=2,c.beginPath(),c.strokeStyle=a.uic.buttonBorderLight,dx=0==b.x?2:1,dy=0==b.y?2:1,c.moveTo(b.px+dx,b.py+a.unit.y-1),c.lineTo(b.px+dx,b.py+dy),c.lineTo(b.px+a.unit.x-dx,b.py+dy),c.stroke(),c.beginPath(),c.strokeStyle=a.uic.buttonBorderDark,dy=dx=1,c.moveTo(b.px+a.unit.x-dx,b.py+dy),c.lineTo(b.px+a.unit.x-dx,b.py+a.unit.y-dy),c.lineTo(b.px+ +dx,b.py+a.unit.y-dy),c.stroke())}catch(e){throw a.exception(e),e;}}}SameGame.prototype=new Puzzle;
