var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,n){a!=Array.prototype&&a!=Object.prototype&&(a[e]=n.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,n,q){if(e){n=$jscomp.global;a=a.split(".");for(q=0;q<a.length-1;q++){var t=a[q];t in n||(n[t]={});n=n[t]}a=a[a.length-1];q=n[a];e=e(q);e!=q&&null!=e&&$jscomp.defineProperty(n,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,n,q){var e=this.length||0;0>n&&(n=Math.max(0,e+n));if(null==q||q>e)q=e;q=Number(q);0>q&&(q=Math.max(0,e+q));for(n=Number(n||0);n<q;n++)this[n]=a;return this}},"es6","es3");
function TiltMaze(){var a=this;a.constructor();a.uis.puzzle=["Jump Maze","Sprunglabyrinth"];var e=a.board.c,n=a.board.h,q=a.board.v,t=0,u=0,v=!1,z=!1,w=!1,A=!1,x=!1;a.enable.dragging=!0;a.enable.swiping=!0;a.enable.tilt=!0;a.enable.hint=!1;a.enable.check=!1;a.enable.colors=!1;a.enable.smarkers=!1;a.enable.values=!1;a.enable.plines=!0;a.enable.pcursor=!1;a.keypad.left=nil;a.keypad.right=nil;a.moves.collapse=!1;a.score.label=a.uis.get("moves");a.score.optimize=a.score.minimize;a.solutionToString=a.solutionToStringGame;
a.isNewSolution=a.isNewSolutionGame;a.showSolution=a.showSolutionGame;a.labels.north=a.labels.south=a.labels.east=a.labels.west=1;a.uic.ballFill="#cc0000";a.uic.ballEdge="#660000";a.uic.goalEdge="#000000";a.uic.goalFill=a.uic.none;a.uic.arrowFill="#ffffff";a.uic.arrowEdge="#000000";a.infoText="\u2022";a.init=function(){Object.getPrototypeOf(a).init.call(a)};a.reset2=function(){try{t=a.size.x-a.labels.east;u=a.size.y-a.labels.south;a.level.options.contains("noborder");v=a.level.options.contains("multitarget");
A=a.level.options.contains("singletarget");z=a.level.options.contains("killertarget");w=a.level.options.contains("stoppertarget");x=a.level.options.contains("onestep");a.level.areas&&a.reset2areas(1,1,t,u,a.level.areas);a.reset2labels(!0,!1);a.level.lines&&a.reset2lines(1,1,t,u,a.level.lines);if(a.level.problem&&!a.level.lines&&!a.level.labels){var b=0;var d=a.level.problem.replace(/\s+/g," ").trim().split(" ");for(var f=1;f<u;f++)for(var c=1;c<t;c++){var r=e[c][f];var l=parseInt(d[b++]);var g=Math.floor(l/
100);0!=g&&(r.label=g);g=Math.floor(l%100/10);0!=g&&(r.value=g);g=l%10;0!=(g&8)&&(n[c][f].value=a.line.wall);0!=(g&2)&&(n[c][f+1].value=a.line.wall);0!=(g&4)&&(q[c][f].value=a.line.wall);0!=(g&1)&&(q[c+1][f].value=a.line.wall)}}if(a.level.problem&&(a.level.lines||a.level.labels))for(d=a.level.problem.replace(/\s+/g," ").trim().split(" "),b=0,f=1;f<u;f++)for(c=1;c<t;c++)r=e[c][f],l=d[b++],"-"==l||"."==l?r.value=nil:l.contains("x")?(g=l.replace("x",""),r.label=parseInt(g)):r.value=parseInt(l);if(a.level.labels)for(d=
a.level.labels.replace(/\s+/g," ").trim().split(" "),b=0,f=1;f<u;f++)for(c=1;c<t;c++)r=e[c][f],l=d[b++],"-"==l||"."==l?r.label=nil:"x"==l||"b"==l?(r.label=-2,q[c][f].value=q[c+1][f].value=n[c][f].value=n[c][f+1].value=a.line.wall):r.label="o"==l||"k"==l?-3:"#"==l||"s"==l?-4:parseInt(l);a.level.solution?a.level.moves=a.level.solution:a.level.moves&&(a.level.solution=a.level.moves)}catch(h){throw a.exception(h),h;}};a.check2=function(){try{for(var b=1;b<t;b++)for(var d=1;d<u;d++){var f=e[b][d];if(v&&
f.label!=nil){a.solved=!1;return}if(-3==f.label&&f.value!=nil){a.solved=!0;a.result.code=a.result.lost;return}if(0<f.label&&f.label!=e[b][d].value){a.solved=!1;f.value!=nil&&z&&(a.solved=!0,a.result.code=a.result.lost);return}}}catch(c){throw a.exception(c),c;}};a.dragToDxDy=function(b,d,f){a.moveToDxDy(b,d,f)};a.moveToDxDy=function(b,d){try{0<b&&a.makeMove(e[1][1],1,0),0<d&&a.makeMove(e[1][1],2,0),0>b&&a.makeMove(e[1][1],4,0),0>d&&a.makeMove(e[1][1],8,0)}catch(f){throw a.exception(f),f;}};a.makeMove2=
function(b,d,f){var c;try{var r=function(a,b,c,d){if(a!=c||b!=d)if(c=e[c][d],c.value=e[a][b].value,e[a][b].value=nil,l=!0,A&&c.value==c.label){d=0;for(a=t-1;1<=a;a--)for(b=1;b<u;b++)e[a][b].value==c.value&&d++;1<d&&(c.value=nil)}};if(!a.solved&&(d&&d!=nil||(0!=b.y&&b.y!=a.size.y-1&&(0==b.x&&(d=4),b.x==a.size.x-1&&(d=1)),0!=b.x&&b.x!=a.size.x-1&&(0==b.y&&(d=8),b.y==a.size.y-1&&(d=2))),d&&d!=nil)){var l=!1;switch(d){case 1:for(var g=t-1;1<=g;g--)for(var h=1;h<u;h++)if(e[g][h].value!=nil){var k=g;for(c=
h;;){var m=e[k][c];v&&m.label==e[g][h].value&&(m.label=nil);if(k==t-1)break;if(e[k+1][c].value!=nil)break;if(-4==m.label)break;if(-3==m.label)break;if(0<m.label&&w)break;if(q[k+1][c].value==a.line.wall)break;k++;if(x)break}r(g,h,k,c)}break;case 4:for(g=1;g<t;g++)for(h=1;h<u;h++)if(e[g][h].value!=nil){k=g;for(c=h;;){m=e[k][c];v&&m.label==e[g][h].value&&(m.label=nil);if(1==k)break;if(e[k-1][c].value!=nil)break;if(-4==m.label)break;if(-3==m.label)break;if(0<m.label&&w)break;if(q[k][c].value==a.line.wall)break;
k--;if(x)break}r(g,h,k,c)}break;case 2:for(g=1;g<t;g++)for(h=u-1;1<=h;h--)if(e[g][h].value!=nil){k=g;for(c=h;;){m=e[k][c];v&&m.label==e[g][h].value&&(m.label=nil);if(c==u-1)break;if(e[k][c+1].value!=nil)break;if(-4==m.label)break;if(-3==m.label)break;if(0<m.label&&w)break;if(n[k][c+1].value==a.line.wall)break;c++;if(x)break}r(g,h,k,c)}break;case 8:for(g=1;g<t;g++)for(h=1;h<u;h++)if(e[g][h].value!=nil){k=g;for(c=h;;){m=e[k][c];v&&m.label==e[g][h].value&&(m.label=nil);if(1==c)break;if(e[k][c-1].value!=
nil)break;if(-4==m.label)break;if(-3==m.label)break;if(0<m.label&&w)break;if(n[k][c].value==a.line.wall)break;c--;if(x)break}r(g,h,k,c)}}if(l){var y=b.value;b.value=nil;Object.getPrototypeOf(this).makeMove2.call(this,b,d,f);b.value=y;a.score.current++}}}catch(B){throw a.exception(B),B;}};a.movesToString=function(){try{for(var b="",d="",f=0;f<a.moves.current+1;f++){var c=a.moves.list[f].split(",");switch(parseInt(c[3])){case 8:d+="n";break;case 2:d+="s";break;case 1:d+="e";break;case 4:d+="w"}if(50<
d.length||f==a.moves.current)b+=d+"\n",d=""}return b}catch(r){throw a.exception(r),r;}};a.movesFromString=function(b){try{a.checking.disable++;a.reset();a.moves.current=-1;a.moves.last=-1;b=b.replace(/[\s,;]+/g,"").trim().toLowerCase();for(var d=0;d<b.length;d++){var f=nil;switch(b[d]){case "e":f=1;break;case "w":f=4;break;case "s":f=2;break;case "n":f=8}a.makeMove(e[1][1],f,0)}}catch(c){ojdebug("Movelist: "+d+"\n",b),a.exception(c)}finally{a.checking.disable--}};a.paintInfo=function(b){try{b=a.uis.get("moves")+
": "+a.score.current+" ("+a.score.best+") ["+a.score.high+"] ",Object.getPrototypeOf(this).paintInfo.call(this,b)}catch(d){throw a.exception(d),d;}};a.paintCell=function(b){try{b.areas==a.cell.label?a.paintLabelCell(b):a.paintValueCell(b)}catch(d){throw a.exception(d),d;}};a.paintLabelCell=function(b){try{var d=[[50,95,75,75,25,25,5],[50,95,75,75,25,25,5],[95,50,50,5,5,50,50],[5,50,50,95,95,50,50]],f=[[5,50,50,95,95,50,50],[95,50,50,5,5,50,50],[50,95,75,75,25,25,5],[50,95,75,75,25,25,5]],c=nil;0==
b.x&&0!=b.y&&b.y!=a.size.y-1&&(c=3);b.x==a.size.x-1&&0!=b.y&&b.y!=a.size.y-1&&(c=2);0==b.y&&0!=b.x&&b.x!=a.size.x-1&&(c=0);b.y==a.size.y-1&&0!=b.x&&b.x!=a.size.x-1&&(c=1);if(c!=nil){var e=Math.floor(a.unit.x/6),l=a.unit.x-e-e,g=b.px+e,h=b.py+e,k=a.canvas.getContext("2d"),m=d[c].length-1;k.beginPath();k.moveTo(g+d[c][m]*l/100,h+f[c][m]*l/100);for(b=0;b<=m;b++)k.lineTo(g+d[c][b]*l/100,h+f[c][b]*l/100);k.lineWidth=1;k.fillStyle=a.uic.arrowFill;k.fill();k.strokeStyle=a.uic.arrowEdge;k.stroke()}}catch(y){throw a.exception(y),
y;}};a.paintValueCell=function(b){try{var d=a.canvas.getContext("2d");d.fillStyle=-2==b.label?a.uic.dark[0]:a.uic.light[0];d.fillRect(b.px,b.py,a.unit.x,a.unit.y);if(b.label!=nil&&-2!=b.label){var f=-3==b.label?a.uic.dark[0]:a.uic.dark[b.label];a.paintCircle(b,{fill:a.uic.none,stroke:f,width:2,scale:70});a.paintCircle(b,{fill:a.uic.none,stroke:f,width:1,scale:50});a.paintCircle(b,{fill:a.uic.none,stroke:f,width:1,scale:30});a.paintCircle(b,{fill:a.uic.none,stroke:f,width:1,scale:10})}if(b.value!=
nil){p=a.defaultParams(b,{});p.scale=50;var c=p.w*p.scale/200;d.save();var e=d.createRadialGradient(p.x+p.w/2-p.w/8,p.y+p.h/2-p.h/8,0,p.x+p.w/2,p.y+p.h/2,c);e.addColorStop(0,"#eeeeee");e.addColorStop(1,a.uic.dark[b.value]);d.fillStyle=e;d.shadowColor="#888888";d.shadowBlur=3;d.shadowOffsetX=d.shadowOffsetY=c/4;d.beginPath();d.arc(p.x+p.w/2,p.y+p.h/2,c,0,2*Math.PI);d.fill();d.restore()}}catch(l){throw a.exception(l),l;}}}TiltMaze.prototype=new Puzzle;
